### ISSUE TITLE
mongodb

### ISSUE THREAD

**Issue by SoonCoin** [iquidus/explorer#10]
getting this error and can't find out why

Starting cluster with pid: 15849
Unable to connect to database: mongodb://user:password@localhost:27017/explorerdb
Aborting

am i forgetting something?

and this i see when i type mongo

mongo
MongoDB shell version: 3.0.0
connecting to: test
Server has startup warnings: 
2015-05-06T23:05:29.551-0400 I CONTROL  [initandlisten] 
2015-05-06T23:05:29.551-0400 I CONTROL  [initandlisten] ** WARNING: You are running in OpenVZ which can cause issues on versions of RHEL older than RHEL6.
2015-05-06T23:05:29.551-0400 I CONTROL  [initandlisten]

**Comment by iquidus** [comment]
Currently the explorer is not compatible with mongodb 3.0.x, this will be addressed in a future update. In the mean time you will want to run mongodb 2.6.9.

**Comment by SoonCoin** [comment]
tnxs for fast response. that fixed it

**Comment by ctgiant** [comment]
I am getting the same error with mongodb shell version 2.4.9.   Any help would be appreciated.  No warning about openvz, just "Unable to connect to database: mongodb://username:password:27017/explorerdb
