### ISSUE TITLE
moneysupply not update

### ISSUE THREAD

**Issue by whatnowangga** [iquidus/explorer#101]
Hello ,
my explorer didnt update moneysupply, how to fixed that ???

**Comment by abigonion** [comment]
same question

**Comment by lozimski** [comment]
Oh Yeah ! Same

**Comment by aitorp6** [comment]
Same problem here, circulating supply is not updated. any ideas?

**Comment by loucaso** [comment]
Same

**Comment by aitorp6** [comment]
Solved, change "supply" to  "GETINFO" in settings file.

**Comment by loucaso** [comment]
I already changed but it stays

**Comment by kunalbarchha** [comment]
You need to change getmoneysupply to gettxoutsetinfo to get total circulating supply. "Getinfo" will only fetch you balance from your wallet.

**Comment by Ecrypty** [comment]
doesnt work here either, in which files can I check the api call?
