### ISSUE TITLE
node scripts/sync.js index update doesn't complete and prevents update to DB

### ISSUE THREAD

**Issue by mdrankin** [iquidus/explorer#104]
I have my cron job as follows;
*/2 * * * * cd /home/explorer && /usr/bin/node scripts/sync.js index update > /dev/null 2>&1

I did have it running every minute but either way the explorer stops randomly (about 10 - 15 times/day). I have to manually run rm -f tmp/index.pid and then re run the index update to re-sync it again.

Can this be looked at please to make it more robust?

**Comment by mathis1337** [comment]
I am having a similar issue, it is also running really slow. Maybe 3000 blocks in past 2 days. At this rate it will take well over a month to sync this.

**Comment by TheHolyRoger** [comment]
Fixed in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc
