### ISSUE TITLE
Iquidus Explorer - cannot find and error but not sync transactions

### ISSUE THREAD

**Issue by lozimski** [iquidus/explorer#109]
Ok, I can access to webpage via port. 
I can see , block number, Hashrate and peers. But not transactions at all. 
Is the any chance some one can help with it ?

> ``GET /ext/getlasttxs/0.00000001?_=1510217265480 200 2ms - 11b
GET /api/getdifficulty 200 2ms - 10b
GET /api/getnetworkhashps 200 1ms - 7b
GET /api/getconnectioncount 200 2ms - 1b
GET /api/getblockcount 200 2ms - 4b
GET /ext/summary 304 13ms
GET /api/getdifficulty 200 1ms - 10b
GET /api/getnetworkhashps 200 2ms - 7b
GET /api/getconnectioncount 200 2ms - 1b
GET /api/getblockcount 200 2ms - 4b
GET /ext/summary 304 14ms
``

**Comment by erfan007p** [comment]
nodejs scripts/sync.js index update

**Comment by lozimski** [comment]
@erfan007p Thank You it works !
It is strange a bit cron set already...
