### ISSUE TITLE
explorer No data available in table 

### ISSUE THREAD

**Issue by khushbu15** [iquidus/explorer#111]
No data available in table but block number,difficulty and connection are getting information explorer .. and browser console 1 error found
 Uncaught TypeError: Cannot read property 'cloneNode' of null.
..suggest me solution 

![image](https://user-images.githubusercontent.com/30494239/32874532-d9c09518-cab8-11e7-8d65-d9bbe5366139.png)

![image](https://user-images.githubusercontent.com/30494239/32874571-29628cca-cab9-11e7-8d30-946e27bde147.png)

**Comment by cvaldezissc** [comment]
@khushbu15 how did you do for show the block number?

**Comment by cvaldezissc** [comment]
I found the solution for me, this was starting the explorer with `npm start` in the console and in another instance after the explorer is running at npm use `sudo node scripts/sync.js index update`
This action will start the process of extract data from the wallet and save it on the mongodb.
