### ISSUE TITLE
How to set up ssl for this Project

### ISSUE THREAD

**Issue by vickyzare567** [iquidus/explorer#112]
Hello Everyone,

I am currently trying to know how to set up ssl for this server and finding nothing helpful if anyone knows how to do this then please let me know.

Thanks in advance
Regards 
VICKY

**Comment by Igor-san** [comment]
I'm use from Cloudflare https://support.cloudflare.com/hc/en-us/categories/200276247-SSL

**Comment by vickyzare567** [comment]
Cloudflare only provides generic ssl. Do you know about how to set up EV ssl

**Comment by lukepighetti** [comment]
@vickyzare567 did you find any solutions? I already have my SSL certs files and I'm just now trying to wire them up to explorer. 

All the examples I have seen for `node` and `express` are referencing syntax that not not appear to be present in this project.

**Comment by Igor-san** [comment]
Like this: (bin/instance)

  var http=require('http');
  http.createServer(app).listen(80);

var server = require('https');
  var fs = require('fs');
  var options = {
    //ca:   fs.readFileSync('ca.pem'),
    cert: fs.readFileSync('server.pem'),
    key:  fs.readFileSync('server.key'),
   };

  server.createServer(options, app).listen(443);
  /*
  var server = app.listen(app.get('port'), function() {
    debug('Express server listening on port ' + server.address().port);
  });
  */

**Comment by lukepighetti** [comment]
Thank you. My next question is the filenames for your certs, as I understand it is usually 

`cert.pem  chain.pem  fullchain.pem  privkey.pem`

any reason why yours are using different names?

**Comment by lukepighetti** [comment]
Thanks. Got it working and got http > https redirect working, but the data doesn't load reliably on the site anymore. Did I miss something stupid?

```
  var http=require('http');
  http.createServer(function (req, res) {
    res.writeHead(301, { "Location": "https://" + req.headers['host'] + req.url });
    res.end();
  }).listen(80);


  var server = require('https');
  var fs = require('fs');
  var certRoot = '/etc/letsencrypt/live/explorer.pigeoncoin.org/';

  var options = {
  //ca: fs.readFileSync('ca.pem'),
  cert: fs.readFileSync(certRoot + 'cert.pem'),
  key: fs.readFileSync(certRoot + 'privkey.pem'),
  };

  server.createServer(options, app).listen(443);

  /*
  var server = app.listen(app.get('port'), function() {
    debug('Express server listening on port ' + server.address().port);
  });
  */
```

**Comment by Igor-san** [comment]
settings.json:
  "address": "127.0.0.1:80",
....
    "theme": "Superhero",
.....
  // port to listen for requests on.
  "port" : 80,

**Comment by lukepighetti** [comment]
Yep, those are my settings. Can't figure out why the http > https redirect doesn't work reliably. But I can confirm that https works wonderfully with the fix provided by @Igor-san

**Comment by erfan007p** [comment]
use express force ssl and put it into app.js

**Comment by lukepighetti** [comment]
@erfan007p do you have an examples? I added it to `bin/instance` and it's the same problem. base URL redirects to https but nothing else does

**Comment by erfan007p** [comment]
lib/explorer.js base url should be https
app.js -> add https://www.npmjs.com/package/express-force-ssl

**Comment by lukepighetti** [comment]
Yeah that definitely just broke everything. 

If you could share your solution for setting up SSL in full that would be very much appreciated. It would save a lot of people, myself included, a lot of headaches.

**Comment by erfan007p** [comment]
Sorry i does these things as bounty hunter, figure it out your own way or just contact me

**Comment by lukepighetti** [comment]
I don't know what that means.

**Comment by NICKVALENTINO** [comment]
Any more info on this?

**Comment by flus38765** [comment]
I think that should work
* You need create a folder named `cert` and put 3 files `server.key` `server.crt` `server.ca` in there.
* run `npm install express-force-ssl` to install `express-force-ssl`
* Edit `app.js`
```js
var express = require('express')
  , path = require('path')
  , bitcoinapi = require('bitcoin-node-api')
  , favicon = require('static-favicon')
  , logger = require('morgan')
  , cookieParser = require('cookie-parser')
  , bodyParser = require('body-parser')
  , settings = require('./lib/settings')
  , routes = require('./routes/index')
  , lib = require('./lib/explorer')
  , db = require('./lib/database')
  , locale = require('./lib/locale')
  , request = require('request');

// Add this section code to here
var forceSSL = require('express-force-ssl');
var https = require('https');
var fs = require('fs');
var ssl_options = {
  key: fs.readFileSync('./cert/server.key'),
  cert: fs.readFileSync('./cert/server.crt'),
  ca: fs.readFileSync('./cert/server.ca')
};
// Add this section code to here

var app = express();

// Add this section code to here
var secureServer = https.createServer(ssl_options, app);
// Add this section code to here


......
// Add below line here
secureServer.listen(443);

module.exports = app;
```
* **Don't need to edit `lib/explorer.js`**
* Just follow it to force ssl redirect https://stackoverflow.com/a/4723302 (maybe put it in `views/layout.jade`)

**Comment by InterCrone** [comment]
Hi @ all
sorry for the nobe question but how i get the private key and the csr from the npm node???

Thanks a lot 
Peter

**Comment by lukepighetti** [comment]
letsencrypt

**Comment by voxcon** [comment]
@lukepighetti were you able to get your explorer work with ssl propperly? If you did, could you please show me your settings? That would be much appreciated!

**Comment by phuong17889** [comment]
@flus38765 thanks, work like charm

**Comment by marc968** [comment]
Hi all,
I have 4 files with letsencrypt in my repertory /etc/letsencrypt/live/mysite : cert.pem , chain.pem , fullchain.pem , privkey.pem 
Can you explain how i can change the file app.js to obtain pages of iquidus Explorer with https:// ? 
Thanks

**Comment by lukepighetti** [comment]
Hey guys, you can check my repo and see if it helps https://github.com/Pigeoncoin/explorer/commits/master

**Comment by cryptonana** [comment]
very simple just put this code in the end of line

var http=require('http');
http.createServer(app).listen(80);

var server = require('https');
var fs = require('fs');
var options = {
ca: fs.readFileSync('ca.pem'),
cert: fs.readFileSync('server.pem'),
key: fs.readFileSync('server.key'),
};

server.createServer(options, app).listen(443);
/*
var server = app.listen(app.get('port'), function() {
debug('Express server listening on port ' + server.address().port);
});
*/

then replace your EV or any SSL file

ca: fs.readFileSync('ca.pem'),
cert: fs.readFileSync('server.pem'),
key: fs.readFileSync('server.key'),

then open setting.json and replace listen port to any (dont pur 443 or 80 port) and run npm start your ssl will work but i face probelm its not auto redirect to ssl manualy redirect working fine

**Comment by broros** [comment]
after  adding the code in bin/instance I get an error

```

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:80
    at listenOnMasterHandle (net.js:1383:18)
    at rr (internal/cluster/child.js:132:12)
    at Worker.<anonymous> (internal/cluster/child.js:99:7)
    at process.onInternalMessage (internal/cluster/utils.js:47:8)
    at process.emit (events.js:326:22)
    at emit (internal/child_process.js:877:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
    at listenOnMasterHandle (net.js:1384:21)
    at rr (internal/cluster/child.js:132:12)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: null,
  port: 80
}
Cluster restarting...
^CCluster shutting down..


```
