### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zhq1** [iquidus/explorer#116]
root@vultr:~/explorer# node scripts/sync.js index reindex
script launched with pid: 19148
index cleared (reindex)

TypeError: Cannot read property 'length' of undefined
    at /root/explorer/lib/database.js:642:36
    at Request._callback (/root/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1044:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:965:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

**Comment by cvaldezissc** [comment]
i've got the same problem with the "proof-of-work" property, does anybody solved it?

**Comment by cvaldezissc** [comment]
I solved this problem, at first you have your coin daemon running properly, and you may be able to launch it methods like i.e.
`./yourcoin_daemon getblockcount`

if it returns a number, it means that it works properly, so the next step is when you start your explorer at firstfrom the explorer root path with `npm start`, then run manually the **sync.js** script, and it will be storing in your  mongodb if all the properties are correct, 

PD. look in the **settings.json** file if your wallet credentials are correct

**Comment by modInfo** [comment]
my fix:

add to coin config (yourCoin.conf)
```
txindex=1
addressindex=1
spentindex=1
```

**Comment by leegod** [comment]
@modInfo  I did, still get length error.

**Comment by leegod** [comment]
> I solved this problem, at first you have your coin daemon running properly, and you may be able to launch it methods like i.e.
> `./yourcoin_daemon getblockcount`
> 
> if it returns a number, it means that it works properly, so the next step is when you start your explorer at firstfrom the explorer root path with `npm start`, then run manually the **sync.js** script, and it will be storing in your mongodb if all the properties are correct,
> 
> PD. look in the **settings.json** file if your wallet credentials are correct

What it means? run manually sync.js script? Isn't it mean type node scripts/sync.js index reindex ?

**Comment by TheHolyRoger** [comment]
Duplicate of https://github.com/iquidus/explorer/issues/56
