### ISSUE TITLE
request:

### ISSUE THREAD

**Issue by crowdcoinChain** [iquidus/explorer#117]
hello, 
is there possibile to have
https://coinmarketcap.com/api/
intregration?

**Comment by erfan007p** [comment]
Check out smartcash commits

**Comment by crowdcoinChain** [comment]
sorry I am not able to find it in this project, link pls

**Comment by TheHolyRoger** [comment]
Exchange markets are no longer hardcoded thanks to @uaktags - https://github.com/iquidus/explorer/commit/2be23e2f8f0e446943518303efef95ca964c59a9
