### ISSUE TITLE
Iquidus Explorer - How to send coin to address

### ISSUE THREAD

**Issue by tarun1982** [iquidus/explorer#127]
We dont find API to send coin to other address. Looking for help.

**Comment by erfan007p** [comment]
Why do you need such api?

**Comment by tarun1982** [comment]
We are new to Iquidus Explorer, and we have no idea how we can transfer Coin from one address to other address.

**Comment by erfan007p** [comment]
This is not a wallet, this is just an explorer, you can use the transfer things, but doing so will put your coins in dangers,,,

**Comment by tarun1982** [comment]
Thank you for your Time and Reply.

Can you pls name a script which we can use as a wallet.

**Comment by CerratoA** [comment]
is there any more information on how to use this explorer with wallet functionality?

**Comment by uaktags** [comment]
This is a Block Explorer.
