### ISSUE TITLE
How i can get these values? settings.json

### ISSUE THREAD

**Issue by ssfs** [iquidus/explorer#130]
Hi,

How i can get these values for different coins or is it necessary to change these for all different coins?

"
  "api": {
    "blockindex": **1337**,
    "blockhash": "**1733320247b15ca2262be646397d1ffd6be953fa638ebb8f5dcbb4c2b91b34f1**",
    "txhash": "**f270cd3813254c9922a2e222a56ba745842d9112223a1394062e460b33d27b7e**",
    "address": "**RBiXWscC63Jdn1GfDtRj8hgv4Q6Zppvpwb**"
  },
"

"
 "genesis_tx": "**65f705d2f385dc85763a317b3ec000063003d6b039546af5d8195a5ec27ae410**",
"genesis_block": "**b2926a56ca64e0cd2430347e383f63ad7092f406088b9b86d6d68c2a34baef51**",
"

Thanks.

**Comment by Mustavio** [comment]
The top 4 are any value that are valid for your blockchain. They are only used in the clickable examples on the API page. so if your chain has 10000 blocks, pick any number less than or equal to 10000 for the blockindex. Then open that link, and use the blockhash that you find. Then open that link and pick a tx hash, then use the address from that tx. 

For the genesis_tx and genesis_block, I just got the values where blockindex=0

**Comment by RushOnline** [comment]
~~~
XXXcoin-cli getblockhash 1337
<BLOCKHASH>

XXXcoin-cli getblock <BLOCKHASH> | grep -A1 tx
  "tx": [
    "<TXHASH>"
~~~
