### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:9332

### ISSUE THREAD

**Issue by tina1998612** [iquidus/explorer#131]
I get the error as shown by the title when starting the explorer. I'm using Mac OS High Serria.
Any help or clue to solve this would be very much appreciated! Thanks:)

**Comment by lukepighetti** [comment]
I am also running into this issue on Ubuntu. Everything seems to be setup right. Any insight would be helpful. #142 appears to solve this but no solution is posted.

**Comment by lukepighetti** [comment]
Please see #142 where I gave a general solution. TLDR; if *coind is in daemon mode and crashing it might not be readily apparent. Make sure it runs well and your coin.conf and settings.json files are all matched up properly.
