### ISSUE TITLE
doubling blocks in Mine explorer list

### ISSUE THREAD

**Issue by Anry777** [iquidus/explorer#138]
What problem is it?
http://81.25.161.17:3002

**Comment by Anry777** [comment]
1701: dded2d8fe3a86f186104d506e5a61b53842ad742baf5c257cd3379c00a5edc4c
1702: 0c535b778f0eda00d083741708e54fb057dd5732c74299af3e1023ed08b46941
1702: c09d91f5201f307230505e6e839035e6113894b0343ea8a867e1c605967b804e
1702: 4ab05d62fb23ec53d698c0b9730ea4f16509d82b76871e54964b031ab88f9634
1703: c97c67cf733a93b51716f788b080043a18527b819c515d33466f6033362234ba
1703: 370fe16e8d476b27722cbee8d0dee3932925f451b5b22ebedb7753ee4d20f384
1704: c32dd10d4e809b73a44623a46c592486f96094b5d1242b0df68dd0471f784818
1705: e195ad5ef2a02270f937229ff74569e0e3832ae9717197d3e8fbeca40c70e672
1706: ad700453465edb98414a5e11c58ac35259fade5aef0e6f9a58adf19714cc33f0
1707: c3aa398b94365b7456ecde171e44445195d9df6752b4704424aa402a9cb8986a
1708: 6d46ab4e5724785d68c5d357f700b99563adb0777854acd6e338f65f86319e11
1708: 3bb7eef0eb5e51868d07e139ba9ede095c18d4d071359702ed89266b19541bd7
1709: 4b110ab2f29f78a60241fed8d70711ab2a7c8eca30733ccb59a8c7af01cade44
1709: bc0f27787e2fb535a090ee5097eb12ebfd4913c1bd2fbd5e23cd228415d2f0c2
1710: 45cd2b159b30638bbdc4bf6cc909696e1c3bad3b816ae45c25bd262d9b17733b
1711: 529ec02188a0ec7e88bc2ced0f42957ba61e47a3554ecababe0bce909417f640
1711: d27e13bbecd77d222414e929f6162453a5fd18aeee7b8bf25b63b072e272d854
1712: 48d107a28079154650d3fdc896e7111771351c00923794998e353fe762a201da
1712: 9826a9f6f28e2bea3ae0b072115a5e1a53b4fcdacf4c209f5a5e8f5309676d19
1712: c1a0b84eaaaba50924cbc0a4fed07d671657943a04ef0923bb311fb60ae4599b
1712: 7acdd75f3d943966c29253859afb5a92d3f028363a5373d1cdfc2f1ad46e9ca6
1712: 50e71335517cd1a0a0de6040d580bc98f13ac28fb0f1e23d2d07f927d6f53fe5
1712: 500f99841554b4eb23984d296617ec192211ecf10640bce95856137226f45640
1712: 56df2ec725b8fd0693058c13cd57d813149c5830e3d6ac7ea26bc99a412084a1
1712: 9c64d8c8111997a5f890d74a27eba1771c8b8ee21286cadaa6b4fe7147b5a28a
1712: 5ccc9b9120754414560699818b94d6bd5e806b20c8aefa9d79b00d974e5aee3f
1713: 7a7ac12513b9a1c3ec39424c2eb90bec64e5addb9933cd6081ac3b86cd337b4c
1713: 005d1e7a95f0a6c0b7a7856d955635bd3bddc9fd2794ea589b2dc533e1c03883
reindex complete (block: 1713)

**Comment by Anry777** [comment]
i was find, that block with privatesend payments slitting in explorer. 
May be - i can change anything to fix it?

**Comment by Anry777** [comment]
end other log
GET /api/getblockhash?height=1712 200 1ms - 64b
GET /api/getblock?hash=00000000001f276b686d536b17944b518770a07a823d52d9420082cd391c1254 200 5ms - 1.27kb
GET /api/getrawtransaction?txid=48d107a28079154650d3fdc896e7111771351c00923794998e353fe762a201da&decrypt=1 200 3ms - 1.53kb
GET /api/getblock?hash=00000000001f276b686d536b17944b518770a07a823d52d9420082cd391c1254 200 6ms - 1.27kb
GET /api/getrawtransaction?txid=9826a9f6f28e2bea3ae0b072115a5e1a53b4fcdacf4c209f5a5e8f5309676d19&decrypt=1 200 4ms - 3.12kb
GET /api/getblock?hash=00000000001f276b686d536b17944b518770a07a823d52d9420082cd391c1254 200 5ms - 1.27kb
GET /api/getrawtransaction?txid=d27e13bbecd77d222414e929f6162453a5fd18aeee7b8bf25b63b072e272d854&decrypt=1 200 5ms - 13.1kb
GET /api/getrawtransaction?txid=8caf9273eba2b8ce62b4778152cd3993d3fcafbfe1bba4036a0ffaea97aa6fe2&decrypt=1 200 4ms - 5.85kb
GET /api/getrawtransaction?txid=c1a0b84eaaaba50924cbc0a4fed07d671657943a04ef0923bb311fb60ae4599b&decrypt=1 200 3ms - 2.21kb
GET /api/getblock?hash=00000000001f276b686d536b17944b518770a07a823d52d9420082cd391c1254 200 6ms - 1.27kb
GET /api/getrawtransaction?txid=153f9fe75e1dc252c88016338574444c3a6eeed0e12d15452371b9529e904c5a&decrypt=1 200 3ms - 2.22kb
GET /api/getrawtransaction?txid=7acdd75f3d943966c29253859afb5a92d3f028363a5373d1cdfc2f1ad46e9ca6&decrypt=1 200 4ms - 2.21kb
GET /api/getblock?hash=00000000001f276b686d536b17944b518770a07a823d52d9420082cd391c1254 200 5ms - 1.27kb
GET /api/getrawtransaction?txid=7679ed6a65062d1a258c97370d5a9519fa28c3b7c093f6ccb4710079fb1dc048&decrypt=1 200 4ms - 3.12kb
GET /api/getrawtransaction?txid=50e71335517cd1a0a0de6040d580bc98f13ac28fb0f1e23d2d07f927d6f53fe5&decrypt=1 200 4ms - 4.02kb
GET /api/getblock?hash=00000000001f276b686d536b17944b518770a07a823d52d9420082cd391c1254 200 5ms - 1.27kb
GET /api/getrawtransaction?txid=31da08255ede441d81787e742e1b17b943dee2c896c39e0e29abedf65ba16ac1&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=989737cbae327d624c03e116f5d12a4f08b6f87ba98f9211c3772fd5222a03c9&decrypt=1 200 4ms - 2.64kb
GET /api/getrawtransaction?txid=f77e7807ccdfaa1f5cff83ffa2404ba9b89750f795d6a5c3622374f2045499d2&decrypt=1 200 4ms - 3.12kb
GET /api/getrawtransaction?txid=500f99841554b4eb23984d296617ec192211ecf10640bce95856137226f45640&decrypt=1 200 4ms - 2.22kb
GET /api/getblock?hash=00000000001f276b686d536b17944b518770a07a823d52d9420082cd391c1254 200 5ms - 1.27kb
GET /api/getrawtransaction?txid=3bb7eef0eb5e51868d07e139ba9ede095c18d4d071359702ed89266b19541bd7&decrypt=1 200 4ms - 2.22kb
GET /api/getrawtransaction?txid=56df2ec725b8fd0693058c13cd57d813149c5830e3d6ac7ea26bc99a412084a1&decrypt=1 200 26ms - 88.44kb
GET /api/getblock?hash=00000000001f276b686d536b17944b518770a07a823d52d9420082cd391c1254 200 5ms - 1.27kb
GET /api/getrawtransaction?txid=70720899c9d0abac49fc594d43b5346716841d7fd25e0aed6f928e9f034f0900&decrypt=1 200 3ms - 1.54kb
GET /api/getrawtransaction?txid=4358d57fb6c7fac140e6f8f865b07f1b9c43df2ea58e374cf3ecd49940a85810&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=80141b5a7ab550d80adda828e405423904b7b3b46da2bbfb9f4d18c090cc981a&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=5e40bcd21e5e54a36ae69b4325f4ec96b91774127301e653cb05586632297d1f&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=85b2d319a9f50cc6e90b4d4cd74dc38d292f16df480f10c1a52210e75de42c26&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=3d506257511ce276fed99023f937871b5855202ad89dbd3bc8f043b5e98fc62c&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=1122aef5c3ac739ca1ee7a1791e9224f2273d89c6a22bbf80a020829cc268a30&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=ec4cf6bc9a15c05e72de0a4a3781e8230afe5401cf2e1d0176acb2175a8a025e&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=b5d6a16063ca54c654667d274c28ac6625b1836e03d9fe9e6628162146cf3b62&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=7f88933f5c7bb738de376d9b1e38deb003b4c67c637c431c0e4949ae5ebffc66&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=9fa59f2376badaac1726e9b13087f364c032f37502276055d12cb935df0e0367&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=1b81afb92ad23480657b0c34cab43369591f8f12e60f387a53cffb569de0f767&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=a209a867f5be3ba68efd25db3be72a6e15d0d7b2036774c8fc7e792279331069&decrypt=1 200 3ms - 1.54kb
GET /api/getrawtransaction?txid=bde35e962841829a4ce75108338a6433e978a4164530b308bd81f5a7491a3f72&decrypt=1 200 3ms - 1.54kb
GET /api/getrawtransaction?txid=2bba9063d4e657ef2c367ea41f721920e2f842c4f376489b56eb6c78dafc5f73&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=46874f7a5ddd0cd5b069229ceb7e1ba9116014cf86f1e632d5ef518b91f83474&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=afea2d3f3ddd405636398d6dd8484c3d6f89f7f86a89e57128c739db00825175&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=df811f575c88c433f76c952d046dcd94a386e68932167d3498ed0aca872cd979&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=92dcf36fc8b418fad84197d47757acf3afa90dd992f7351b5bdd36f11552577d&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=b5a8861e2a53876a1c6c35826b5eb72569cf7fe20d088cae8c0b08f297df127e&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=692456f60d3e7a7c21cadbc315e16ca3e71e4f111f019cc9b5df5a4d5de30d7f&decrypt=1 200 3ms - 1.54kb
GET /api/getrawtransaction?txid=0acbd4af7aabbea1665b52a255dcea72b8cc40edfb9704badaf9de9125f65a83&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=dbc593b1528258a98aed6ca2d23620b6ba77808a4bcfe9da76c12a6cbfdb4b86&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=4b1972b0d4fa87634789f23d6bd60f9f331cb5da8bd74144cab65fa485b69792&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=58b31b0cca34169bc76c3f14a0ee262cf506f07d3c15e0a3cdfa1aeef3e0d492&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=bf93fac27bf24d0295308e75244355042271d5be2e2f817c956fbf5c1ddff192&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=cfb9e2c42a4f5ff0dcc640dba9e8d8dd1d94339441ee9223d10bbfd5e2ae3693&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=3eaf9d83f46f80c621b784f1d83c3cbb18c0b5ddd3c06899c3b79d241b54fa93&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=4be0d5aa76d9cc263ae63a7785054ad4d75b48f2b6b513a70e26404b969c769c&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=f955a0db3c8089bf013d5b14ad5a73f40d865b070145623da2605b7bb0de4e9d&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=f7b91bcf025385b1ad8eaa483666d274ff635ee90ecd3edb4e99a4e7b174399f&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=e383b244ea9e747e19c45dd7c07f573d2a3aebff8aa578c5bfcd24f83e7ed1a0&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=4f9a6e6b23bef256936e592611c40f93959878f2f52eb43c927986a3ecce8aa8&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=6515902aa15b03e8385ccf74478696570d2800cf170c0e5c032c1e88e9bf7aa9&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=d4c0e9c21594875201fff09ed8a72008150ab676e8283d04dbcd7bf6d43fc2a9&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=800afc4f3f1b6b11d95948dd6348da1b60795455c2ee4e739f205b10de20f5b8&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=31da08255ede441d81787e742e1b17b943dee2c896c39e0e29abedf65ba16ac1&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=96d99ff06b1e3c619a9186556754d563ab0a889f073069fa034b0d78654311c6&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=e83aaff0f7f10d38d3e11441eeffdfe0f3c2ebef5119f71c16a1e06c88ab4ecb&decrypt=1 200 5ms - 1.52kb
GET /api/getrawtransaction?txid=2ab758fe72e6d1d2a7085f37a2423adefa7ad78482257e4268e3375e0a4e82df&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=0e84ed004c0609901a54ca365d7119c66a0b07097ddc68e265523323a7bfcbdf&decrypt=1 200 4ms - 1.52kb
GET /api/getrawtransaction?txid=f7e15d17c043957a71877d10a98cb4776c46f748aeca75f1d22f6a6ff01507ea&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=beb7b71371f867ddd5bc5683195ff752cea47bf98064a5a8344a7df586ee8bfe&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=9c64d8c8111997a5f890d74a27eba1771c8b8ee21286cadaa6b4fe7147b5a28a&decrypt=1 200 6ms - 12.07kb
GET /api/getblock?hash=00000000001f276b686d536b17944b518770a07a823d52d9420082cd391c1254 200 4ms - 1.27kb
GET /api/getrawtransaction?txid=7b0b006234eadcf37d8d9276f820b1a2eb8d23ddb3c7f0c8806ff406aa9aed61&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=35e82541cc7dd5bd27a1e3679fbb911e648150472fdeef79607301e5867ff96b&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=5aa55d5d7ae471d9cae9cc9904d6fb0b32dc15ded54a080a2a8e28342842f3e5&decrypt=1 200 4ms - 1.54kb
GET /api/getrawtransaction?txid=e06baeeb99d674e34d59e8da5f7f4d04f35432adae7e2338370fbcb628b117fb&decrypt=1 200 3ms - 1.52kb
GET /api/getrawtransaction?txid=5ccc9b9120754414560699818b94d6bd5e806b20c8aefa9d79b00d974e5aee3f&decrypt=1 200 3ms - 2.22kb
GET /api/getblock?hash=00000000001f276b686d536b17944b518770a07a823d52d9420082cd391c1254 200 5ms - 1.27kb
GET /api/getrawtransaction?txid=36120b4622542a4148001bebb26a18cf33e0a81e379d17f25e99524dec3cbe2d&decrypt=1 200 3ms - 2.69kb

**Comment by ChristianGrieger** [comment]
Has the same here but after block 50000 its back to normal for me.

**Comment by ChristianGrieger** [comment]
![error](https://user-images.githubusercontent.com/8712219/36072973-42639f98-0f29-11e8-9f5a-a6fda32d736b.png)

**Comment by ChristianGrieger** [comment]
Okay looks like its no error it just displays many times because the block has multiple transactions :)

**Comment by TheHolyRoger** [comment]
Discussion here: https://github.com/iquidus/explorer/issues/238
