### ISSUE TITLE
npm start error while running sync.js file

### ISSUE THREAD

**Issue by ebrahimasifismail** [iquidus/explorer#139]
root@xpaycoinexplorer:~/explorer# npm start

> explorer@1.6.1 start /root/explorer
> node --stack-size=10000 ./bin/cluster

Starting cluster with pid: 29468
{ [Error: Invalid params, response status code: 401] code: -32602 }
GET /api/getblockcount 200 10ms - 39b
{ [Error: Invalid params, response status code: 401] code: -32602 }
GET /api/getconnectioncount 200 3ms - 39b
{ [Error: Invalid params, response status code: 401] code: -32602 }
GET /api/getblockhash?height=-5 200 15ms - 39b
{ [Error: Invalid params, response status code: 401] code: -32602 }
GET /api/getblock?hash=There%20was%20an%20error.%20Check%20your%20console. 200 3ms - 39b
...................................................................................................................................................................................................................while running sync.js

root@xpaycoinexplorer:~/explorer# node scripts/sync.js index update
script launched with pid: 29598

TypeError: Cannot read property 'length' of undefined
    at /root/explorer/lib/database.js:642:36
    at Request._callback (/root/explorer/lib/explorer.js:107:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:187:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:1044:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:965:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
....................................................................................................................................................................................................................
stuck right here... somebody pls help.......

**Comment by bibz0r** [comment]
Having the same problem.

> GET /api/getblockcount 200 4ms - 1b
> { [Error: Block number out of range.] code: -1 }
> GET /api/getblockhash?**height=-2** 200 4ms - 39b
> { [Error: Block not found] code: -5 }
> GET /api/getblock?hash=There%20was%20an%20error.%20Check%20your%20console. 200 4ms - 39b
> 

I guess the problem is that iquidus is looking for blockheight -2. In the case of the previous user it even shows blockheight -5.

Why does that happen?

**Comment by Igor-san** [comment]
} else if (mode == 'update') {
                    if (stats.last<1) stats.last=1; ///trick
                    db.update_tx_db(settings.coin, stats.last, stats.count, settings.update_timeout, function(){
                      db.update_richlist('received', function(){

**Comment by bisto007** [comment]
nowadays coin github doesnt have makefile.unix 
then how we can compile?
Please anyone

**Comment by laugh26** [comment]
chmod 775 -R explorer
