### ISSUE TITLE
Please add BTC38 API

### ISSUE THREAD

**Issue by mammix2** [iquidus/explorer#14]
Hi
Firstly, this is a great explorer, iquidus explorer and node.js are very modular

Please can you add API support for BTC38 markets

http://www.btc38.com/help/document/2581.html
You might need to use google translate to view the page unless you can understand Chinese :)

Thanks

**Comment by mammix2** [comment]
Hi, any chance of adding BTC38 API?

**Comment by followtheart** [comment]
这个得让官方自己来搞吧

**Comment by uaktags** [comment]
Closing as the website never seems to load. If anyone wants to translate and offer me the api endpoints available, i'll work on one.
