### ISSUE TITLE
Error! : Search found no results for: HQu1Vdb43UeUf1jzgPtSmkdoNkdCgV5Xs8

### ISSUE THREAD

**Issue by Crypto75** [iquidus/explorer#143]
this my coin address but i will not found in explorer i have many coin address still but not find it. 
i have one my coin qt wallet and generate new address than after go to explorer and find it so occur this message   **Search found no results for: HQu1Vdb43UeUf1jzgPtSmkdoNkdCgV5Xs8**

plz help me any idea 
thank you

**Comment by GroovyGrovesy** [comment]
If an address has no transactions associated with it it will not show in the explorer, send some coins to it and it will show up!

**Comment by newfulluser** [comment]
I have the same problem, fresh install and search function always says the address cannot be found...

An old install of that same explorer on the same coin works just fine and can find all wallets correctly.

**Comment by TheHolyRoger** [comment]
Wait for indexing to complete.
