### ISSUE TITLE
Mongo connect failed

### ISSUE THREAD

**Issue by cryptomaxsun** [iquidus/explorer#145]
mongo
MongoDB shell version: 2.4.9
connecting to: test
Wed Feb 14 14:44:41.957 Error: couldn't connect to server 127.0.0.1:27017 at src/mongo/shell/mongo.js:145
exception: connect failed

How fix?
Ubuntu 14.04

**Comment by sigwo** [comment]
Start mongo.

**Comment by humdevs** [comment]
That happened to me after I rebooted the system without shutting down iquidus first and it corrupted the database. I had to do a fresh install to get it working.
