### ISSUE TITLE
Unable to connect to database

### ISSUE THREAD

**Issue by glitchyethos** [iquidus/explorer#147]
Hello,

I am getting an error when I run npm start:

Unable to connect to database: mongo://user:password@localhost:27017/explorerdb Aborting

I pretty much set all the ports to 27017 to see whats going on but I am still getting this issue. The only port that is open is the port regarding the altcoin which is 9333. 

Can anyone help me out as to what is happening?

**Comment by leegod** [comment]
I am having same issue. Have you solved?

**Comment by OctoBitIO** [comment]
I had the same problem. Solving by changed localhost to 127.0.0.1

**Comment by dekm** [comment]
Having this same issue changing to 127.0.0.1 did not work.
