### ISSUE TITLE
Transaction shown as many outputs

### ISSUE THREAD

**Issue by GroovyGrovesy** [iquidus/explorer#149]
Hi,  

I didn't really know how to explain this one so I'll use pictures.  The first one is from my explorer which I have just set up, notice all the red -6 outputs with the same time and hash.

![image](https://user-images.githubusercontent.com/7847340/36564462-4c080b34-1815-11e8-8013-2dcfb0f1f37b.png)

The below picture is of the same address from a different explorer, notice all of the -6's have been grouped into a single transaction!

![image](https://user-images.githubusercontent.com/7847340/36564526-8b569382-1815-11e8-8eb3-bad39e10f024.png)

How can I get my explorer to group the outputs like that into a single output???  I've looked through the settings and cannot see anything that would do this!

Any ideas?

**Comment by TheHolyRoger** [comment]
Fixed in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc
