### ISSUE TITLE
how to get chart like that?

### ISSUE THREAD

**Issue by kampungcoin** [iquidus/explorer#152]
![image](https://user-images.githubusercontent.com/36219575/36909157-379cd738-1e78-11e8-9ed2-12f47f4454c6.png)

**Comment by popupcoin** [comment]
https://www.amcharts.com/download/

this is the chart solution that most of the installs are working with 

`npm install @amcharts/amcharts4
npm install @amcharts/amcharts4-geodata`

**Comment by TheHolyRoger** [comment]
This requires historical stat logging. Not something we're looking at for now.

**Comment by TheHolyRoger** [comment]
Duplicate of https://github.com/iquidus/explorer/issues/134
