### ISSUE TITLE
Any tradesatoshi api script out there?

### ISSUE THREAD

**Issue by 2g4y1** [iquidus/explorer#153]
Is there any script for Tradesatoshi API (https://tradesatoshi.com/Home/Api)?

Seen it here: https://explorer.buzzcoin.info/markets/tradesatoshi and https://blockchain.plusonecoin.org/markets/tradesatoshi

but i can´t find a git repo for this coins

regards
2g

**Comment by 2g4y1** [comment]
[tradesatoshi.zip](https://github.com/iquidus/explorer/files/3131496/tradesatoshi.zip)
I created this and its working

**Comment by TheHolyRoger** [comment]
Merged https://github.com/iquidus/explorer/commit/4c4089a7c77e63cd7563b864909f7cd910468dc7
