### ISSUE TITLE
Issue with Sync

### ISSUE THREAD

**Issue by vm06007** [iquidus/explorer#163]
Hello, I'm getting this issue when syncing/checking:

sudo node scripts/sync.js index check
tx not found: 56c101dfe5984ab7f392e5ea1e2240252233924e98de8024b54cdc3393953485
tx not found: 16bc7e177b171e03b5467d19d42ecf6c6ac5a1b95305412e83a40605b4ac7471
tx not found: d88e1d64a494bdd542a95ad0eeca85dd0332b22163b52d0ef4b7221becd25737
tx not found: f3136016d5a50a462d0cab0c6409cc49d107799c78e44602e8eea00d6df58040
/home/wwwroot/lib/explorer.js:344
          module.exports.syncLoop(tx.vout.length, function (loop) {
TypeError: Cannot read property 'length' of undefined

also similar with running reindex it dies on some block 
and then on the explorer I can see almost all blocks, although rich-list is empty
why the rich-list is empty? Although I can view blocks and some transactions manually

![screen shot 2018-03-22 at 11 02 59 am](https://user-images.githubusercontent.com/1138692/37739914-a16cb758-2dc0-11e8-8bcb-d5e28d1c7228.JPG)

**Comment by vm06007** [comment]
last message here helped: https://github.com/iquidus/explorer/issues/118

**Comment by voxcon** [comment]
@vm06007 can you please specify how the last post from #118 has helped you to solve this the property 'length' problem?

**Comment by lukepighetti** [comment]
@voxcon Please post the solution for others. :)

**Comment by voxcon** [comment]
@lukepighetti use the provided patch in #118 and specify an rpcport in your coin.config file.
