### ISSUE TITLE
/home/explorer/lib/explorer.js:252 (RangeError: Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by mdrankin** [iquidus/explorer#164]
Getting an issue now when attempting to sync. Have tried the solution given in issue #72 and issue #83 which is causing the issue as I get the same problem when attempting to sync right after forcing a delete of the index.pid file.

/home/explorer/lib/explorer.js:252 (RangeError: Maximum call stack size exceeded)
    module.exports.syncLoop(array.length, function (loop) {
                                                   ^

RangeError: Maximum call stack size exceeded
    at /home/explorer/lib/explorer.js:252:52
    at Object.next (/home/explorer/lib/explorer.js:189:18)
    at /home/explorer/lib/explorer.js:260:14
    at Object.next (/home/explorer/lib/explorer.js:189:18)
    at /home/explorer/lib/explorer.js:260:14
    at Object.next (/home/explorer/lib/explorer.js:189:18)
    at /home/explorer/lib/explorer.js:260:14
    at Object.next (/home/explorer/lib/explorer.js:189:18)
    at /home/explorer/lib/explorer.js:260:14
    at Object.next (/home/explorer/lib/explorer.js:189:18)
    at /home/explorer/lib/explorer.js:260:14
    at Object.next (/home/explorer/lib/explorer.js:189:18)
    at /home/explorer/lib/explorer.js:260:14
    at Object.next (/home/explorer/lib/explorer.js:189:18)
    at /home/explorer/lib/explorer.js:260:14
    at Object.next (/home/explorer/lib/explorer.js:189:18)

**Comment by avandurmen0001** [comment]
node --stack-size=20000 scripts/sync.js index reindex

**Comment by mdrankin** [comment]
Thanks, that seems to be running now. Will see how it goes.

**Comment by mdrankin** [comment]
Note that I did drop the database and recreate it a couple of times previously and still encountered the issue. I guess if the index is stored elsewhere then it may work. It was falling over at block 344,381, and so far it's indexed 295,000 blocks

**Comment by mdrankin** [comment]
My mongo username credentials keep dropping out so the sync stopped. Re-created the username and started it again. Would be better if Iquidus used a more reliable database engine.

**Comment by mdrankin** [comment]
After my Mongo credentials have stopped working for the 100th time, the re-syncing seems to be loading some transactions or blocks in our of order. They are certainly being displayed out of order. See below

![image](https://user-images.githubusercontent.com/17876223/39120600-3bdd1bf4-4732-11e8-973e-08ac73a9af1b.png)

**Comment by avandurmen0001** [comment]
you need to reindex

**Comment by TheHolyRoger** [comment]
Reindex, it's massively improved in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc
