### ISSUE TITLE
Sync.js TypeError

### ISSUE THREAD

**Issue by MystPhysX** [iquidus/explorer#17]
Hey,

I'm running Iquidus on Debian Wheezy with MongoDB 2.6.10, Node.js 0.10.40 and the latest Iquidus. After following the instructions on the Github and configuring everything I ran Iquidus and tried to sync the database with my coin's blockchain but I get this when running the following command:

root@server1:~/explorer# /usr/bin/node scripts/sync.js index update
script launched with pid: 17933

TypeError: Cannot read property 'length' of undefined
    at /root/explorer/lib/database.js:622:36
    at Request._callback (/root/explorer/lib/explorer.js:106:14)
    at Request.self.callback (/root/explorer/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/root/explorer/node_modules/request/request.js:985:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/root/explorer/node_modules/request/request.js:936:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

Any ideas on what I'm doing wrong?

**Comment by iquidus** [comment]
are you running the *coind with both the -dameon and -txindex flags? Alternatively you can put txindex=1 in your coins .conf.

**Comment by MystPhysX** [comment]
I've got txindex=1, listen=1 and daemon=1 in the *.conf.

**Comment by iquidus** [comment]
please join the jumbucks community slack at http://slack.getjumbucks.com and come find me (xocel) in the #iquidus channel, will be easier to get to the bottom of this if we can chat properly :)

**Comment by MystPhysX** [comment]
It turns out the coin daemon could not bind the rpc port specified in the code. A new port specified in the .conf file using rpcport= and updating the settings.json file to reflect that port change fixed the issue. I hope other people find this helpful. Thank you.

**Comment by leegod** [comment]
@MystPhysX  Thanks!!!!! you Saved Life.
