### ISSUE TITLE
Richlist pie chart sums to 126%

### ISSUE THREAD

**Issue by lukepighetti** [iquidus/explorer#171]
http://explorer.pigeoncoin.org/richlist

Any idea why the richlist would sum to 126%?

I tried reindexing and it solved it for a few hours and it went back to 126%.

**Comment by exit-exit** [comment]
I have the same issue. would like to know what it may be

**Comment by lukepighetti** [comment]
exit-exit I found it was because I didn't have transaction indexing enabled
