### ISSUE TITLE
Copyright removal fee?

### ISSUE THREAD

**Issue by leegod** [iquidus/explorer#172]
If I want to remove [ Powered by Iquidus explorer ] character below, 

who should I contact and consult about fee for that?  

contact me : wsxdrfv@hanmail.net

**Comment by uaktags** [comment]
It's literally a setting in the settings.json to change the footer text and footer url. I would personally like there to be a change to the theme to have the Powered By separate from the settings=>Footer Text.

**Comment by bibz0r** [comment]
@uaktags Are you sure about that? I can't find any settings in the settings.json file.

Was this removed? @iquidus could you please elaborate on this?

**Comment by newfulluser** [comment]
I can't find it either, but I dont want to remove it, I just want to add more stuff in the footer, does anyone know where is the footer stored? Thanks

**Comment by jayanh** [comment]
you should open file layout.jade under explorer/views edit line 215. and npm install again

**Comment by seangler** [comment]
how to add social media link on footer
