### ISSUE TITLE
Can you diagnose 

### ISSUE THREAD

**Issue by bluwhizqy** [iquidus/explorer#174]
Hi,

We are wondering if you can diagnose what is going on in the Davor Explorer. 

Its not connecting and we dont understand why? Is there an explanation?

Im not part of davor incase anyone sees this and thinks i am.

**Comment by bluwhizqy** [comment]
http://explorer.davor.io

heres the Link

**Comment by uaktags** [comment]
Explorer doesn't load, no error message shown, atleast provide some log/output. Closing.
