### ISSUE TITLE
MongoDB Performance

### ISSUE THREAD

**Issue by xieta** [iquidus/explorer#178]
I seem to remember Iquidus syncing a million+ block chain much much more quickly on earlier versions of Mongo.

Is there a recommended mongo storage engine for Iquidus?
Are there optimizations which need to be made to the mongo instance for longer chains?

Currently, I'm testing with MongoDB v3.6.3 but have switched from wiredTiger to mmapv1 storage engine.

After about 1.4 million blocks, I'm seeing in the logs a new block being imported (initial sync) every 3 seconds. The vCPU aren't pegged and there is free memory. Are there some buffers which need to be increased for longer chains?

**Comment by xieta** [comment]
Experimenting now - with adding a mongo index on explorerdb.txes.

**Comment by cmorland** [comment]
Any luck in improving index speed?

**Comment by makeholer** [comment]
Any tips on improving the speed guys?

**Comment by makeholer** [comment]
> Any luck in improving index speed?

Any tips on improving the speed guys?



> I seem to remember Iquidus syncing a million+ block chain much much more quickly on earlier versions of Mongo.
> 
> Is there a recommended mongo storage engine for Iquidus?
> Are there optimizations which need to be made to the mongo instance for longer chains?
> 
> Currently, I'm testing with MongoDB v3.6.3 but have switched from wiredTiger to mmapv1 storage engine.
> 
> After about 1.4 million blocks, I'm seeing in the logs a new block being imported (initial sync) every 3 seconds. The vCPU aren't pegged and there is free memory. Are there some buffers which need to be increased for longer chains?

**Comment by cmorland** [comment]
I ended up using ElectrumX + and an RPC based frontend

https://github.com/kyuupichan/electrumx
https://github.com/janoside/btc-rpc-explorer

**Comment by TheHolyRoger** [comment]
@cmorland
@xieta
@makeholer 
Performance is much improved ^1.7.3
