### ISSUE TITLE
How can I create a rich list with this explorer?

### ISSUE THREAD

**Issue by Tvcoin** [iquidus/explorer#179]
I would integrate a rich list in the explorer, is this possible and how do I do this?

**Comment by 2g4y1** [comment]
https://github.com/iquidus/explorer/blob/c8ac131aed4f065b4f327ec379eaef2a006e5f50/settings.json.template#L65
set this to true

**Comment by Tvcoin** [comment]
And I can also use this explorer for BCX?

**Comment by Tvcoin** [comment]
It’s a BTC fork.. can anyons help me ?

**Comment by uaktags** [comment]
OP's original issue is resolved. Of course iquidus could be used with Xcoin, just run it and see what happens. If OP needs anything else, a new issue should be made.
