### ISSUE TITLE
How to setup more than 2 explorers in same VPS?

### ISSUE THREAD

**Issue by leegod** [iquidus/explorer#180]
as title, how to setup? 

I made new folder (explorer2) and git clone to there, 

set new settings.json file, mongo, use explothb   (different db name). 

Then how?

**Comment by Igor-san** [comment]
Yes it is possible. Just different ports (3001,3002 ...), access to the databases and wallets.

**Comment by uaktags** [comment]
Issue is resolved and explained in prev comment. 
There's efforts being made to clusterize the explorer, but for the purpose of OP, what's written is enough.
