### ISSUE TITLE
If mining reward is 0, explorer does not show its record?

### ISSUE THREAD

**Issue by leegod** [iquidus/explorer#181]
I premined whole coin up to total supply. So I set block subsidy reward as 0 at source.

But I can mine at qt wallet, but does not shows transaction record. And its reward is 0.

So explorer does not show its record.

Is this normal and intended? 

Then, tx fee should occurs and when reward is not 0, explorer also will show it?

**Comment by regtable** [comment]
saves database room if anything. when you make a transaction it jumps the block height. i know its not brilliant but why do you need to see the empty blocks ;-)

**Comment by dnprod** [comment]
likely blocks of zero value do not have a payment address, blocks without tx addresses are probably not displayed.

**Comment by TheHolyRoger** [comment]
Fixed in https://github.com/iquidus/explorer/commit/cae9a67da6ba55b84ce5c99904aec901e45dea4d
