### ISSUE TITLE
enable CORS?

### ISSUE THREAD

**Issue by lukepighetti** [iquidus/explorer#182]
I've tried adding this snippet to the base of `app.js` with no success.

```
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});
```

Has anyone successfully enabled CORS on iquidus/explorer ?

**Comment by lukepighetti** [comment]
Put it right after `var app = express()` declaration

```
var app = express();

// enable CORS

app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});
```

**Comment by schuesslerf** [comment]
Hello,

I tried following this to enable CORS there to have another website being able to send XHTTP requests there...for a request to /ext/getmoneysupply, this worked.. however, when requesting the API, like /api/getnetworkhashps, then I still get a CORS error saying that is has been blocked... Do I have to enable it seperately for the API somewhere?
