### ISSUE TITLE
 error Error: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by thepcb** [iquidus/explorer#183]
How to fix this?

npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--production"
npm ERR! cwd /home/jyrki/explorer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10

npm http GET https://registry.npmjs.org/qr-image
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/markdown-js/0.0.3
npm http GET https://registry.npmjs.org/static-favicon
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jyrki/explorer/npm-debug.log
npm ERR! not ok code 0

**Comment by bumbacoin** [comment]
short answer

# npm config set strict-ssl false

**Comment by thepcb** [comment]
How about this error?

body-parser deprecated undefined extended: provide extended option app.js:47:20
(node:2022) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:2022) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

Thank you

**Comment by uaktags** [comment]
These aren't errors but warnings. This is due to the age of the repo vs the current state of the dependencies.
