### ISSUE TITLE
Why is /ext/getmoneysupply different than RPC total_amount

### ISSUE THREAD

**Issue by lukepighetti** [iquidus/explorer#190]
/ext/getmoneysupply

`389930024.84191614`

coin-cli gettxoutsetinfo

`"total_amount": 389960000.00000000`

**Comment by uaktags** [comment]
https://github.com/iquidus/explorer/blob/bf99bb56eb4f0437c59d54a424882c2f839ca521/lib/explorer.js#L222-L247
To me it just looks like you haven't had a sync happen between the /etc/getmoneysupply being called and the gettxoutsetinfo. As we can see in the code, if you're using the TXOUTSET setting, then it's calling this RPC. There's no data manipulation at all.
