### ISSUE TITLE
duplicate blocks in front page 

### ISSUE THREAD

**Issue by regtable** [iquidus/explorer#191]
is there any reason as to why the front page brings up duplicated block heights but when you click the block itself it shows all transaction hashes as normal?
like this
https://imgur.com/a/PbZ4EMH

also the top 100 seems to be odd. there is a grey section that from sync slowly creeps over every other pie section untill it overwhelms the area and says 1000+% for some
http://178.62.45.184:3001/richlist
the wallet is not fully in sync but set to txindex as it goes along. if this is just a bug related to not being in full sync before starting the indexing il drop it all and await full sync.

**Comment by Igor-san** [comment]
These are transactions that are part of a block of height 40079 http://178.62.45.184:3001/block/5ed3a7b76056d7eadf14c2b60fe6d69a2275c028219e4795a76f99af2b47506f. Naturally, there are several of them.

**Comment by regtable** [comment]
Oh ok so the front end just shows each transaction? I thought it showed it
in block form. Makes sense then if only one tx in block it shows once if 2
it shows twice. Thanks for clarity. Any idea on the top 100 issue?

**Comment by leshacat** [comment]
@regtable @Igor-san I thought it was supposed to be one per block as well...?

Any updates?

Thanks

**Comment by leshacat** [comment]
UPDATE: https://github.com/iquidus/explorer/issues/238

close this after reading that issue ticket

**Comment by regtable** [comment]
Yeah it seems iquidus actually puts his on the main 0age and dupe blocks
are literally that more has in same block. Confusing but not an error

**Comment by regtable** [comment]
Also top 100 is just f*cky. Multiple pos coins with issues. I'm writing my
own now 🤣

**Comment by uaktags** [comment]
Nothing really to answer in this issue as it's not an issue in its current form. Closed for now.
