### ISSUE TITLE
Is there a way to get more than 100 lines in the getaddress API ?

### ISSUE THREAD

**Issue by Coriac** [iquidus/explorer#195]
I'm trying to get a full transaction list from an address. 
Is there any parameter to send in the URL request to overdrive the 100 lines limit of the API ?

**Comment by makeholer** [comment]
Have you found any solution for this?

**Comment by feyrian** [comment]
You have to set the `txcount` parameter in the settings.json file.
When you change it for a higher number than before you'll have to launch the sync.js script in check or reindex mode: `nodejs scripts/sync.js index check` or `nodejs scripts/sync.js index reindex`

**Comment by TheHolyRoger** [comment]
Options added in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc
