### ISSUE TITLE
Explorer doesn't update 

### ISSUE THREAD

**Issue by ozosbitt-project** [iquidus/explorer#196]
Hello, 

I have everything setup correctly, i can access to the website and do able to see difficulty and block 1,
and no error found.

every time i ran this command  

node scripts/sync.js index reindex
 node scripts/sync.js index update

it came success but the the latest block i keep getting is 1st block, doesn't able to fetch the latest block

any idea?

**Comment by ozosbitt-project** [comment]
issue solved

**Comment by MLBotPlatform** [comment]
wanna share how?
