### ISSUE TITLE
cryptopia api

### ISSUE THREAD

**Issue by SoonCoin** [iquidus/explorer#20]
is it possible to get cryptopia.co.nz in markets also please.

**Comment by ctgiant** [comment]
I would also love to have this feature if you can get around to implementing it.  Thanks.

**Comment by iquidus** [comment]
I'm not very familiar with cryptopia but will look into this, I'm busy working on a few other things atm so it may be a little while before I get to this. If someone wants to make a pull request I will gladly merge it. Or if someone wants to sponsor the feature addition I can bump it up the todo list and get it done asap.

**Comment by madross** [comment]
im am also looking for this intergration aswell as c-cex we at incakoin can donate you some nka if that would be a resonable sponsor

**Comment by iquidus** [comment]
A pull request has been made adding c-cex and cryptopia here: https://github.com/iquidus/explorer/pull/23 . I will be merging this once I have double checked everything (although I doubt there will be any issues). In the mean time you can merge locally.
