### ISSUE TITLE
Stuck on Block

### ISSUE THREAD

**Issue by buddilla** [iquidus/explorer#201]
I have reindexed the explorer 3 times tried to update a bazillion times. I can not for life of me figure out why the explorer gets stuck on the same block every time. If I manually search for the next block it will show up on the explorer homepage. 

http://explore.ohmcoin.org

![screen shot 2018-06-11 at 4 21 33 pm](https://user-images.githubusercontent.com/13294167/41262116-e49d03da-6d93-11e8-8aeb-9e13e60ce121.png)

**Comment by buddilla** [comment]
Looks like if the explorer is not "gracefully" shut down before a server shutdown or reboot it will corrupt the db. Lame...

**Comment by buddilla** [comment]
Still occurring even from a fresh install

**Comment by ReeCore** [comment]
use newdb 

mongo
use explorernewdb

:)
