### ISSUE TITLE
{ [Error: socket hang up] code: 'ECONNRESET' }

### ISSUE THREAD

**Issue by diveshark** [iquidus/explorer#205]
Hi, I am getting the following response when the page is served and I am receiving the following error across the served page.

> There was an error. Check your console.

Starting cluster with pid: 3807
GET / 304 986ms
GET /vendor/jqplot/jquery.jqplot.css 304 7ms
GET /themes/Cerulean/bootstrap.min.css 304 5ms
GET /vendor/jqplot/jquery.jqplot.min.js 304 6ms
GET /vendor/jqplot/plugins/jqplot.dateAxisRenderer.min.js 304 1ms
GET /vendor/jqplot/plugins/jqplot.ohlcRenderer.min.js 304 0ms
GET /stylesheets/style.css 304 0ms
GET /vendor/jqplot/plugins/jqplot.pieRenderer.min.js 304 3ms
GET /vendor/jqplot/plugins/jqplot.highlighter.min.js 304 4ms
GET /vendor/jqplot/plugins/jqplot.categoryAxisRenderer.min.js 304 2ms
GET /vendor/jqplot/plugins/jqplot.barRenderer.min.js 304 2ms
GET /javascripts/chart.js 304 0ms
GET /themes/fonts/glyphicons-halflings-regular.woff2 304 1ms
{ [Error: socket hang up] code: 'ECONNRESET' }
GET /api/getdifficulty 200 29ms - 39b
GET /ext/getlasttxs/0.00000001?_=1529532577850 200 22ms - 11b
{ [Error: socket hang up] code: 'ECONNRESET' }
GET /api/getconnectioncount 200 5ms - 39b
{ [Error: socket hang up] code: 'ECONNRESET' }
GET /api/getblockcount 200 3ms - 39b
GET /ext/summary 304 87ms

**Comment by emanbayani** [comment]
Firewall!

**Comment by jmuilwijk** [comment]
I am facing this issue too, confirmed my daemon is up and running and connecting to the explorer script.
As soon as it tries to call any of the methods OP does it will result in the same issue, @emanbayani you suggest a firewall issue how can i see if this too in my case? As far as i could see no firewall was enabled.

**Comment by jmuilwijk** [comment]
In my case it wasn't a firewall issue, i found that the daemon cannot be executed on it's default port using the solution in https://github.com/iquidus/explorer/issues/184#issuecomment-391281136
