### ISSUE TITLE
network dont appear country

### ISSUE THREAD

**Issue by ReeCore** [iquidus/explorer#213]
Hi!

some days ago, my explorer dont show countrys in network, i check and same in diferents chains and vps

could you tell me if API is down? 

thanks

**Comment by emanbayani** [comment]
I'm having the same issue!

**Comment by nibbles83** [comment]
Correct, freegeoip ended their free service at the beginning of the month. You can create a free account on the new ipstack site and will need to modify the code to pass the api key through.
There is a limit to the amount of requests per day now, so you may be better finding an alternative geo service if ipstack doesn't fit your needs.

**Comment by dnprod** [comment]
seems like the npm 'geoip2' package could be useful here

**Comment by 2g4y1** [comment]
https://github.com/ipsum-network/ips-explorer/commit/e39654df388a12e0c3e16da75a166d74f5678a25
Found this commit from Aviator-Coding

**Comment by ReeCore** [comment]
thanks, i will try just now

**Comment by emanbayani** [comment]
ipsum-network@e39654d
Found this commit from Aviator-Coding

Did anyone try this?

**Comment by ReeCore** [comment]
Yes. And works. You can check in our explorer: http://explorer.reecore.org/

You must wait some long time to begin works

**Comment by ReeCore** [comment]
@ProjectHelixCoin, did you make a account in ipstack.com? need make your own account and link to get countrys list

**Comment by ProjectHelixCoin** [comment]
@ReeCore I got it working, thanks! It turned out that it didn't check the nodes that were already cached, nodes that were found after i changed it did get their country added. After clearing the cache and restarting the wallet to find new connections, everything is working perfectly.

**Comment by cryptozeny** [comment]
thanks guys!
