### ISSUE TITLE
Can iquidus explorer work with an ethereum private network?

### ISSUE THREAD

**Issue by gittygoo** [iquidus/explorer#216]
I can't seem to get this to work, is it even possible at at all?

**Comment by iquidus** [comment]
It does not support ethereum based chains.

You could fork ubiq spectrum (its 3 separate codebases, interface, crawler, api), make changes required 
 and it will work great. Some work will be required as currently its purposed for ubiq.

https://github.com/ubiq/spectrum-interface
https://github.com/ubiq/spectrum-api
https://github.com/ubiq/spectrum-crawler

**Comment by uaktags** [comment]
Closing.
