### ISSUE TITLE
running on a hosted service

### ISSUE THREAD

**Issue by regtable** [iquidus/explorer#218]
i am running iquidus on a hosted node. everything worked well on my small machine at home but when i moved to a similar sized hosted nod its consuming 110% cpu for the explorer itself. can this be lowered at all?
im going to guess at stacksize 1000 per vcpu so 2000 for 2vcpu? just wondering as i dont want to upgrade the size again to find its consuming everything in the host machine due to some value i can change to limit usage to my machine and not a cancerous node instance

**Comment by nibbles83** [comment]
Try running the npm in production mode.

NODE_ENV=production npm start

It reduces the cpu requirement by about 50% for me.

**Comment by regtable** [comment]
thankyou i will try this. i dotn want to get banned from a 3rd service. as i have upgraded to the highest i can afford but it seems to always use 110-120% no mater the size

**Comment by regtable** [comment]
@nibbles83 that worked sat at about 25-30% usage now thanks. means i can probable use the smaller nodes now too
