### ISSUE TITLE
address totals includes negative-confirmation-count-blocks

### ISSUE THREAD

**Issue by trickyReborn** [iquidus/explorer#22]
... and all transactions within this block are confirmed in explorer (which is wrong).

like here
http://explorer.trickycoin.com/block/59f32221376a7e4943cb216fcd0aedf8ade74a290e36d0ffd066ffb3d5d52057

I'll try to figure out by myself, but it's still an issue to report ;) Cheers!

**Comment by iquidus** [comment]
Hmm odd, I have not encountered -1 confirmations before, so it isn't being handled correctly. Will make sure it's fixed in next update. Thanks for reporting this.
