### ISSUE TITLE
Run 'npm start' to create database structures before running this script.

### ISSUE THREAD

**Issue by spijkermenno** [iquidus/explorer#224]
I have the explorer up and running and the cronjob worked for a few minutes, after some time it stopped working and now when i try to run the **sudo node sync.js index update** it gives this error:

$ sudo node sync.js index update

No settings file found. Continuing using defaults!
script launched with pid: 16456
Run 'npm start' to create database structures before running this script.
unable to remove lock: ./tmp/index.pid

i can't seem to fix it, can anyone help?

**Comment by stephen-coding** [comment]
I run "npm start" in one window first and then I open a 2nd window (Ctrl + Alt + T on Linux) to run the "sudo node sync.js index update" script, when the sync script is running a lock file is created in the tmp folder, so if you stopped a previous sync that didnt finish yet youll need to go into the tmp folder and delete that index.pid file before being able to run it again
