### ISSUE TITLE
how to set ssl on server

### ISSUE THREAD

**Issue by cryptonana** [iquidus/explorer#230]
how to set SSL on server with Iquidus Explorer please guide me

**Comment by iquidus** [comment]
alternatively you can run iquidus on a random port (e.g 3001) and use nginx or caddy as a reverse proxy, managing SSL certs and 80 -> 443 redirect via the nginx/caddy configs. Caddy requires less configuration for this type of set up and has built in letsencrypt support.

**Comment by wh1tebeard** [comment]
apache is pretty easy to set up as a reverse proxy as well...
