### ISSUE TITLE
Connections span is not In the correct place.

### ISSUE THREAD

**Issue by jamiecruickshank** [iquidus/explorer#235]
Hi, 
I have setup a new explorer and the .connections span is sitting half way up the page, also the Powered by Iquidus text is sitting below the footer. 
I have checked other setups and its also the same, I am using Mac OS with Safari and Chrome, both with the same results. 

<img width="1275" alt="screen shot 2018-11-02 at 0 26 32" src="https://user-images.githubusercontent.com/4493594/47861361-faf82700-de35-11e8-9acf-92939205229a.png">

**Comment by feyrian** [comment]
Yeah there's a mistake in the `/views/layout.jade` file.
Edit it and in line 216 put an extra space in front of `.col-md-4`
The code must be aligned as in line 195.
```
So, this line:
     .col-md-4
Become:
      .col-md-4
notice there's one more space in front of the .col-md-4
```

**Comment by cryptozeny** [comment]
@feyrian good point! thanks. you should commit this :smiley:

**Comment by feyrian** [comment]
There is already a PR for that: #219

**Comment by TheHolyRoger** [comment]
Fixed in https://github.com/iquidus/explorer/pull/219
