### ISSUE TITLE
update_tx_db - coinstats - last variable - Any issues with lowering? Should this be a config option?

### ISSUE THREAD

**Issue by togoshigekata** [iquidus/explorer#236]
A fresh blank index on my explorer has been taking longer and longer each time I do it,
Watching over it a little, I suspected it was re-doing work,
I found a constant in the code that seemed interesting,
(I noticed my explorer crashes periodically as well [from checking index.pid file])
I think the explorer could get in a loop of redoing work,
Experimenting, I set the constant to 10 and havent had any issues seeing it re-doing work so far

https://github.com/iquidus/explorer/blob/c8ac131aed4f065b4f327ec379eaef2a006e5f50/lib/database.js#L630

1. Are there any issues with setting this constant lower?
2. Should this constant be made into a config variable?

How to view Coin Stats in Mongo DB:
```
mongo
use explorerdb
db.coinstats.find()
```

**Comment by TheHolyRoger** [comment]
Sounds like you're running into a stack size issue but indexing has been improved in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc so this shouldn't be a problem anymore.
