### ISSUE TITLE
Getting hashrate working for POW/POS altcoin

### ISSUE THREAD

**Issue by Coryvmcs1** [iquidus/explorer#24]
Hey M8. Trying to get this to work with x11 altcoin and unable to get the hashrate to display and work. Any ideas How I can get our explorer to extract the Hash info?

**Comment by madross** [comment]
did you install the explorer in the root directory of the server/vps i was helping a user set it up a few weeks back and they had the same issue once they reinstalled it in the root dirrectory the issue fixed itself also have you set it to POW to show the hashrate

**Comment by Coryvmcs1** [comment]
It's in its own directory in root. 
It's set for POW as well

**Comment by ctgiant** [comment]
did you change   line 129 of settings.json from:
"nethash": "getnetworkhashps",
to: 
"nethash": "netmhashps",

**Comment by Coryvmcs1** [comment]
We did and for some reason it won't display as it is a hybrid pow/pos. I think that is the issue.

**Comment by mmitech** [comment]
The only way to get the nethashrate  in POW/POS hybrid coins is with "getmininginfo" option :

     
    "blocks" : 9501,
    "currentblocksize" : 1000,
    "currentblocktx" : 0,
    "difficulty" : {
        "proof-of-work" : 13.31161407,
        "proof-of-stake" : 0.00044244,
        "search-interval" : 1
    },
    "blockvalue" : 10000000000,
    "netmhashps" : 1216.44568251,
    "netstakeweight" : 20646.85482433,
    "errors" : "",
    "pooledtx" : 0,
    "stakeweight" : {
        "minimum" : 0,
        "maximum" : 0,
        "combined" : 0
    },
    "stakeinterest" : 1000000,
    "testnet" : false

Then you can see the "netmhashps" in the output, so  either explorer could take the "netmhashps" value from the "getmininginfo" output or you will have to add  "getnetworkhashps" to your daemon commands in next releases.

I would like to see this solved in explorer before I change it in the coin daemon in the next releases.

**Comment by rudy4682** [comment]
see https://github.com/rudy4682/explorer

Fixed get_hashrate -- netmhashps Added Hybrid POS difficulty

**Comment by Coryvmcs1** [comment]
Thanks for all your help.

**Comment by iquidus** [comment]
thanks @rudy4682 , your contributions are much appreciated. I'll get master caught up with your branch shortly :)

**Comment by iquidus** [comment]
rudys fix has been merged into master

**Comment by 631250005** [comment]
> netmhashps

thanks！that fixd my issue
