### ISSUE TITLE
Iquidus for Bitcoin, too slow?

### ISSUE THREAD

**Issue by makeholer** [iquidus/explorer#240]
I'm making an bitcoin explorer for our company, It seems that it will take months to Iquidus update all the database, anyone using it for Bitcoin? Is there any solution to update the database faster?

**Comment by cryptozeny** [comment]
btc blockchain is so huge. it's normal.

**Comment by makeholer** [comment]
I've analyzed the process and my conclusion is that it's not possible to use Iquidus for Bitcoin, because the number of transactions per minute it is processing is lower than the number of transactions going to the blockchain today... Is there any options?

**Comment by cryptozeny** [comment]
i see btc has too many txs... you can try insight with btc ver =< `0.15`

**Comment by makeholer** [comment]
> i see btc has too many txs... you can try insight with btc ver =< `0.15`

I already tried insight, full synced, it is VERY slow because it don't use mongo, i think it use something like microsoft access, any query take like 10 seconds...

**Comment by uaktags** [comment]
#252 has the solution of removing the explorer api and going directly to the daemon for faster syncing. But it still stands that BTC is a huge blockchain.

closing, we're about as fast as we can get.
