### ISSUE TITLE
cannot click icon on mobile chrome (for twitter, youtube, etc...)

### ISSUE THREAD

**Issue by cryptozeny** [iquidus/explorer#243]
https://github.com/iquidus/explorer/blob/30f91a05c5cd1b83c721652c1807232ab9727ebc/views/layout.jade#L199

```jade
    .navbar.navbar-default.navbar-fixed-bottom.hidden-xs
      .col-md-4
        if settings.display.twitter
          ul.nav.navbar-nav
            li.pull-left
              a#twitter-icon(href="https://twitter.com/#{settings.twitter}", target='_blank')
                span.glyphicon.fa.fa-twitter
```
The same goes for other coin explorers. `.hidden` is wrong?

![image](https://user-images.githubusercontent.com/37016180/49147269-91d9d580-f347-11e8-8b56-259d5fc4df42.png)

you can test on mobile chrome.
https://florincoin.info/
https://explorer.sugarchain.org/

**Comment by cryptozeny** [comment]
https://github.com/sugarchain-project/explorer/issues/3

**Comment by uaktags** [comment]
So this issue appears to be that the footer of "Powered by Iquidus Explorer" seems to overtake the portion for the icon. This is due to the col-md-4 divs. They're setup for medium screensize rather than small. To make it work, it'd have to be swapped out for col-sm-4
