### ISSUE TITLE
Default entry length 10 on first page

### ISSUE THREAD

**Issue by cryptozeny** [iquidus/explorer#245]
![screenshot from 2018-11-30 05-29-04](https://user-images.githubusercontent.com/37016180/49250119-66e3a480-f461-11e8-8fee-119e16506f74.png)

its default is 10. how can i change this value as a default?

ie:
```
25
50
100
200
```

**Comment by feyrian** [comment]
Set the `pageLength` option on the datatable initialisation.
Exple on the index.jade view, add `pageLength: 50` on the recent-table Datable initialisation:
```javascript
var rtable = $('#recent-table').dataTable( {  
  pageLength: 50,
  autoWidth: true,      
  searching: false,
  // ...
});
```

**Comment by cryptozeny** [comment]
wow great! i'll try it!!

**Comment by TheHolyRoger** [comment]
Settings added in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc
