### ISSUE TITLE
sudo node scripts/sync.js index update WONT update past Genesis Block 1

### ISSUE THREAD

**Issue by MLBotPlatform** [iquidus/explorer#248]
everything is working fine except the sudo node scripts/sync.js index update

I run npm start on main terminal with NO errors and then open another SSH windows and did the following

i also tried sudo node scripts/sync.js index reindex with output : 

index cleared (reindex)
1: 5eea8b1a9d1a57deb8382c5ba72c8ea7262d97863cf3f03cca690266ce2b3733

then sudo node scripts/sync.js index update with output : update complete (block: 1) 

normally it should process all my blocks but nothing.

website is up but only shows the genesis block
<img width="921" alt="screenshot_23" src="https://user-images.githubusercontent.com/45493203/49765246-89d04d00-fcda-11e8-8a7d-a8dbba9c9828.png">

so everything runs normal, Mongo runs normal, i selected the explorerdb..

but it wont sync further than block 1

there is no index.pid in the tmp folder as i dont have an issue running the above script.

**Comment by wmcorless** [comment]
Run Your coin with -txindex

**Comment by MLBotPlatform** [comment]
i did, i tried both txindex=1 on conf file , and again without it on conf file with ./coind -txindex..
as i said i tried everything. just that it syncs only block 1

**Comment by wmcorless** [comment]
use this to load the coin ./coind -daemon -txindex
place the following in your crontab and reboot
*/1 * * * * cd /root/explorer && /usr/bin/nodejs scripts/sync.js index update > /dev/null 2>&1
*/2 * * * * cd /root/explorer && /usr/bin/nodejs scripts/sync.js market > /dev/null 2>&1
*/5 * * * * cd /root/explorer && /usr/bin/nodejs scripts/peers.js > /dev/null 2>&1

**Comment by MLBotPlatform** [comment]
friend, i appreciate you trying to help but do you understand the problem in the 1st place? 

even if i do the crontab and reboot, the index update gets stuck at genesis block. 

there is no point doing the crontab, till i can get a full initial index update of all blocks. crontab is to auto do that. But it fails in the 1st place....

**Comment by wmcorless** [comment]
I had the same problem but I fixed it.

**Comment by MLBotPlatform** [comment]
read this again. slowly.

> everything is working fine except the sudo node scripts/sync.js index update
> 
> I run npm start on main terminal with NO errors and then open another SSH windows and did the following
> 
> i also tried sudo node scripts/sync.js index reindex with output :
> 
> index cleared (reindex)
> 1: 5eea8b1a9d1a57deb8382c5ba72c8ea7262d97863cf3f03cca690266ce2b3733
> 
> then sudo node scripts/sync.js index update with output : update complete (block: 1)
> 
> normally it should process all my blocks but nothing.
> 
> website is up but only shows the genesis block
> <img alt="screenshot_23" width="921" src="https://user-images.githubusercontent.com/45493203/49765246-89d04d00-fcda-11e8-8a7d-a8dbba9c9828.png">
> 
> so everything runs normal, Mongo runs normal, i selected the explorerdb..
> 
> but it wont sync further than block 1
> 
> there is no index.pid in the tmp folder as i dont have an issue running the above script.

**Comment by wmcorless** [comment]
is this a PIVX coin?

**Comment by minblock** [comment]
How many blocks do you have in your chain you need more than 1 block for them to show up.

**Comment by wmcorless** [comment]
when I had the same problem, I beleive mongo was crashing. Instead of
forever I changed it to systemd. either that or or the txindex was the
issue.
I have both iquidus and ciquidus running fine at paccoinexplorer.net and
explorer.kema.io

**Comment by MLBotPlatform** [comment]
i had about 2.000 blocks. yes a pivx coin. with ciquidus it run perfectly.

**Comment by minblock** [comment]
oh cool I never new that iquidus can handle pos

**Comment by MLBotPlatform** [comment]
it can.. inside the settings.json there is an option for POW/POS/Hybrid for hashrate i think so it should. also seen example of pos coins with iquidus.

**Comment by Hser2bio** [comment]
@MLBotPlatform that is because you need put the correct way to get info:

/ how to calculate current coin supply
  // COINBASE : total sent from coinbase (PoW)
  // GETINFO : retreive from getinfo api call (PoS)
  // HEAVY: retreive from heavys getsupply api call
  // BALANCES : total of all address balances
  // TXOUTSET : retreive from gettxoutsetinfo api call
  "supply": "TXOUTSET",

change to your coin kind, reindex and you will get fixed

**Comment by samqju** [comment]
@MLBotPlatform I hope you have found the solution for your problem, If not Try this

go to your explorer and search for 1 i.e. block 1 and when search returns it will give you option to go to next block , move forward coule of blocks and then update, it will run smoothly

![exp](https://user-images.githubusercontent.com/32988468/54471338-53c0ce80-47dd-11e9-80bd-5a7c918a56fc.jpg)

i saw this problem on Zcash code based coins
