### ISSUE TITLE
Trying to install this...running into errors :(

### ISSUE THREAD

**Issue by Yzord** [iquidus/explorer#25]
Hi,

Want to make a BC explorer for a coin, but after installing and getting the page i get this

GET /api/getconnectioncount 200 3ms - 39b
GET /ext/getlasttxs/100/0.00000001?_=1447333764940 200 5ms - 11b
{ [Error: socket hang up] code: 'ECONNRESET' }
GET /api/getblockcount 200 4ms - 39b
GET /ext/summary 304 34ms
{ [Error: socket hang up] code: 'ECONNRESET' }
GET /api/getdifficulty 200 5ms - 39b
{ [Error: socket hang up] code: 'ECONNRESET' }
GET /api/getnetworkhashps 200 2ms - 39b
{ [Error: socket hang up] code: 'ECONNRESET' }
GET /api/getconnectioncount 200 3ms - 39b
{ [Error: socket hang up] code: 'ECONNRESET' }
GET /api/getblockcount 200 5ms - 39b
GET /ext/summary 304 26ms

I have put explorer map in the root of the coin, but do i have to place it in .testcoin map or normal testcoin map?

Can you help me with this?

**Comment by mmitech** [comment]
ECONNRESET usually means the port that you are trying to use is already being used, check what program/service is using the port you are using by:

     sudo netstat -tulpn | grep :'YOUR PORT NUMBER HERE'

**Comment by iquidus** [comment]
the explorer appears to be failing to communicate with the coin daemon. Check your wallet settings in explorer and your rpc settings in *coin.conf
