### ISSUE TITLE
Install for Windows

### ISSUE THREAD

**Issue by username1565** [iquidus/explorer#251]
Hello. Do you have instructions or exe-file (portable zip-file)
to run or install iquidus explorer on Windows?
If you have, can you add this to Releases?

**Comment by uaktags** [comment]
From my experience, it runs just fine via Windows. I do quite a bit of localized testing on Windows without any setup changes needed.

for the cron, I did end up doing something similar to this for creating Scheduled Tasks:

```
sync.ps1

$path="C:\Users\tim\iquid-test2\tmp\index.pid"
if([System.IO.File]::Exists($path)){
    Remove-Item -path C:\Users\tim\iquid-test2\tmp\index.pid
}
$ErrorActionPreference="SilentlyContinue"
Stop-Transcript | out-null
$ErrorActionPreference = "Continue"
Start-Transcript -path .\output.txt -append
cd C:\Users\tim\iquid-test2; node --stack_size=40000 .\scripts\sync.js index update
Stop-Transcript
```

Hope that helps

**Comment by uaktags** [comment]
As mentioned, this runs quite well in windows doing basically the same setup as you would with Linux. Above is the powershell script for it, works fine as well. Not quite sure what else is desired, so closing.
