### ISSUE TITLE
Does not update

### ISSUE THREAD

**Issue by dimecoinco** [iquidus/explorer#26]
We had this installed and the explorer did not update itself. It was clearly in touch with the network because you could search all the block heights after the point the explorer did not update its first page. That is, it stopped at block height 10000 (for example), but you could key in 10076 and get accurate results. I had a look around the internet and I believe it is mongodb issue (not sure, though). Has anyone had this issue and how was it solved?

**Comment by mmitech** [comment]
Did you set your cronjob to update the block index ? 


*It is recommended to have this script launched via a cronjob at 1+ min intervals.*

**crontab**

*Example crontab; update index every minute and market data every 2 minutes*

    */1 * * * * cd /path/to/explorer && /usr/bin/node scripts/sync.js index update > /dev/null 2>&1
    */2 * * * * cd /path/to/explorer && /usr/bin/node scripts/sync.js market > /dev/null 2>&1

**Comment by iquidus** [comment]
Check your cronjob has been set correctly, and that the update script has not left its lockgile behind in a previous run if killed prematurely. (rm tmp/index.pid)

**Comment by dimecoinco** [comment]
Thanks guys, I got fed up. But I decide to have another go and after checking here, it was indeed tmp/index.pid  ... Thanks again, and for making the explorer free and open source.

**Comment by legends420** [comment]
This worked rm tmp/index.pid then run cron jobs to update everything worked well for me

**Comment by saydulk** [comment]
root@Explorer:~/explorer# npm start

> explorer@1.6.1 start /root/explorer
> node --stack-size=10000 ./bin/cluster

Starting cluster with pid: 14974

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:904:11)
    at net.js:1084:30
    at Object.1:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at child_process.js:396:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
    at process.<anonymous> (child_process.js:395:13)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at Pipe.channel.onread (child_process.js:347:11)

**Comment by hronopay** [comment]
Hi!  i've faced the same problem... (Ubuntu 16.4) 
Removing of index.pid led to another issue...
`root@ServerN2:~# find . -name index.pid
./explorer/tmp/index.pid
root@ServerN2:~# cd explorer
root@ServerN2:~/explorer# node scripts/sync.js index reindex
script launched with pid: 3385
Unable to connect to explorer API
index cleared (reindex)
reindex complete (block: 1)
root@ServerN2:~/explorer# node scripts/sync.js index update
script launched with pid: 3401
Unable to connect to explorer API
update complete (block: 1)
root@ServerN2:~/explorer# node scripts/sync.js index update
script launched with pid: 3448
1: e6d0f819ad886ad355b661559884e0136d5cfb59de15d2008ca137c514192f66
update complete (block: 1)
root@ServerN2:~/explorer# node scripts/sync.js index update
script launched with pid: 3483
update complete (block: 1)
root@ServerN2:~/explorer# node scripts/sync.js index reindex
script launched with pid: 3497
index cleared (reindex)
1: e6d0f819ad886ad355b661559884e0136d5cfb59de15d2008ca137c514192f66
reindex complete (block: 1)
root@ServerN2:~/explorer# node scripts/sync.js index reindex
script launched with pid: 3549
Unable to connect to explorer API
index cleared (reindex)
reindex complete (block: 1)
root@ServerN2:~/explorer# node scripts/sync.js index update
script launched with pid: 3563
Unable to connect to explorer API
update complete (block: 1)
root@ServerN2:~/explorer# node scripts/sync.js index update
script launched with pid: 3685
1: e6d0f819ad886ad355b661559884e0136d5cfb59de15d2008ca137c514192f66
update complete (block: 1)
root@ServerN2:~/explorer# node scripts/sync.js index reindex
script launched with pid: 3743
index cleared (reindex)
1: e6d0f819ad886ad355b661559884e0136d5cfb59de15d2008ca137c514192f66
reindex complete (block: 1)
root@ServerN2:~/explorer# node scripts/sync.js index update
script launched with pid: 3761
update complete (block: 1)
root@ServerN2:~/explorer# node scripts/sync.js index check
script launched with pid: 3775
check complete (block: 1)
root@ServerN2:~/explorer#`
(index.pid was removed via WinSCP)
Explorer now shows only one 1st genesis block...   Can you help me? what to try
Thanks in advance!

**Comment by dirty-harry** [comment]
Did you ever get this sorted?

**Comment by zex24** [comment]
If you are getting this error "Error: bind EADDRINUSE" you are probably trying to use a port which is already used by some other process. Changing the port should solve the problem.
