### ISSUE TITLE
Transactions Not Showing

### ISSUE THREAD

**Issue by aanwhs** [iquidus/explorer#260]
I have successfully prepared iquidus explorer, but there are some that don't appear. Please look directly!
blockchain.activacoin.site (update domain).

Please help.

**Comment by uaktags** [comment]
You're using a forked version of Iquidus (IPUM forked from Ciquidus, forked from here).

I would run:
```
node scripts/sync.js index check
```
or 
```
node scripts/sync.js index reindex
```
And make sure that you let it run. Perhaps do it in a screen so you don't Ctrl C it or anything else, and let it complete on its own. To me it just looks like the initial sync was ended prematurely.

**Comment by aanwhs** [comment]
Thank you, it works.
But, why explorer is stuck.

**Comment by uaktags** [comment]
I'm not sure I understand the issue? What's stuck?

**Comment by TheHolyRoger** [comment]
Indexing massively improved in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc
