### ISSUE TITLE
Hosting on a subpath

### ISSUE THREAD

**Issue by lukepighetti** [iquidus/explorer#261]
Hi there,

I do not believe this is an Nginx problem. There doesn't seem to be a way to set the subpath. For example, hosting on `explorer.mycoin.com` works, `mycoin.com` works, but `mycoin.com/explorer` doesn't seem to work. All links are pointing towards `mycoin.com/` which is 404 in that context.

Any recommendations for how to PR this?

**Comment by uaktags** [comment]
This may need a rewrite in nginx as-well/or the usage of express-namespace. I have no need for this, so I probably won't look into something like this for a few weeks. But in a simple testing, I see that just using nginx rewrites you can get everything basically working with the exception of css/js/img. API works, pages load, etc. However, that's as far as I got with it. good luck

**Comment by uaktags** [comment]
Okay, got it working with a few more tweaks. You'll have to update the layout.jade, any jade file that has ajax calls in it, etc. So i'd recommend for your PR to include some things like:

settings.json having a basepath string like "basepath": "/". To do this you'll need to add it to settings.js as well as an export. Then you have to add it to app.js for "app.set".

With this setting in place, you can update your jades for all paths to have settings.basepth + "/....."

**Comment by lukepighetti** [comment]
Yep, I got it handled. I'll try to make a PR but no promises, I think my version of iquidius is different enough to make it difficult to make the PR. Thanks for the help!
