### ISSUE TITLE
Error in Block index update

### ISSUE THREAD

**Issue by charliegama** [iquidus/explorer#262]
Error in indexe block. 

GET /api/getblock?hash=00000084e57ac8a5ec8aff845d18f462dafd6f5369dc2481fe87ff6d6ccd9dab 200 7ms - 779b

**{ [Error: No such mempool transaction. Use -txindex to enable blockchain transaction queries. Use gettransaction for wallet transactions.] code: -5 }**

### Try some ways but not - Any suggestions

 nodejs scripts/sync.js index update
script launched with pid: 3907
tx not found: 4a0d779ab369ed94f20659696c9722e5952b01a6d87e263c51715d42a6278290
update complete (block: 1)

**Comment by uaktags** [comment]
```
Use -txindex to enable blockchain transaction queries.
```
