### ISSUE TITLE
Wrong send/ Recieved amounts

### ISSUE THREAD

**Issue by axelkrumbach** [iquidus/explorer#263]
Iam using the current iquidus running at https://bdtscan.io

https://bdtscan.io/tx/9f44e387be901ba415086cc326ac6ba2a948656b11dd64558fbcdda3262e49a8
should be 250 coins instead of 0.20862855.
Iam using POS.

**Comment by uaktags** [comment]
https://bdtscan.io/api/getblock?hash=4a1df7fe66cf2765f6a05850c336016acbd7a1285699f264467b24593725ae2f
can you tell use what "getblock 4a1df7fe66cf2765f6a05850c336016acbd7a1285699f264467b24593725ae2f" shows from the coin's daemon?

**Comment by uaktags** [comment]
closing as now the server is gone.
