### ISSUE TITLE
problem with market data and toFixed(8)

### ISSUE THREAD

**Issue by FireWalkerX** [iquidus/explorer#27]
This is what i see in the market link

explorer/views/markets/bittrex.jade:24 22| tbody 23| tr > 24| td #{marketdata.data.summary.High.toFixed(8)} 25| td #{marketdata.data.summary.Low.toFixed(8)} 26| td #{marketdata.data.summary.Volume.toFixed(8)} 27| td.hidden-xs #{marketdata.data.summary.Bid.toFixed(8)} Cannot call method 'toFixed' of undefined

**Comment by borodiansky** [comment]
From your explorer directory, type the following:

node scripts/sync.js market

This will propagate the initial market data.  Once that's complete, add in the cron job as per the documentation:

*/2 * * * * cd /path/to/explorer && /path/to/node scripts/sync.js market > /dev/null 2>&1

The reason this is happening is there's no data to operate on.

**Comment by iquidus** [comment]
Thanks @borodiansky !
