### ISSUE TITLE
Known moderate severity security vulnerability detected in morgan < 1.9.1 defined in package.json. package.json update suggested: morgan ~> 1.9.1.

### ISSUE THREAD

**Issue by regtable** [iquidus/explorer#271]
does this just need updating in the package.json?

**Comment by regtable** [comment]
closing issue not tested but have ran through each independant package 1x1 installing and removing all depreciated packages and installing the main prefered package here is the list of deps will attempt to fix/port errors if any crop up.
`  "dependencies": {
    "bitcoin-core": "^2.0.0",
    "body-parser": "^1.18.3",
    "cookie-parser": "^1.4.4",
    "debug": "^4.1.1",
    "express": "^4.16.4",
    "jsonminify": "^0.4.1",
    "markdown-js": "0.0.4",
    "mongodb": "^3.2.2",
    "mongoose": "^5.4.20",
    "morgan": "^1.9.1",
    "pug": "^2.0.3",
    "qr-image": "^3.2.0",
    "request": "^2.88.0",
    "static-favicon": "^2.0.0-alpha"
  },
  "devDependencies": {
    "jasmine": "^3.3.1"
  }
}`

**Comment by regtable** [comment]
anybody wants to try these just change your package.json to reflect the above then npm install on a fresh instance.

**Comment by wh1tebeard** [comment]
I was getting all empty tables before...
I tried this on a fresh install and got:

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/whitebeard/explorer/node_modules/debug/src/index.js:9:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
/home/whitebeard/explorer/node_modules/debug/src/node.js:132
        let val = process.env[key];

**Comment by TheHolyRoger** [comment]
Fixed in https://github.com/iquidus/explorer/pull/310
