### ISSUE TITLE
Error TOP100 richlist

### ISSUE THREAD

**Issue by DigitalCoin1** [iquidus/explorer#272]
rl_received.jade:13 11| tbody 12| - var count = 0 > 13| each item in received 14| - count = count + 1 15| - var itemFixed = item.received / 100000000 16| tr Cannot read property 'length' of null

![image](https://user-images.githubusercontent.com/32315718/55841057-101f6300-5b04-11e9-8c4a-cf892cc20726.png)

**Comment by TheHolyRoger** [comment]
Fixed in https://github.com/iquidus/explorer/pull/305
