### ISSUE TITLE
npm ERR! Make sure you have the latest version of node.js and npm installed.

### ISSUE THREAD

**Issue by Eisenhauer252** [iquidus/explorer#273]
npm ERR! Linux 4.15.18-12-pve
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! explorer@1.6.1 start: `node --stack-size=10000 ./bin/cluster`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the explorer@1.6.1 start script 'node --stack-size=10000 ./bin/cluster'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the explorer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --stack-size=10000 ./bin/cluster
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs explorer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls explorer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/explorer/npm-debug.log

What can i do ?   :(

**Comment by TheHolyRoger** [comment]
Looks like an issue with your node installation, try a more recent version like v12 or v8
