### ISSUE TITLE
Cannot display Top100 Richlist 

### ISSUE THREAD

**Issue by longvic0** [iquidus/explorer#274]
Hi all,
 I'm running an explorer : http://notebc.miners.rocks/richlist
There's no data in richlists collections. 
 Could you please give me the solution to update the richlist of the blockchain explorer.

Thank you,

**Comment by vrfebet** [comment]
Hi
you need reindex db coin
start daemon with parameters
<your coin> -reindex-chainstate -daemon -txindex
and after that, they run:
<your coin> -daemon -txindex

**Comment by vrfebet** [comment]
start daemon with parameters
your coin -reindex-chainstate -daemon -txindex
and after that, they run:
your coin -daemon -txindex

**Comment by longvic0** [comment]
Thank you. 
 My problem occurs when the explorer is in progress of indexing / updating the database.
 When index/update finish, the sync.js script will update the richlists collection.

**Comment by uaktags** [comment]
That's because that's when the sync script updates the stats.
