### ISSUE TITLE
which rpc port to use?

### ISSUE THREAD

**Issue by bylucy** [iquidus/explorer#276]
Hello,
how can i solve this problem?
which rpc port to use?

root@neweraexplorer1:~/newera/src# ./newerad -daemon -reindex -txindex
Newera server starting
root@neweraexplorer1:~/newera/src# Error: An error occurred while setting up the RPC port 34842 for listening on IPv4: bind: Address already in use

**Comment by longvic0** [comment]
Please check your service to find which process is using that port

> netstat -lp |grep 34742

Change your listen rpcport for your coin in conf file. then start again.

**Comment by bylucy** [comment]
Thanks for replying, I decided it

**Comment by bylucy** [comment]
now such a problem:
how to fix connection area in the template?
http://188.166.88.160:3001

**Comment by longvic0** [comment]
go to views/layout.jade  line 216 then add one more space before col-md-

**Comment by bylucy** [comment]
tank you

**Comment by bylucy** [comment]
Hello,
how to change domain to explorer?
how to install the ssl certificate in the domain?

**Comment by longvic0** [comment]
Just run your explorer with nginx 
SSL certificate work with nginx proxy and ssl config.
 I've done with my forked explorer: https://github.com/longvic0/explorer

**Comment by bylucy** [comment]
Hello,Thanks for replying
how to run with nginx please describe more

**Comment by uaktags** [comment]
This really isn't a system-admin's guide and we should be staying focus to just iquidus explorer's "issues". I'd suggest things like stackoverflow for these more unrelated questions.

However, in hopes that this closes your issue, 
http://www.nikola-breznjak.com/blog/javascript/nodejs/using-nginx-as-a-reverse-proxy-in-front-of-your-node-js-application/

**Comment by bylucy** [comment]
ok
tanks

**Comment by uaktags** [comment]
No problem, hope that helps. Proxy-Pass is basically the solution though for getting nginx to listen on 80/443 and redirect your other ports as needed (3001 for us).

If that resolves your issue, may I ask that you close this "issue" and then just open a new one if you run into any more issues/concerns with the explorer? Helps to keep things organized since the github maintainer hasn't been present to help clean it.
