### ISSUE TITLE
npm start hanging

### ISSUE THREAD

**Issue by haznit** [iquidus/explorer#281]
Hey guys,

I am getting the following situation when I try to run "npm start":

root@vmd39041:~/explorer# npm start

> explorer@1.6.1 start /root/explorer
> node --stack-size=10000 ./bin/cluster

Starting cluster with pid: 17026

I get nothing more than that. 
I'm pretty confident about the coin settings in settings.json.

The only diff I see with this coin is that the daemon is installed in /root instead of the typical /usr/local/bin location.
However even moving the files to /usr/local/bin and starting the wallet from there doesn't help.
Is there anything else I could check here to see why the output is hanging...?

Thanks,

**Comment by longvic0** [comment]
Hi 
  I think you'd better use forever to start your explorer

> Install Forever to keep the js running
> # sudo npm install forever -g
> # sudo npm install forever-monitor
> 
> Start the Explorer
> # forever start bin/cluster

**Comment by cool007zqw** [comment]
@longvic0 
Sorry but what you proposed does not solve it. Thank you all the same.

**Comment by cool007zqw** [comment]
Solution found! (More precisely, problem found)

@haznit 

What is the value of  "port" (about line 32) in you setting.json?
Whatever it is, use that port to open the web interface, instead of the port in "address": "whatever : port". I think the port in "address" makes no use.
