### ISSUE TITLE
How to list all missing blocks in the explorer?

### ISSUE THREAD

**Issue by longvic0** [iquidus/explorer#282]
Hi all,
  I have a problem with the explorer database. There's some missing blocks that I can't find in the explorer database ( txes collection ). 
  My temporary solution to create the list is:
  Export all blockindex of the explorer database. Use mysql or Excel to find the non-exist blocks in my explorer.
 When the datase is bigger, 1M -- 7M blocks, this solution is a bad idea.
 Is there any mongodb query to find out the missing blockindex of the explorer ?
 Please help me!
Regards,

**Comment by uaktags** [comment]
I haven't found an ellegant solution, but I have found one.

https://github.com/uaktags/explorer/blob/434910e060c86cf59b3698508925b3998d2b64f6/scripts/sync.js#L287-L310

Basically, I create an array of numbers from 1 until the "db.collections.coinstats.last" number (the last blockindex that was synced). 
Then I use db.collections.txes.distinct("blockindex") to export of all of the blockindexes already known (probably the same way you exported them manually). 
Finally, I start a forloop on the original blocksArray to check if there's a related index in the txes. If yes, move on, if no, store it in a new array called Missing. Now I know the missing blocks.

So to answer, no there isn't any singular query in mongo to do a check on which numbers are missing. It's going to have to be a loop of some kind.
