### ISSUE TITLE
cronjobs not running

### ISSUE THREAD

**Issue by popupcoin** [iquidus/explorer#290]
my sync is stuck on block 1517 and my cronjobs do not appear to be running.

**Comment by uaktags** [comment]
Try running the script manually to see what it's doing and double check your crontab to ensure its formatted correctly to run.

**Comment by popupcoin** [comment]
Thank you are the reply, I rechecked the cron jobs and there was a syntax error on crontab -e so after a quick edit and reboot it is all syncing correctly.

thank you for the reply
