### ISSUE TITLE
Negative balances: Discrepancy between MongoDB values and Iquidus web server display

### ISSUE THREAD

**Issue by liamstojanovic** [iquidus/explorer#293]
I am having a puzzling error. [I am using Iquidus](http://abcblock.org/) to display the [ABCmint](http://abcmint.org/) cryptocurrency.

I noticed that [this address 8Rj5WDxT2VaM8HZpPv4uDtae9qLxPsQtLRGtTgUzZhJtpg1px](http://abcblock.org/address/8Rj5WDxT2VaM8HZpPv4uDtae9qLxPsQtLRGtTgUzZhJtpg1px) appears as negative. This is likely related to [the following issue](https://github.com/iquidus/explorer/issues/6); in essence, the address owner specifies themselves as a recipient, activity which can create negative balance amounts.

I decided to export the addresses collection from mongo, and was even more puzzled when I took a look at the balance, received, and sent values. [For whatever reason, the database values do not correlate with what the web interface claims.](https://imgur.com/a/jNAgJyI) The sent and received values match, but the balance does not.

Has anyone else experienced a similar issue?

**Comment by RottenCoin** [comment]
looks like you haven't started deamon with -txindex 
Only way is to reindex everything now.

**Comment by liamstojanovic** [comment]
> looks like you haven't started deamon with -txindex
> Only way is to reindex everything now.

This is how I started my cryptocurrency client initially, using all of the flags you specified. I guess it wouldn't hurt to try reindex and repopulate MongoDB.

**Comment by RottenCoin** [comment]
I made that mistake once starting bare deamon. Better to add txindex=1  to. conf file and no need to remember anymore. Yes reindex coin first and when is done do same with the explorer

**Comment by liamstojanovic** [comment]
> I made that mistake once starting bare deamon after vps reboot. Better to add txindex=1 to .conf file and no need to remember anymore. Yes reindex coin first and when is done do same with the explorer

Done. Still experiencing same problem. The explorer shows negative balance for certain addresses. One of them can be [found here](http://abcblock.org/address/8Rj5WDxT2VaM8HZpPv4uDtae9qLxPsQtLRGtTgUzZhJtpg1px)

**Comment by RottenCoin** [comment]
Do it again then. Delete blockchain folders from the wallet and reindex. Start  mongo and use new database.

**Comment by liamstojanovic** [comment]
> Do it again then. Delete blockchain folders from the wallet and reindex. Start mongo and use new database.

The problem still persists. Did this on both my live server, and a virtual machine on my laptop.

**Comment by uaktags** [comment]
I think what we're finding is inconsistent handlings of the vout txes. This was reported to me in my fork as the issue didn't occur in this original repo, however now I'm seeing youre getting it here too, so there may be some underlying issue with how the array of vouts are being collected and executed.

**Comment by TheHolyRoger** [comment]
This is fixed in https://github.com/iquidus/explorer/pull/319 but not merged yet, awaiting review

**Comment by TheHolyRoger** [comment]
Merged in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc
