### ISSUE TITLE
Labels do not appear in bottom navbar

### ISSUE THREAD

**Issue by liamstojanovic** [iquidus/explorer#294]
[If you take a look at my instance of Iquidus explorer](http://abcblock.org/), you will notice that,

- The "blocks" and "connections" label are floating on the page itself, not anchored to the bottom navigation bar,
- The labels I have specified in my settings.json file do not appear.

This behavior exhibits itself from a fresh install of the explorer. I did not edit any layout files prior to installing Iquidus, so I am not sure exactly why this is happening.

**Comment by uaktags** [comment]
Closing as the link doesn't exist. We also have Bootstrap4 in the process of coming out. I've yet to see this issue myself.
