### ISSUE TITLE
incorrect total send and total received in POS coin

### ISSUE THREAD

**Issue by ssdpool** [iquidus/explorer#3]
the sum of total send and total received in pos included every one pos stake generated.
for properly result need to fix  it:
example  
if pos address sender and address received is same .
then in total send will add nothing
in total receive will add pos results

**Comment by iquidus** [comment]
I've finally managed to replicate and diagnose this on my end, I had previously misunderstood the problem.

This is going to require quite a fix as those values currently come strait from the database (currently PoS adaptions happen client side). The database is storing the correct values from the blockchains perspective. However much of the sent & received is PoS generation (matching input & output addresses) this is why the values seem far too high from the users perspective, yet the balance is correct. 

Currently as a new tx is indexed the inputs and outputs are handled by separate functions. Making checking for PoS here slightly difficult without taking a noticeable performance hit to indexing. 

I am putting the fix to this issue off for a future update (1.4.1) so I can give it more thought. In the mean time as a work around I have added a new setting 'show_sent_received', set in settings.json, if set false the total sent and total received columns in the Address table will not show, leaving just the address balance.

This workaround has been pushed to the dev-1.4 branch.
commit: caec99da3a2c3b7b5cc6afd01316758d1d2b0c80

The dev-1.4 branch will be merged into master shortly, just have a few more tests to run.

**Comment by iquidus** [comment]
1.4.0 has been merged into master and is ready for use. I will be leaving this issue open as it has not been resolved properly. 

An actual fix will include a check within the save_tx() function (lib/database.js, line:123) so the addresses sent, received and balance can be updated correctly for PoS. As well as an additional setting in settings.json so this check only occurs if proof_of_stake is set true (as it is going to have to do some extra looping through vin/vout which will slow indexing).

**Comment by iquidus** [comment]
fixed in version 1.5.0

note: currently total received = received + staked. This will be addressed in a future update, where staked will be displayed separately.
