### ISSUE TITLE
diplay error

### ISSUE THREAD

**Issue by newmight2015** [iquidus/explorer#30]
I find the website couldn't display blocks and couldn't display the action "processing" after run the block explorer some days.
the same problem also :
http://explorer.gambitcrypto.com/
https://blockchain.vanillacoin.net/
http://explorer.infernopool.com/

**Comment by duoduosys** [comment]
the some question，
Latest Transactions in the main page diplay error，nothing to see

**Comment by MystPhysX** [comment]
Yep same here.

The recent blocks don't show when loaded but you can still search and find them if needed.

**Comment by yavuzc78** [comment]
me too have same issue

**Comment by naveen-appoets** [comment]
same issue

**Comment by uaktags** [comment]
Latest Transactions not showing, though searching works, tells me that the sync hasn't been occuring. Closing as this shouldn't be an issue, but if someone has a testable example, I'd be happy to look at it.
