### ISSUE TITLE
Add BitCanna to "See it in action"

### ISSUE THREAD

**Issue by stefanheijnen** [iquidus/explorer#300]
Hi Equidus,

First of all, thank you for this great explorer :+1: 

I have a request. Could you add please add [BitCanna](https://explorer.bitcanna.io) to the "see in action" list?

BitCanna is a decentralized payment network that is powered by the cannabis industry, not a central authority.

The Bitcanna Alliance is an initiative from leaders in the European cannabis industry. With their shared interest they are committed to providing the best solution to address the challenges that are currently holding back the cannabis industry. The ultimate goal is to open up the restrained business attitude of the current market in order to earn back trust from consumers, regulators and financial institutes.

I'm not affiliated with BitCanna, but I have their permission to get BitCanna listed.

![image](https://user-images.githubusercontent.com/1306331/64074720-60fc4780-ccaf-11e9-8a9c-c17afd9b5668.png)

**Comment by TheHolyRoger** [comment]
Can you link their fork of iquidus here?

**Comment by RaulBernal** [comment]
Hi! Forked BitCanna Explorer :  https://explorer.bitcanna.io
