### ISSUE TITLE
[request] Add Exchange-Assets Market

### ISSUE THREAD

**Issue by XVictus-project** [iquidus/explorer#308]
can you add exchange-assets to markets?
API --> https://exchange-assets.com/api/public/ticker/

**Comment by uaktags** [comment]
Unfortunately, exchange-assets doesn't provide a robust api. They have only 3 API calls.

**Comment by uaktags** [comment]
https://gist.github.com/uaktags/7c823194f68cba2dcf01b7d0238d8833

That should do the trick, but note it's not supported, and is just a rough draft. Should get you going though. Make sure you enable "exchange-assets" in your settings.market.

**Comment by TheHolyRoger** [comment]
Exchange markets are no longer hardcoded thanks to @uaktags - https://github.com/iquidus/explorer/commit/2be23e2f8f0e446943518303efef95ca964c59a9
