### ISSUE TITLE
Explorer not updating all transactions and in proper order

### ISSUE THREAD

**Issue by rhodium-tech** [iquidus/explorer#315]
I have started using Iquidus Explorer for my coin named RHYPTON - http://107.180.90.239:3001/
I can find that my explorer is running well but the issue is it is not catching all transactions and also not in proper order.
this a brand new project and hence there is not lots of transactions, so before i start publicly promoting can u please held and suggest me to sort out this issue,
Regards,
Rhodium Tech
![explorer](https://user-images.githubusercontent.com/58563842/70404733-f81c2c80-1a60-11ea-9586-f33cb320c4c4.png)

**Comment by rhodium-tech** [comment]
When i start npm i get the below error in the beginning but after that it start working after coming several times this same error.

Error: bind EADDRINUSE null:3001
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at listenOnMasterHandle (net.js:1427:16)
    at rr (internal/cluster/child.js:121:12)
    at Worker.send (internal/cluster/child.js:88:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event

**Comment by TheHolyRoger** [comment]
> When i start npm i get the below error in the beginning but after that it start working after coming several times this same error.
> 
> Error: bind EADDRINUSE null:3001
> at Object._errnoException (util.js:1022:11)
> at _exceptionWithHostPort (util.js:1044:20)
> at listenOnMasterHandle (net.js:1427:16)
> at rr (internal/cluster/child.js:121:12)
> at Worker.send (internal/cluster/child.js:88:7)
> at process.onInternalMessage (internal/cluster/utils.js:42:8)
> at emitTwo (events.js:131:20)
> at process.emit (events.js:214:7)
> at emit (internal/child_process.js:772:12)
> at _combinedTickCallback (internal/process/next_tick.js:141:11)
> at process._tickCallback (internal/process/next_tick.js:180:9)
> events.js:183
> throw er; // Unhandled 'error' event

This is a separate issue, and it is due to you having multiple explorer processes running.

`ps aux | grep node`

To find the dead explorer processes to kill

**Comment by TheHolyRoger** [comment]
> I have started using Iquidus Explorer for my coin named RHYPTON - http://107.180.90.239:3001/
> I can find that my explorer is running well but the issue is it is not catching all transactions and also not in proper order.
> this a brand new project and hence there is not lots of transactions, so before i start publicly promoting can u please held and suggest me to sort out this issue,
> Regards,
> Rhodium Tech
> ![explorer](https://user-images.githubusercontent.com/58563842/70404733-f81c2c80-1a60-11ea-9586-f33cb320c4c4.png)

This issue is fixed in https://github.com/iquidus/explorer/pull/319

**Comment by TheHolyRoger** [comment]
Merged in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc
