### ISSUE TITLE
Add SperoCoin to README.md

### ISSUE THREAD

**Issue by DigitalCoin1** [iquidus/explorer#328]
Please add SPERO's address to the active explorer listing:

https://explorer.sperocoin.org

Tks!

**Comment by TheHolyRoger** [comment]
Can you please link the source? Or are you using pure iquidus?

**Comment by DigitalCoin1** [comment]
https://github.com/DigitalCoin1/BlockExplorer

**Comment by TheHolyRoger** [comment]
@DigitalCoin1 I can see that you're pretty much up to date with https://github.com/iquidus/explorer/tree/1.6.2-stable

Please rebase your changes onto that branch (your peer fixes are redundant now, the only change you need is the logo and your settings.json)

Example: https://github.com/TheHolyRogerCoin/RogerXplorer/commits/digitalcoin

**Comment by TheHolyRoger** [comment]
Once you've rebased from iquidus master I'll add the link to the readme
