### ISSUE TITLE
Iquidus Explorer 2.0

### ISSUE THREAD

**Issue by iquidus** [iquidus/explorer#33]
An entire rewrite of the explorer is planned. It has been on my todo list for quite some time however keeps getting bumped down as other projects have taken priority (as the current explorer works). Due to recent developments I now have a lot more resources at my disposal and will be hiring some devs to help with various projects, including this one. I have created this issue for people to add any feature requests.

Planned changes.
1) Store tx, address and balance data more efficiently, resulting in much faster indexing times.
2) Separate front-end from backend/API. So one frontend can connect to many backends/API's (multicoin support)
3) Plugin framework
4) Move markets & richlist/wealth distribution functionality into plugins, outside of main codebase for easier maintenance and customizations.
5) Network plugin, displaying, charting and mapping various network information.
6) Decred support

Please add anything you would like as a response so I can keep it in mind when writing the core code.

**Comment by iquidus** [comment]
On the hunt for good nodejs & javascript devs, with experience with crypto currencies, a passion for blockchain technology, and motivation to change the world. Can work remotely, but even better if you are able to move to Sevilla, Spain (as office is here).

Happy to upskill those that don't quite have the expertise required. Many big projects on the horizon, no shortage of work, but a serious shortage of skilled devs.

**Comment by followtheart** [comment]
1) Store tx, address and balance data more efficiently, resulting in much faster indexing times. :+1: 

sync index update ....is tooooooo slow!

**Comment by Infernoman** [comment]
sending raw transactions.

**Comment by viest** [comment]
@followtheart  Sync index update ....is tooooooo slow! how do you solve it?

**Comment by Igor-san** [comment]
> Sync index update ....is tooooooo slow! how do you solve it?

Yes, I confirm this. Re-indexing more than 400,000 blocks has been going on for several days already.
