### ISSUE TITLE
IP Country names

### ISSUE THREAD

**Issue by BayerTM** [iquidus/explorer#332]
Hi Roger,

I have a question i don't see any country names in network area.
Version of my block explorer is 1.6.1 do you have any idea ?

![ice_screenshot_20191228-181347](https://user-images.githubusercontent.com/59299109/71547255-eeba1c00-299d-11ea-8863-5f1d9f780387.png)

Thank You

**Comment by TheHolyRoger** [comment]
Use 1.6.2.

https://github.com/iquidus/explorer/commit/bb153106ed9a446658e9d084ec6a1702c10e19d5

https://github.com/iquidus/explorer/tree/1.6.2-stable
