### ISSUE TITLE
Searching will only sometimes work

### ISSUE THREAD

**Issue by WillWammer** [iquidus/explorer#349]
http://blocks.mocha.network/

Entering in an address in the search box, if I entered the address MgLSgi9he2C661JfW3cQa2JrGwkYop9P8R

Instead of getting 

http://blocks.mocha.network/address/MgLSgi9he2C661JfW3cQa2JrGwkYop9P8R

I would get

http://blocks.mocha.network/tx/MgLSgi9he2C661JfW3cQa2JrGwkYop9P8R 

Same thing for TXs as well. Sometimes they register as addresses. Is there something I need to change in the config? Or is this a legitimate bug?

**Comment by uaktags** [comment]
I'm able to load ``http://blocks.mocha.network/address/MgLSgi9he2C661JfW3cQa2JrGwkYop9P8R`` just fine. searching for it as well works on my end. I also tested it with a bunch of different txes and addresses that I saw. 

Tested just typing in numbers ( returns the blocks at those heights)
Grabbed a number of different hashes from Latest TX and got a combo of NonStandard Transaction as well as normal txes that have addresses for the To/From.
Also did searches for specific addresses that I skimmed from searching around.

**Comment by WillWammer** [comment]
@uaktags Yup, thanks for that. It just started working again for some reason.... anyways, I'll close the issue.

**Comment by WillWammer** [comment]
Nope have to reopen this. It's now more consistent then ever. It will ALWAYS search for block default instead of TX or address. There is also this issue where I have NAN confirmations.

**Comment by uaktags** [comment]
I'm still not getting any issues. But either way, the search function is pretty straightforward:
https://github.com/iquidus/explorer/blob/56e37523263bd81d57dfc420416c1b0426b875a7/routes/index.js#L236-L271

I'd venture to guess we're either dealing with bad cache, or something is going wrong with the validation on the json returns that are coming from checking the string against address/tx/blocks

**Comment by WillWammer** [comment]
Ah ok. I'll give it another look
