### ISSUE TITLE
Incorrect maximum supply

### ISSUE THREAD

**Issue by BarneyChambers** [iquidus/explorer#352]
I am running a bitcoin fork with Iquidus explorer with almost identical codebase to Bitcoin. Its a pure PoW coin that doesn't do anything majorly different under the hood, aside from using HMQ1725 algorithm instead of SHA256.

For some reason my maximum supply is wrongly calculated, showing 13,000,000 instead of 105,000,000 which is displayed when I do the RPC command `gettxoutsetinfo`

What would cause iquidus explorer to display an incorrect max supply? I am currently using `COINBASE` to calculate max supply in settings.json

**Comment by uaktags** [comment]
Is the explorer fully synced?

Setting it to coinbase, it's doing a calculation based off of how much btc was created by coinbase at the time of the block sync. So if you only have sync'd up to 10k of say 100k blocks (1/10th the fully blockchain) then you'll only know the maximum supply at that point.

Alternatively, you could set it from COINBASE to TXOUTSET instead:
```
} else if (settings.supply == 'TXOUTSET') {
        client.command([{method:'gettxoutsetinfo', parameters: []}], function(err, response){
          if(err){console.log('Error: ', err); }
          else{
            if(response[0].name == 'RpcError'){
              return cb('There was an error. Check your console.');
            }
            return cb(response[0].total_amount);
          }
        });
```

**Comment by BarneyChambers** [comment]
I managed to solve the issue be running sync.js with the reindex flag. Not sure what was causing the bug but my blockchain was and is definitely synced up while the number was incorrect.

**Comment by uaktags** [comment]
Id say it's a good idea to close since we can't test this anymore, everything mentioned is still true regarding the difference between txoutset vs coinbase. 

Just for clarification though, when we say BlockChain is fully syncd, we mean that the explorer is fully syncd with your coind, rather than questioning whether your coind's BlockChain is fully syncd with the coins network.
