### ISSUE TITLE
Rich List is not working

### ISSUE THREAD

**Issue by mmitech** [iquidus/explorer#36]
The Rich List is not working, I've tried reindexing a couple of times, dropping the whole database, spawning a new server and nothing helps.
The error I get when looking at the dev-console is "Uncaught ReferenceError: pieWealthDist is not defined".

**Comment by legends420** [comment]
anyone get this to work im having the same problem

**Comment by isLishude** [comment]
Because of scope error,I Will PR for this.

**Comment by isLishude** [comment]
see the #155 PR

**Comment by leegod** [comment]
What is rich list? And market does not work even after json settings market:true?
