### ISSUE TITLE
Big Perfomance problems (Ajax error), How Sync only after genesis block?

### ISSUE THREAD

**Issue by bitcoin5000** [iquidus/explorer#365]
I have big performance problem on bitcoin fork (Ajax error everywhere), i have vps with 2 cores and 4gb ram, its possible to sync explorer only with blocks after fork to gain performance? I put fork block in genessis block settings but seems its start syncing from block 1. Any help?
  "genesis_tx": "getblock of getblockhash here? ",
  "genesis_block": "getblockhash of first forkblock here?",

**Comment by uaktags** [comment]
While you CAN make it sync at a later point, you will not get the intended outcome you're looking for. Starting a sync later will mean you miss all the info that came before. Not sure what kind of fork you're using where you start later in an existing block chain, but completely ignore all of its blocks.


For this reason, please note, I personally won't be providing support for this, nor would I suspect others as I can see likely issues come up with transactions, counts, etc.

To do what you're looking for, update the "last" entry in your mongo database. It's under coin_stats. Last tells the sync tool what the last successful block was, so you'd enter the block height of Genesis.
