### ISSUE TITLE
reindex complete (block:0)

### ISSUE THREAD

**Issue by fancywarlock** [iquidus/explorer#366]
I literally tried to fix this all day, but need help.

My recent transactions screen is blank, so I followed the documentation:

1.  removed index.pid (sudo rm -f tmp/index.pid)
2.  npm start 
3.  node scripts/sync.js index reindex
4.  here's what I get:

script launched with pid: 30079
index cleared (reindex)
reindex complete (block:0)

In all of the tutorials I've seen, the "reindex complete" should be followed by (block:1).  

I have no idea why it is returning (block:0) instead of (block:1).  No matter what, I am not getting the transactions populated.  

You can see the proper execution on this youtube video, however mine does not return the block:

https://youtu.be/laeV2slJgc8?t=1163

it's also worth noting that my API calls are working fine, but my extended API is not working properly.  So perhaps it's some sort of communication issue?

http://134.122.107.224:3001/info

Really appreciate some help here.  Thanks!

**Comment by fancywarlock** [comment]
I upgraded node.js to 12.x and it didn't help.  now getting ECONNREFUSED

**Comment by fancywarlock** [comment]
Deleted the droplet.  Will try again tomorrow.  Could you please recommend specific versions of Mongo and Nodejs that you are certain are compatible with one another and work for this use case?  Thanks!

**Comment by uaktags** [comment]
ECONNREFUSED has never been a Mongo/NodeJS communication issue, but almost always an issue with communicating with the coind.

I'd be weary of using a 2 yr old video for proper execution. The proper execution is in the readme.md (running reindex shouldn't just stop at the first block after genesis, requiring an 'update'. That'd be just silly).

The Node/Mongo version in the readme is one that I'm "certain are compatible".

```
index cleared (reindex)
reindex complete (block:0)
```
this tells me that it's having a comm issue with your coin daemon or has an issue with the current count, not with mongo. It made it past the mongo connection.

https://github.com/iquidus/explorer/blob/56e37523263bd81d57dfc420416c1b0426b875a7/scripts/sync.js#L162

If you weren't getting the CONNREFUSED issue, I'd say that may be an issue, but the CONNREFUSED is communications with your daemon.
