### ISSUE TITLE
explorer Not Show diff

### ISSUE THREAD

**Issue by mraksoll4** [iquidus/explorer#370]
i try settings POW POS Hybrid notting no change it not show diff
coin bassed at v0.18.1 bitcoin sources algo POW

https://explorer.ltfnd.info/

https://github.com/litecoinfinance/litecoinfinance

+ for some reason work only 1.7.2 ver of explorer , ver 1.7.3 not working ( it not make sync update , only reindex command work )

**Comment by mraksoll4** [comment]
find fix for diff
https://github.com/iquidus/explorer/pull/363/commits/ca2034382e457849c6ad70556ca9d71d610a2668

**Comment by mraksoll4** [comment]
but why not sync ver 1.7.3 not find any solution .

**Comment by mraksoll4** [comment]
to for some reason not work https://explorer.ltfnd.info/richlist

maybe when it be full synced it start work ?

**Comment by uaktags** [comment]
Correct, richlist happens after update_tx_db

```
 db.update_tx_db(settings.coin, 1, stats.count, settings.update_timeout, function(){
                            db.update_richlist('received', function(){
```

**Comment by TheHolyRoger** [comment]
Diff fixed: https://github.com/iquidus/explorer/commit/b7180dc9224adcda0c75845e77aab0bfc8734347
