### ISSUE TITLE
Difficulty not showing

### ISSUE THREAD

**Issue by rhodium-tech** [iquidus/explorer#372]
http://rhypton.com:3001
Coin Algorithm - X11
POW
But difficulty not showing after updating to new version of explorer 1.7.3
Pls help
Regards,
![explorer](https://user-images.githubusercontent.com/58563842/80267993-b1eb0100-86c1-11ea-94d4-432650808efc.png)

**Comment by BayerTM** [comment]
Hi Rhodium-tech,

Did you check your settings.json file for correct settings? 
Like pow pos ? 

And i think what it is your difficulty count is lower then 2 decimals thats why its not showing up on the main page. Check you API console and click on the link get difficulty and you will see its working and its lower then 2 decimals !!

Regards, Bayer

**Comment by rhodium-tech** [comment]
Thanks for your response. I checked my json settings. Its perfect as POW.
I hope you r right as my difficulty is less than 2 decimal thats why not reflecting.
Thanks for ur suggestion.
