### ISSUE TITLE
[request] Add "Fides-ex" exchange

### ISSUE THREAD

**Issue by MadCatMining** [iquidus/explorer#383]
Could a Fides-ex exchange be added to Market list?
Tried applying changes to Poloniex as example as it seems to use simmilar calls but had bad luck with that.

Main page: https://www.fides-ex.com/
Api documentation: https://www.fides-ex.com/exchange-documentation

**Comment by uaktags** [comment]
What issues were you having when creating your own?

Right out the gate I see that it uses HMAC which is a PITA in my opinion. Off the cuff, I'd say https://github.com/uaktags/iquidus-explorer-exchanges/blob/master/graviex/graviex.js would be your best bet as a starting point as graviex uses HMAC so you can see how that gets formatted.

**Comment by MadCatMining** [comment]
The only issue, tbh, is that i do not know any programming language. So for me is the only option is to take examples and see if it works with minor changes, that i can understand.

Thanks for the tip. I'll will have look at graviex.

**Comment by uaktags** [comment]
Understood, I took a look and while they say HMAC is needed, none of the needed apis seem to require it. However, it does take a bit of understanding to make the translations between Fides' endpoints and any other exchange used as ref.

I haven't looked at the .pug file for the template, and honestly, I probably wont as I'm really just looking at this on a lunch break, but hopefully this can get you going.

https://gist.github.com/uaktags/3ead23e2141d1163cdd1262e962c578f

**Comment by MadCatMining** [comment]
Great! 
I'll see where it take's me and carry on from there. 
Thank you for your help @uaktags!

**Comment by uaktags** [comment]
No problem, just take a look at the buys and sells, and make sure that the data matches with the json values:

```
{
      MarketType: 'BTC',
      CurrencyType: 'ETH',
      Type: 'SELL',
      Pair: 'BTC_ETH',
      Rate: 1.88888888,
      Volume: 0.00028452,
      Total: 0.0005374266641376001
    }
```

whereas in https://github.com/uaktags/iquidus-explorer-exchanges/blob/8efd3030a9d3d0c9c4f0c049355d231659c57210/graviex/graviex.pug#L59-L66 you'll see they use "price" instead of "Rate", "amount" instead of "Volume", etc. I could have changed these names in the fidesex.js but chose to keep the keys with the same name as the api

**Comment by MadCatMining** [comment]
Well what do you know - only "Trades" table left unsolved yet. The rest is already reflected at "Markets" page. Up to now used Tradesatoshi.pug/Graviex.pug mix.

**Comment by MadCatMining** [comment]
Alright then - job done. A little bit of graviex.js/tradesatoshi.js/poloniex.js and same for the .pug part.
@uaktags if you want me to pass somewhere my masterpiece - let me know.

**Comment by uaktags** [comment]
I'd you don't mind, do a pull request on either iquidus or on my repo for
exchanges so that others can grab at it.

Glad to hear you nailed it!

**Comment by MadCatMining** [comment]
Fides-ex Market implementation completed. Pull request made.
Closing issue.

Thanks for assistance @uaktags!
