### ISSUE TITLE
Issue with node 14

### ISSUE THREAD

**Issue by prinze77** [iquidus/explorer#388]
Not start with node 14 
<img width="1096" alt="Снимок экрана 2020-06-22 в 8 16 22 PM" src="https://user-images.githubusercontent.com/33203521/85316384-58d2fa00-b4c5-11ea-9730-8a9530efd108.png">

**Comment by GOSSIP-Blockchain** [comment]
use node v12x

**Comment by prinze77** [comment]
> use node v12x

Thanks cap
