### ISSUE TITLE
ext/getaddress api with array of last txs

### ISSUE THREAD

**Issue by GamSui** [iquidus/explorer#392]
In some installations I can see that the ".../ext/getaddress" api returns a list of last txs. I'm using quite an old version 1.6.1. In my installation I only get address, sent, received and balance. I don't get the last txs array. Is this a restriction of my current version, or can I active this feature? If yes how?

**Comment by TheHolyRoger** [comment]
Where have you seen that? This isn't currently in the original fork.

If you can link it we will replicate it.

**Comment by uaktags** [comment]
It may have been part of the change from
Address.findOne() to AddressTx.findOne()
Briefly looked at the last push that iquidus made to database.js and noticed the difference in our models for the find_address. 

So before, only responded with the address dcoument rather than the AddressTX document

**Comment by TheHolyRoger** [comment]
Ahhh, right got you. I remember stripping that out thinking it was redundant. I think that still existed in 1.6.1 though which is odd... Will look into bringing this back

**Comment by GamSui** [comment]
Thanks for your replies.

I have seen it on the following live explorer sites (all powered by Iquidus Explorer). So I assumed if this can be found on several instances it cannot be a custom implementation).

http://explorer.omegablockchain.net/ext/getaddress/oSVLhptBjB7jv8F4nuwfDBYoaRhmRQug3g
https://explorer.maxcoinproject.net/ext/getaddress/mVameADsUKcSeFUv47bShXzc424KVoEtUq
http://altmco.in/ext/getaddress/Aburni676T6PWnPUiM8Knb3W3Eyt6t7LFt
http://gcpool.eu:3590/ext/getaddress/NNBCACPrrDQZA4C6Gi8pYZe5VRVoNao6GE

Would be great if you can bring it back. Thanks a lot!

**Comment by FrediDealCash** [comment]
I have just opened the following issue: https://github.com/iquidus/explorer/issues/408

I am running the latest v of the explorer and also need the above functionality to get the last txs for a specific address

**Comment by TheHolyRoger** [comment]
I'll take a look at this later we don't need to change much to get this back in

**Comment by FrediDealCash** [comment]
> I'll take a look at this later we don't need to change much to get this back in

Amazing - that would be great. Thanks!

**Comment by TheHolyRoger** [comment]
@FrediDealCash @GamSui Please try out this PR:

https://github.com/iquidus/explorer/pull/410

**Comment by FrediDealCash** [comment]
> @FrediDealCash @GamSui Please try out this PR:
> 
> #410

Just tried it and have left my comment on the PR: https://github.com/iquidus/explorer/pull/410#pullrequestreview-478457394

All works perfectly, thank you very much for taking the time to do this.
