### ISSUE TITLE
Web Linking by block height

### ISSUE THREAD

**Issue by RaulBernal** [iquidus/explorer#396]
Hi,  you plan to implement a web linking by block height? 

Example: 

- height (/height/block_height)

127.0.0.1:3002/height/11111

**Comment by uaktags** [comment]
We do have the api "/api/getblockhash?index=" but as for your request for producing the block view by height, we currently don't track by blocks at anypoint, so we'd need to do an API call to translate blockheight into blockhash, and then produce the normal block call on that hash. Shouldn't be much work other than to expand on
https://github.com/iquidus/explorer/blob/897d6b952a25dc120312a1072bd69f0af83d939f/routes/index.js#L9-L35

I'll keep this issue open to track it and see where we may want to add this to

**Comment by TheHolyRoger** [comment]
Here you go, added to master, easy one I looked at before :D https://github.com/iquidus/explorer/commit/73580382f5371cdb5bbbe46da42bd0d50df7e355
