### ISSUE TITLE
api ext/getaddress/ kills client if address not seen on network

### ISSUE THREAD

**Issue by xPooky** [iquidus/explorer#4]
When i try to use the api to get address that is not yet seen on the network, the client stops running with error

/root/explorer/app.js:62
      address: address.a_id,
                      ^
TypeError: Cannot read property 'a_id' of undefined
    at /root/explorer/app.js:62:23
    at /root/explorer/lib/database.js:465:14
    at Promise.<anonymous> (/root/explorer/lib/database.js:63:14)
    at Promise.<anonymous> (/root/explorer/node_modules/mongoose/node_modules/mp
romise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/root/explorer/node_modules/mongoose/node_modules/mpromise/
lib/promise.js:84:38)
    at Promise.fulfill (/root/explorer/node_modules/mongoose/node_modules/mpromi
se/lib/promise.js:97:20)
    at Object.cb (/root/explorer/node_modules/mongoose/lib/query.js:1145:30)
    at Object._onImmediate (/root/explorer/node_modules/mongoose/node_modules/mq
uery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

npm ERR! explorer@1.3.4 start: `node --stack-size=10000 ./bin/www`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the explorer@1.3.4 start script.
npm ERR! This is most likely a problem with the explorer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --stack-size=10000 ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls explorer
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /root/explorer
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/explorer/npm-debug.log
npm ERR! not ok code 0

**Comment by iquidus** [comment]
Thanks for reporting this. My apologies about the slow response. A fix has been pushed to the master branch. git pull to grab it. 

the api will now respond with 

{"error":"address not found.","hash":"GZT7M1rwV1rqTsX3ghLa4K7bAeMWNhpDcz"}

note, a successful call will not contain an 'error' key. 

I've also pushed the fix to the dev-1.4 branch which is nearing a release state and contains many stability fixes (cluster support etc) but use with caution for now as it is not quite ready.

**Comment by xPooky** [comment]
Thank you, works great now
