### ISSUE TITLE
Implement Coinexchange.io in Markets

### ISSUE THREAD

**Issue by marcianovc** [iquidus/explorer#40]
how to implement the exchange coinexchange.io in iquidus?

**Comment by uaktags** [comment]
You'll have to create a new JS library in lib/markets for it. I've attempted but am not finished thus far.

``var request = require('request');

var base_url = 'https://www.coinexchange.io/api/v1';

function get_summary(coin, exchange, coinexchange_id, cb) {
  var req_url = base_url + '/getmarketsummary?market_id=' + coinexchange_id;
  request({uri: req_url, json: true}, function (error, response, body) {
    if (error) {
      return cb(error, null);
    } else {
      /*if (body.message) {
        return cb(body.message, null)
      } else {*/
		var summary = body.result;
		console.log(summary);
		summary['bid'] = body.Data['BidPrice'].toFixed(8);
		summary['ask'] = body.Data['AskPrice'].toFixed(8);
		summary['volume'] = body.Data['Volume'];
		summary['high'] = body.Data['HighPrice'].toFixed(8);
		summary['low'] = body.Data['LowPrice'].toFixed(8);
		summary['last'] = body.Data['LastPrice'].toFixed(8);
		summary['change'] = body.Data['Change'];
        return cb (null, body.result[0]);
      //}
    }
  });
}

function get_trades(coin, exchange,coinexchange_id, cb) {
  /*var req_url = base_url + '/getmarkethistory?market_id=' + coinexchange_id + '&count=50';
  request({uri: req_url, json: true}, function (error, response, body) {
    if (body.success == true) {
      return cb (null, body.result);
    } else {
      return cb(body.message, null);
    }
  });*/
  return 0;
}

function get_orders(coin, exchange,coinexchange_id, cb) {
  var req_url = base_url + '/getorderbook?market_id='+ coinexchange_id;
  request({uri: req_url, json: true}, function (error, response, body) {
    if (body.success == true) {
      var orders = body.result;
      var buys = [];
      var sells = [];
      if (orders['BuyOrders'].length > 0){
          for (var i = 0; i < orders['BuyOrders'].length; i++) {
            var order = {
              amount: parseFloat(orders.BuyOrders[i].Quantity).toFixed(8),
              price: parseFloat(orders.BuyOrders[i].Price).toFixed(8),
              //  total: parseFloat(orders.buy[i].Total).toFixed(8)
              // Necessary because API will return 0.00 for small volume transactions
              total: (parseFloat(orders.BuyOrders[i].Quantity).toFixed(8) * parseFloat(orders.BuyOrders[i].Price)).toFixed(8)
            }
            buys.push(order);
          }
      }
      if (orders['SellOrders'].length > 0) {
        for (var x = 0; x < orders['SellOrders'].length; x++) {
            var order = {
                amount: parseFloat(orders.SellOrders[x].Quantity).toFixed(8),
                price: parseFloat(orders.SellOrders[x].Price).toFixed(8),
                //    total: parseFloat(orders.sell[x].Total).toFixed(8)
                // Necessary because API will return 0.00 for small volume transactions
                total: (parseFloat(orders.SellOrders[x].Quantity).toFixed(8) * parseFloat(orders.SellOrders[x].Price)).toFixed(8)
            }
            sells.push(order);
        }
      }
      return cb(null, buys, sells);
    } else {
      return cb(body.message, [], []);
    }
  });
}

module.exports = {
  get_data: function(coin, exchange, cb) {
    var error = null;
	console.log('get data');
    get_orders(coin, exchange, function(err, buys, sells) {
      if (err) { error = err; }
		console.error(error);
		get_summary(coin, exchange, function(err, stats) {
          if (err) { error = err; }
          return cb(error, {buys: buys, sells: sells, chartdata: [], trades: trades, stats: stats});
        });
    });
  }
};
``
