### ISSUE TITLE
Add SouthXchange

### ISSUE THREAD

**Issue by gnark-mining** [iquidus/explorer#401]
How to add SouthXchange?  Tried but failed many times i don'T find how to for this one..

Thank you!   

API: https://www.southxchange.com/Home/Api

**Comment by uaktags** [comment]
Can you show what work you've tried to do? It's not as simple for us to just "add XYZ exchange", especially if we don't use it. 
Show us your work, show what "failed" and then when you get it working, submit a PR for us to add it.

**Comment by gnark-mining** [comment]
> 
> 
> Can you show what work you've tried to do? It's not as simple for us to just "add XYZ exchange", especially if we don't use it.
> Show us your work, show what "failed" and then when you get it working, submit a PR for us to add it.

https://github.com/gnark-mining/explorer-southxchange-files/commit/97a6dc79f28a91475939bc524cc26216b0fbf559

**Comment by uaktags** [comment]
It doesn't look like you even tried updating with the API of that exchange. Looks like a Copy/Paste job

https://www.southxchange.com/Home/Api

**Comment by uaktags** [comment]
For example:
Get_Summary in your copied market.js file is looking for the following:
```
 summary['bid'] = parseFloat(body['ticker']['buy']).toFixed(8);
        summary['ask'] = parseFloat(body['ticker']['sell']).toFixed(8);
        summary['volume'] = parseFloat(body['ticker']['vol']).toFixed(8);
        summary['volume_btc'] = parseFloat(body['ticker']['quote_volume']).toFixed(8);
        summary['high'] = parseFloat(body['ticker']['high']).toFixed(8);
        summary['low'] = parseFloat(body['ticker']['low']).toFixed(8);
        summary['last'] = parseFloat(body['ticker']['last']).toFixed(8);
        summary['change'] = 0;
```
So if we wanted ETH/BTC market, we'd get the price:
https://www.southxchange.com/api/price/ETH/BTC
which returns
```
{"Bid":0.036000051,"Ask":0.037550920,"Last":0.037550940000000000,"Variation24Hr":4.06,"Volume24Hr":7.765770540000000000}
```
Obviously high/low/change and variation/volume24hr don't match in either. So with the data you did return, you can remove the high/low and add in the variation, but you'll have to modify the template for it too. 

This is why ``It's not as simple for us to just "add XYZ exchange", especially if we don't use it.`` Can't always just copy/paste it, we need to code around the differences in exchanges and modify accordingly.

**Comment by gnark-mining** [comment]
I know that's why i asked for help lol. I know that i only copy pasted and for the rest i didnt understand it at all.

**Comment by gnark-mining** [comment]
Well, i finally found out how, closing this

**Comment by FrediDealCash** [comment]
@Original-Tasty can you share what you did? Thanks

**Comment by Original-Tasty** [comment]
> 
> 
> @Original-Tasty can you share what you did? Thanks

Regarding @uaktags, there is no such things here about sharing informations, "It's not as simple for us to just "add XYZ exchange", especially if we don't use it." So no, sorry, you have to do it yourself, good luck

**Comment by ShllFT** [comment]
Hu

**Comment by TheHolyRoger** [comment]
Original-Tasty wrote this before he deleted it. So doesn't look like he's willing to help I'm afraid.

> Regarding uaktags, there is no such things here about sharing informations, "It's not as simple for us to just "add XYZ exchange", especially if we don't use it." So no, sorry, you have to do it yourself, good luck

Not sure why he expects us to take on the work of adding everything he requests and then gets sour.... No one is paying anyone to maintain this repo but we try to help as much as we can.

**Comment by FrediDealCash** [comment]
> Original-Tasty wrote this before he deleted it. So doesn't look like he's willing to help I'm afraid.
> 
> > Regarding uaktags, there is no such things here about sharing informations, "It's not as simple for us to just "add XYZ exchange", especially if we don't use it." So no, sorry, you have to do it yourself, good luck
> 
> Not sure why he expects us to take on the work of adding everything he requests and then gets sour.... No one is paying anyone to maintain this repo but we try to help as much as we can.

Unfortunate as you have said but thanks @TheHolyRoger & @uaktags for supporting this project (and us)

**Comment by uaktags** [comment]
Haha he even changed his name, deleted his entire repos, and added a "stop stalking me" repo.... Then changed the name of this issue. 😂 Someone's a sour patch kid.

**Comment by Original-Tasty** [comment]
HAha you thought it was because of you? C'mon lol hahaha
