### ISSUE TITLE
No pos transactions

### ISSUE THREAD

**Issue by bhok** [iquidus/explorer#41]
Hi i have configured Iquidus at http://185.115.243.223/, all working fine except POS transactions does not appears: for example http://185.115.243.223/block/c3905c1862bcc5f80ff98c6b099ca9832111aa663c8d3e2a7d3d087200848d61, it appears to be a 0 transaction, and dont show the pos reward, but if i go inside the transaction: http://185.115.243.223/api/getrawtransaction?txid=1f31b2e6236c9cc0505a57c0b9894268593d0cda20c9604d60f6ac0145a04163&decrypt=1 i can see the pos reward correctly "value": 23.75,  "value": 23.76040212, it is an hybrid pow/pos coin called Revenu, setting json is=
// index page (valid options for difficulty are POW or POS)
  "index": {
    "show_hashrate": true,
    "difficulty": "Hybrid",
    "last_txs": 100
  },
  
  // ensure links on API page are valid
  "api": {
    "blockindex": 1013,
    "blockhash": "4339c14669fe166cc6d4849943d40155028c447b0a99728e8c604129164fd748",
    "txhash": "8877a48137024b02edcc73869b52edc052d064394d6629b5f6030a069d0133b9",
    "address": "RrdNpxRcbVxB9PzaujQd3rRzvj5SnQCmgy"
  },
  
  // market settings
  //supported markets: bittrex, poloniex, yobit, empoex, cryptsy, bleutrade
  //default market is loaded by default and determines last price in header
  "markets": {
    "coin": "rev",
    "exchange": "btc",
    "enabled": ["ccex"],
	"ccex_key" : "F58C3CB8C271C4BEBE582DF0EFD3" ,
    "default": "ccex"
  },

  // richlist/top100 settings
  "richlist": {
    "distribution": true,
    "received": true,
    "balance": true
  },

  // twitter
  "twitter": "iquidus",

  //genesis
  "genesis_tx": "00000ebc988a29ebf02daceaf8535b0da4ff06de6de68c50daa75a9c38faeba6",
  "genesis_block": "6ab37d41be7b74b331b5b411cc709d90c7e44c91fddc3fe6325309b4cd74372e",  

  //heavy (enable/disable additional heavy features)
  "heavy": false,

  //amount of txs to index per address (stores latest n txs)
  "txcount": 100,

  //show total sent & received on address page (set false if PoS)
  "show_sent_received": false,
  
  // how to calculate current coin supply
  // COINBASE : total sent from coinbase (PoW)
  // GETINFO : retreive from getinfo api call (PoS)
  // HEAVY: retreive from heavys getsupply api call
  // BALANCES : total of all address balances
  "supply": "GETINFO",

  // how to acquire network hashrate
  // getnetworkhashps: uses getnetworkhashps api call, returns in GH/s
  // netmhashps: uses getmininginfo.netmhashpsm returns in MH/s
  "nethash": "netmhashps",
  
  // nethash unitd: sets nethash API return units
  // valid options: "P" (PH/s), "T" (TH/s), "G" (GH/s), "M" (MH/s), "K" (KH/s)
  "nethash_units": "M",

Thank you in advance

**Comment by iquidus** [comment]
this is normal PoS behavior. a PoS transaction is actually 2 transactions, one with 0 recipients, this includes script defining it as PoS, the second contains the proof of stake reward.
