### ISSUE TITLE
Not Loading in Browser

### ISSUE THREAD

**Issue by justthedoctor** [iquidus/explorer#412]
So i have a new copy running, Using git clone from this repo as of early today, it is running and it is syncing from the daemon however when i try to load the website it wont load in my browser.. any idea's?

  "address": "45.33.89.66:3001",
  "port" : 3001,

**Comment by uaktags** [comment]
Anything showing in the console?

**Comment by justthedoctor** [comment]
When i first npm start i dont see anything in the console, however when i node scripts/sync.js index update i see movement in the console as well..

**Comment by justthedoctor** [comment]
My apology it was my firewall blocking the port ;| fixed the issue wasnt the project.
