### ISSUE TITLE
Looking for coins to test with

### ISSUE THREAD

**Issue by uaktags** [iquidus/explorer#420]
Hey guys,

To test some functionality, I'd like some small coins to test with. I'm looking for Masternode coins, PoS coins, and regular coins. I'd love for them to be small and have a bootstrap available to speed things up. The goal will be to have them running so i can test Coin specific functionality, test masternode capabilities, etc. The more unique, the better too.

**Comment by uaktags** [comment]
Currently testing with bitgreen. Their chain appears to be relatively small in size (a few gigs) and they have a working iquidius explorer which I can use as reference for later from a users standpoint.

**Comment by 2a5A1Ghu1** [comment]
I can help you with some ohmcoin, I am one of the lead devs, as well. if you would like hit me up on discord https://discord.gg/5KgQDku 

We have many explorers running in various stages of mods as well, including a few with unnamed exchange api working so we can get price info

**Comment by uaktags** [comment]
Thanks @2a5A1Ghu1, I've joined and will reach out once I get through a few more things.

**Comment by B1ackt34** [comment]
Do you still need some coin to test on?

Bitcoin Adult is available :)

**Comment by uaktags** [comment]
``to be small and have a bootstrap available to speed things up``
Over a million blocks, no thanks!

**Comment by 2a5A1Ghu1** [comment]
> `to be small and have a bootstrap available to speed things up`
> Over a million blocks, no thanks!

Hope you aren't talking about ohmcoin we have a bootstrap/snapshot LOL
Only asking because we have over a million blocks

**Comment by uaktags** [comment]
Haha, nah, I actually have ohmcoin setup and good. Funnily, I had a docker of ohm running this whole time since like a year or so ago when I held some. I was referring to the BitcoinAdult drop.

Right now, i'm really looking for a coin that is going to be really different. Something that would typically need a fork and custom code (so that i can focus more on the coin modularity).

**Comment by 2a5A1Ghu1** [comment]
> Haha, nah, I actually have ohmcoin setup and good. Funnily, I had a docker of ohm running this whole time since like a year or so ago when I held some. I was referring to the BitcoinAdult drop.
> 
> Right now, i'm really looking for a coin that is going to be really different. Something that would typically need a fork and custom code (so that i can focus more on the coin modularity).

Well since it's been a year, make sure you have updated we had a hard fork just recently. We are currently working on getting up to date on pivx's code and then we will be pushing out new could for the decentralized crowdfunding platform. Hopefully by that time it will fill your needs for unique.

**Comment by B1ackt34** [comment]
Probably we will fork BTAD in a bunch of month ... i will tell you when :)

**Comment by michelvankessel** [comment]
If you want, you can test on the Blackcoin testnet. Just join our Discord and ping me on the #testnet channel. https://discord.gg/hjNUgWD

**Comment by deltatoken** [comment]
hi - how about some selacoins? there is a block explorer already as well using this on http://162.243.161.203/

**Comment by uaktags** [comment]
Thanks guys, think i have enough here.
