### ISSUE TITLE
rpc error

### ISSUE THREAD

**Issue by karpyshynroman** [iquidus/explorer#427]
On tab `API` in route `/api/getconnectioncount` i have an error 
`{"message":"Node context not found","code":-32603,"name":"RpcError"}`

But in route `/api/getdifficulty` everything works.

I start my node with this flags
`/Applications/BitcoinABC-Qt.app/Contents/MacOS/BitcoinABC-Qt -regtest -server -txindex -daemon -rpcuser=user -rpcpassword=password -rpcport=8332`

Have this config inside iquidus

```
"use_rpc": true,

  "wallet": {
    "host": "127.0.0.1",
    "port": 8332,
    "username": "user",
    "password": "password"
  },
```

From curl everything works in my node too
`curl --user user --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "sendtoaddress", "params": ["qznwwyklq6kj2wh0m0xv3drrrkwwxrxv0v53uxdmeq", 0.1, "donation", "seans outpost"] }' -H 'content-type: text/plain;' http://127.0.0.1:8332 `

How to fix it?

**Comment by uaktags** [comment]
That means its not a iquidus issue, but a client issue.

https://github.com/Bitcoin-ABC/bitcoin-abc/issues/410

We're simply sending "getconnectioncount" method to the wallet, bitcoinabc is responding back with the node context. So the issue is there, not here.
