### ISSUE TITLE
Wrong timestamp on index page

### ISSUE THREAD

**Issue by Ruxiol** [iquidus/explorer#438]
Hey guys, where can i setup time, its showed wrong.

My system time is ok, but on explorer page time of transactions is late 2h, possible timezone?

**Comment by joeuhren** [comment]
Which coin? And have you tried comparing one of the bad timestamps from the index page to the actual timestamp recorded on the blockchain for that block or transaction? Something like `coin-cli getblock 0000012314f5cf2013f0820cebb718103a83e54d9a80a66244c59f4a92794814` and look for a "time" or "timestamp" value and then you can use a tool like https://www.unixtimestamp.com/index.php to convert the timestamp to a human-readable date and see if it shows a different date/time than the index page.

From a quick glance at a sample explorer I have running here, the timestamps on the index page perfectly match up to blockchain values so I'm wondering if in your case the timestamps are being written to the blockchain 2h behind and therefore are showing up the same in iquidus?

**Comment by Ruxiol** [comment]
Blockchain timestamps are ok, they are shown with correct time! 

But only on explorer its showed as 1hour before 

Thanks for helping me figure out what could be the cause

**Comment by joeuhren** [comment]
I haven't spent enough time looking at this problem yet, so maybe someone else will chime in with a better answer, but I have noticed some date issues in iquidus before, and most likely the issue you are experiencing is part of that problem. Basically what I think needs to happen is the dates all need to be run through some kind of date library such as moment.js to make sure they are normalized properly and are all displayed with the correct timestamp and date format, but I'm just guessing right now. I'll see if I can find some time to look into it soon as it would be nice to display the correct date/time

**Comment by TheHolyRoger** [comment]
Also worth checking your server timezone if it's only off by an hour - i've seen issues with timestamps being second/millisecond format but then your times would be way off, not just an hour

**Comment by uaktags** [comment]
Closing, haven't heard anything further on this in some time. There's not really any info for us to diagnose or reproduce the problem.
