### ISSUE TITLE
How to run iquidus in the background 

### ISSUE THREAD

**Issue by Dollar-coin** [iquidus/explorer#441]
Hi,
I was trying to run iquidus in the background using (npm start run&) or npm start & however once in a while it will stop working if my terminal is idle for a certain amount of time.

What is the correct way to run it in a process.

**Comment by grigzy28** [comment]
I personally use the DTACH program to run the npm program in.

**Comment by joeuhren** [comment]
Interesting suggestion about the DRACH program - I had not heard of that one. I think the more popular method of running iquidus in the background is via the forever module, which will even restart the explorer automatically if it crashes: https://www.npmjs.com/package/forever

first install using:

```
sudo npm install forever -g
```

then run the explorer in the background:

```
cd /path/to/explorer
forever start bin/cluster
```

you can stop the explorer by running:

```
cd /path/to/explorer
forever stop bin/cluster
```

**Comment by AO-GP** [comment]
Thanks for the tip! Getting an error when installing forever -g

Is there a workaround?

**Comment by uaktags** [comment]
Closing, no further responses.
