### ISSUE TITLE
Adding new Exchange?

### ISSUE THREAD

**Issue by Ruxiol** [iquidus/explorer#450]
Hello, our project is using this explorer and we all love it, but how can we add new exchange?

In our case its WhiteBit exchange that our crypto is listed.

https://github.com/whitebit-exchange/api-docs

**Comment by joeuhren** [comment]
There's 100's of exchanges out there and WhiteBit isn't supported yet. To add it yourself you will need to do the following:

- Make a copy of one of the existing exchange definitions from `lib/markets` and configure it to work with the equivalent WhiteBit apis
- Make a copy of one of the existing pug files from `views/markets` and configure it to work with the variables from the definition file you created above
- You can add the exchange name into both the `locale/en.json` and `lib/locale.js` files like the other exchanges are
- Set up your `settings.json` file to the market you just created

Then `npm start` your explorer and in a separate terminal you can run `cd /path/to/explorer && /path/to/nodejs scripts/sync.js market` to test the market sync and see if you get any errors, and if not, check your explorer and the data should appear.

**Comment by uaktags** [comment]
Added some labels, but note that we're probably not going to focus on building the custom exchange integrations. I've made a repo for people to add to it if they'd like, but it takes away from our development to worry about the exchanges that come and go constantly.

**Comment by vahid420** [comment]
like

**Comment by rubber-duckie-au** [comment]
@Ruxiol, Probably not worth a PR (especially as this explorer repo is heavily customized) but these will cover the first two points @joeuhren mentioned. Please note: I removed Whitebit off my explorer some time ago but they still should work.

https://github.com/rubber-duckie-au/explorer/blob/master/lib/markets/whitebit.js
https://github.com/rubber-duckie-au/explorer/blob/master/views/markets/whitebit.pug

**Comment by uaktags** [comment]
Closing, no further response. Above gave a proper response to help, but OP never came back.
