### ISSUE TITLE
A record set up but iquidus are not accessed by the subdomain only through the server ip

### ISSUE THREAD

**Issue by cibadmin** [iquidus/explorer#454]
hello,

I have created an a record pointing to my server ip but explorer is not working sub.domain:3001 it only works on the ip:3001 why and what did i do wrong it should work when creating the a record any help?

thx

**Comment by joeuhren** [comment]
This is a DNS problem and has nothing to do with the explorer software. You have already taken the correct action and created the "A" record. Most likely you just need to wait longer for propagation as it can sometimes take up to 48 hours and may depend on the TTL setting you created the "A" record with.

Try running an nslookup on the domain. Example:

```
ubuntu@ubuntu:~$ nslookup explorer.example.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   explorer.example.com
Address: 45.77.72.123

ubuntu@ubuntu:~$
```

If the answer you get back is the correct IP address, then you are done, it's working. If you don't get a valid response then you have some other DNS problem and/or need to wait longer.

If you still can't figure it out after waiting for propagation to complete, try contacting your domain registrar for more help as they will be able to provide more info about what could be going wrong.
