### ISSUE TITLE
what command to be used to close the session after npm start?

### ISSUE THREAD

**Issue by cibadmin** [iquidus/explorer#457]
Hello,

I wanted to make some editing to my settings so i stopped npm and it stopped with success I made what I did and then typed npm start and started successfully BUT the issue i am unable to get out of the screen i am typing ctrl+a+d it is not working if i shut down my ssh window the npm stops so i am keeping it opened until i get your help

regards

**Comment by joeuhren** [comment]
I would recommend using `npm start` only while testing to make sure your settings are correct and view the console messages to make sure you fix any warnings or errors and then use [forever](https://www.npmjs.com/package/forever) when the site is ready for production. Forever will run the explorer in the background and will even restart the explorer automatically if it crashes:

first install using:

```
sudo npm install forever -g
```

then run the explorer in the background:

```
cd /path/to/explorer
forever start bin/cluster
```

you can stop the explorer by running:

```
cd /path/to/explorer
forever stop bin/cluster
```

**Comment by uaktags** [comment]
npm start runs it within the same context as your ssh session: npm start isn't a daemon.

using screen, you'll be able to do npm start within a new screen, then ctrl+a+d to leave the screen running in the background and can close your SSH session as you like with npm still running.

This is naturally what npm start is, and not really a feature/issue with iquidus. I do however recommend @joeuhren method of using forever in node projects that you want to run like a daemon.
