### ISSUE TITLE
I am having an issue connecting with explorer

### ISSUE THREAD

**Issue by brocoinofficial** [iquidus/explorer#458]
Error:  OperationalError: connect ECONNREFUSED 127.0.0.1:6332
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:6332
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 6332
  },
  isOperational: true,
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6332
Please help me I tried changing port as well but still same issue !

**Comment by joeuhren** [comment]
It looks like you aren't able to communicate with your wallet daemon. You'll have to double-check the `wallet` section of the `settings.json` and match the values against your coins config file. Also, be sure the port is properly set to the RPC Port #, not the main Port #.

Example:

`settings.json`:
```
  "wallet": {
    "host": "localhost",
    "port": 9332,
    "username": "your_username",
    "password": "your_password"
  },
```

`coin.conf`:
```
rpcuser=your_username
rpcpassword=your_password
rpcallowip=127.0.0.1
rpcport=9332
port=9333
```

**Comment by ecorreasoto** [comment]
Me podrian ayudar tengo un problema al ejecutar  npm start...
root@goldpatron:~/explorer# npm start

> explorer@1.7.4 start /root/explorer
> node --stack-size=10000 ./bin/cluster

Starting cluster with pid: 2672
{ Error: connect ECONNREFUSED 127.0.0.1:31299
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  cause:
   { Error: connect ECONNREFUSED 127.0.0.1:31299
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 31299 },
  isOperational: true,
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 31299 }

**Comment by ecorreasoto** [comment]
ya lo solucione...

**Comment by uaktags** [comment]
Closing as we haven't heard back from OP, issue appears to be wallet related and their config. Advice seems likely as solution.
