### ISSUE TITLE
link to peers from network

### ISSUE THREAD

**Issue by crackfoo** [iquidus/explorer#46]
Hi, 

Can you add an option to allow viewing of network peers? Perhaps a list of ip's as well as a pre-formatted list using addnode=

Cheers

**Comment by iquidus** [comment]
this functionality will be available in next official release

**Comment by iquidus** [comment]
Most of this is now available in master branch, with the exception of the pre formatted addnode= list. This will be added soon

**Comment by crackfoo** [comment]
great, thanks!

**Comment by xieta** [comment]
Hi @iquidus,

I noticed, in the master branch the network list truncates the IPv6 node addresses at the first colon.
Seems this is the behavior is not limited to just my Iquidus instance, since after checking a few others in the wild, the same happens there.

-Xi

**Comment by TheHolyRoger** [comment]
This is now done
