### ISSUE TITLE
Get a list of all addresses with a positive balance

### ISSUE THREAD

**Issue by gdiscord** [iquidus/explorer#463]
Is it possible to query the explorer to dump all the addresses in the blockchain that have a positive balance?

**Comment by rubber-duckie-au** [comment]
you can leverage mongo for this:

`mongo --quiet explorerdb  --eval 'printjson(db.addresses.find({balance: {$gt: 0}}).toArray())' > output.json`

make sure your fully synced first

**Comment by gdiscord** [comment]
thanks, will give it a go.

**Comment by gdiscord** [comment]
the solution works a treat. closing now.

thanks.
