### ISSUE TITLE
Block fields Recipients and Amount are always 0

### ISSUE THREAD

**Issue by picacoin** [iquidus/explorer#466]
I followed all of the steps and got all of the blocks showing. The only issue is that for all of the blocks Recipients and Amount are 0.
![Screenshot 2021-05-30 212434](https://user-images.githubusercontent.com/84209422/120139492-74db2300-c18d-11eb-9a3a-60fc95b2fcc6.png)

**Comment by joeuhren** [comment]
Most coins that I've seen do not have an api that returns the total projected coin supply. Instead, most of them return the current supply at that moment, which is what is being used here.

That being said, there is an option for determining how the coin supply is calculated. Take a look at the `supply` setting in the `settings.json` file and see if maybe one of the other options for that setting is more to your liking.

**Comment by rishabhworking** [comment]
@joeuhren first of all thank you for the work you & your team have been sharing with the community for these past years. I have used the latest stable version in a few of my projects https://bpcexplorer.com and https://explorer.lightyears.io to name a few. These happen to be a fork of https://github.com/bitcoinpos/bitcoinpos, a POS chain. As you can see in both explorers, the reward field always shows 0. And it is the case only with the POS. The explorer works perfectly with POW chains.  
Now when you will check the https://explorer.bitcoinpos.net you will find that in the coinbase transaction you will find the reward in the input, not in output. What it does, it performs another transaction where it adds the reward to the staked amount. And Iquidus explorer is parsing just the coinbase transaction in this case, but not the next immediate transaction. Here is an example block: https://explorer.bitcoinpos.net/block-height/298751
![BpsExplorer](https://user-images.githubusercontent.com/39197153/120601427-895a3c80-c467-11eb-9643-82c5acaea667.png)

**Comment by picacoin** [comment]
@rishabhworking My coin is POW, Yet I still get all zeros. I wonder why. I changed the code using the following steps
https://github.com/iquidus/explorer/issues/78#issuecomment-368241329

But this is what caused the problem. Before I was just getting an error running "node scripts/sync.js index reindex."

**Comment by rishabhworking** [comment]
@picacoin please share your github repo, I will check

**Comment by picacoin** [comment]
@rishabhworking
Here you go
https://github.com/picacoin/explorer

**Comment by uaktags** [comment]
first off...THANK YOU for figuring out you have a problem BEFORE having a full fledged blockchain with issues to try to navigate. That took me like a whole 1minute to sync your chain....*$#king awesome.

So, looking at any one of the screenshot blocks, i'm getting totally different results.

```
./picacoin-cli getblockhash 18804
00000000000015cb0a4eaf124a71f94f8c9f3188eb53146c6ab14766ec93f2b2
```

```
./picacoin-cli getblock 00000000000015cb0a4eaf124a71f94f8c9f3188eb53146c6ab14766ec93f2b2
{
  "hash": "00000000000015cb0a4eaf124a71f94f8c9f3188eb53146c6ab14766ec93f2b2",
  "confirmations": 562,
  "height": 18804,
  "version": 536870916,
  "versionHex": "20000004",
  "merkleroot": "bbedc82e9e7b705f9d31e943abc344c69e55715d6459a2aef91819baae9c0d99",
  "time": 1622462647,
  "mediantime": 1622462340,
  "nonce": 816974864,
  "bits": "1b008c64",
  "difficulty": 119501.9966611018,
  "chainwork": "000000000000000000000000000000000000000000000000097eb736e714a392",
  "nTx": 1,
  "previousblockhash": "0000000000001f245f6b3ecd7e460390e9639d332350c55553bcd9935024232b",
  "nextblockhash": "00000000000001db8c8dcd95dae5c946c23cb87eddf4002fce69ac8e94f94442",
  "strippedsize": 189,
  "size": 189,
  "weight": 756,
  "tx": [
    "bbedc82e9e7b705f9d31e943abc344c69e55715d6459a2aef91819baae9c0d99"
  ]
}
```

```
tim@debvm:~/PIC$ ./picacoin-cli getrawtransaction bbedc82e9e7b705f9d31e943abc344c69e55715d6459a2aef91819baae9c0d99 1
{
  "txid": "bbedc82e9e7b705f9d31e943abc344c69e55715d6459a2aef91819baae9c0d99",
  "hash": "bbedc82e9e7b705f9d31e943abc344c69e55715d6459a2aef91819baae9c0d99",
  "version": 2,
  "size": 108,
  "vsize": 108,
  "weight": 432,
  "locktime": 0,
  "vin": [
    {
      "coinbase": "02744904b3d0b46008810000022fa692c64d43706f6f6c",
      "sequence": 0
    }
  ],
  "vout": [
    {
      "value": 50.00000000,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 49ed41c0a31dcd7806602c35453e202cf31deb61 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a91449ed41c0a31dcd7806602c35453e202cf31deb6188ac",
        "address": "17jtYu6jfRTrsH8yWKRw78vmGp47xHy5Tg",
        "type": "pubkeyhash"
      }
    }
  ],
  "hex": "02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff1702744904b3d0b46008810000022fa692c64d43706f6f6c000000000100f2052a010000001976a91449ed41c0a31dcd7806602c35453e202cf31deb6188ac00000000",
  "blockhash": "00000000000015cb0a4eaf124a71f94f8c9f3188eb53146c6ab14766ec93f2b2",
  "confirmations": 562,
  "time": 1622462647,
  "blocktime": 1622462647
}
```

So I'm at a loss of where our setups diverge. It'll help if I can setup my chain the same as yours so that I can peer into your git repo for the explorer and see what/if any changes are needed.

Currently running piacoin as just ./picacoind -server=1 -txindex=1 (along with all of the RPC bs i needed)

**Comment by uaktags** [comment]
I should also mention, that for the most part issues like these can be looked at quickly by running the JSONRPC commands (either via curl/-cli/iquidius API. In my example above, i'd totally expect there to be 50 in the TX vout with 1 recipient. However, not knowing where your others came from, I'm not sure the issue JUST yet.

**Comment by picacoin** [comment]
@uaktags Thanks for helping me out!
Heres my setup
./picacoind -daemon -txindex=1 -rpcport=4332

If it'll help here is my full config:
```
server=1
rpcuser=username
rpcpassword=password
rpcallowip=127.0.0.1
txindex=1
rpcport=4332
```
I ran the same commands as you did, and get your results, it just won't show in the explorer.

I also noticed that the Iquidus API call getaddress returns  {"error":"address not found.","hash":"3ASVUCaAwqeJgoq6XmTSSGLhoheY6A3jo7"}.

the Iquidus API call getbalance also returns the same result.

Also, I have both the picacoin server and the explorer on the same VPS. Could that be an issue?

**Comment by uaktags** [comment]
It's a problem with your coin's JSON

```
http://159.89.188.140:3001/api/getrawtransaction?txid=c435eb5db914e8e63eb87e120fde1796ca71ef9c8435de5d03acce83a54d84df&decrypt=1
```
This transactions shows 2 things: 1 is a standard TX of 50PIC from coinbase and 1 that is a nulldata.
The problem you're facing is with the JSON that's being returned:

```
{"txid":"c435eb5db914e8e63eb87e120fde1796ca71ef9c8435de5d03acce83a54d84df","hash":"c435eb5db914e8e63eb87e120fde1796ca71ef9c8435de5d03acce83a54d84df","version":2,"size":133,"vsize":133,"weight":532,"locktime":0,"vin":[{"coinbase":"510101","sequence":4294967295}],"vout":[{"value":50,"n":0,"scriptPubKey":{"asm":"OP_HASH160 5ff9e2ff235c0f7fe2e4aa3951ec66772cf04066 OP_EQUAL","hex":"a9145ff9e2ff235c0f7fe2e4aa3951ec66772cf0406687","address":"3ASVUCaAwqeJgoq6XmTSSGLhoheY6A3jo7","type":"scripthash"}},{"value":0,"n":1,"scriptPubKey":{"asm":"OP_RETURN aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9","hex":"6a24aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf9","type":"nulldata"}}],"hex":"02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff03510101ffffffff0200f2052a0100000017a9145ff9e2ff235c0f7fe2e4aa3951ec66772cf04066870000000000000000266a24aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf900000000","blockhash":"0000000082b627595073b7d60073bc7e70f47de52f1a58e919ef3a094e9e3332","confirmations":19367,"time":1620941276,"blocktime":1620941276}
```

The vout has a value of 50 (GOOD! we're expecting 50PIC) but it's going to "ADDRESS".....this is the kicker
```
https://github.com/picacoin/explorer/blob/c8c008877f30a69a0472c7ca71ed741f8402550b/lib/explorer.js#L500
```
Line 500 you'll see that Iquidus looks for "addresses" plural, not "address" singular.

Quick and dirty fix is to either change "addresses" in
```
hasOwnProperty("addresses")) {
```
to 
```
hasOwnProperty("address")) {
```
on line 500. That atleast got it to work for me in syncing, but i'm not sure if there's more to be changed as well (just coming back into the fold after some long away time).

This issue seems to be due to this in your coin:
```
https://github.com/picacoin/picacoin/blob/a1bf8c14786e1692b705121216fdf718bcb82128/src/rpc/rawtransaction.cpp#L137-L141
```

With that, atleast, I'm ready to say this issue is closed as not really a Iquidus issue but a problem with your own coin's JSON response. As the Picacoin doesn't have a fork there's no way for me to know if you (the developer) caused the "deprecated" event or if its from whereever you forked your coin from.

**Comment by picacoin** [comment]
@uaktags Thank you for all of the help, you are so informational. I figured that If I pass `-deprecatedrpc=addresses` to picacoind, it worked perfectly 😀
