### ISSUE TITLE
Explorer index check

### ISSUE THREAD

**Issue by TabbsCommunity** [iquidus/explorer#467]
Hey people,

So I I built my explorer and everything stays up to date, But the problem is I am now doing this by looping the command node scripts/sync.js index check, is there an other way cause this has some delay 1-3 minutes.

Thx for helping :)

**Comment by uaktags** [comment]
Is there anything wrong with the cron job of sync.js index update?

You'll have delays because the script uses a blocker so a new script instance won't start until the previous is finished.

**Comment by TabbsCommunity** [comment]
the cron job isn't working yes i added the lines idk what's going wrong there.

**Comment by uaktags** [comment]
What happens when you run the script directly from cli instead?

**Comment by TabbsCommunity** [comment]
Hey, thx for answering but i already solved it i added these lines to my coin .conf file
server=1
rpcport=44447
txindex=1
