### ISSUE TITLE
orphan block

### ISSUE THREAD

**Issue by cyberpay** [iquidus/explorer#47]
is there a way to check which block is orphan or which is confirmed

**Comment by CryptoCanary** [comment]
The explorer will only show blocks that confirm and are valid. Orphans are not accepted by the network and therefor not valid blocks. Orpans would only be visible where they were generated and rejected by the network, i.e. pool or wallet that submitted the rejected block.

**Comment by cyberpay** [comment]
thx and what is the difference in between different background color for the blocks stats? see screens 
http://imgur.com/iXUWBXm
http://imgur.com/rlBtgae

**Comment by CryptoCanary** [comment]
I believe you are looking at a block that is fully confirmed versus a block that is yet to be fully confirmed.

**Comment by cyberpay** [comment]
cool

**Comment by iquidus** [comment]
the background colors are based on the coins set maturity. 

you can configure with this setting: https://github.com/iquidus/explorer/blob/master/settings.json.template#L56

greater than setting = green
greater than setting/2 && less than setting = yellow
less than setting/2 = red

**Comment by rmdfwqclmrkcvpbe** [comment]
> the explorer only indexes valid blocks, it will not show orphans at present.

@iquidus It seems to be orphan blocks with BitCoin Core 0.15.x. (It's not BTC, it's ZNY.)
![x](https://user-images.githubusercontent.com/34421494/35075253-6932132c-fc35-11e7-8892-c33aeb52d57f.png)
