### ISSUE TITLE
Is this a EVM compatible block explorer ?

### ISSUE THREAD

**Issue by moda20** [iquidus/explorer#471]
Is this a EVM compatible block explorer ? if so why does it try to connect to bitcoin-core ?

**Comment by uaktags** [comment]
It is not, not without a huge deal of changes.

Note that bitcoin-cores usage has nothing to do with this explorer being tied to a particular coin. Instead, this library is merely used as a RPC library to communicate with coins. If another library proves more useful, we're able and willing to change to it.

**Comment by uaktags** [comment]
Closing as we'll probably never have this as a capability, if even at all possible. The way we store data, the amount of data on these types of blockchains like ETH/BSC/etc, and other reasons.
