### ISSUE TITLE
How are 'Latest Transactions' auto updated?

### ISSUE THREAD

**Issue by jpass022** [iquidus/explorer#474]
The correct block count is always shown in the lower right toolbar. But the 'Latest Transactions' window does not auto update to keep up with block count. If I enter the latest block in search box and search, thenreturn to the 'Latest Transactions' window, it is then up to date to the block I searched. Is there a setting to have the explorer auto update the 'latest Transactions' window to stay current with the block count?

**Comment by uaktags** [comment]
Latest Transactions is updated via the ``scripts/sync.js index update`` cron job that you need to have running. This script starts at "stats.last" or 0 and runs until the current block height at the time of execution (the block number that shows in the bottom right).

The text in the bottom right is just the output from the coin's API call and has no actual bearing on the data within iquidus (outside of the "current block height" when we run the sync script).

**Comment by uaktags** [comment]
Closing, no further response.
