### ISSUE TITLE
When I change from user/pass to username/password I get this error

### ISSUE THREAD

**Issue by uaktags** [iquidus/explorer#475]
When I change from user/pass to username/password I get this error 
```
{ Error: Invalid params, response status code: 401
    at IncomingMessage.<anonymous> (/app/node_modules/bitcoin/lib/jsonrpc.js:79:17)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: -32602 }
GET /api/getblockcount 200 144.729 ms - 39

```

_Originally posted by @sundanny26 in https://github.com/iquidus/explorer/issues/334#issuecomment-892095428_

**Comment by sundanny26** [comment]
I am using v1.6.2 exactly. And I was receiving the same error as in issue #334 
So I tried to update `user` to `username` in the configuration. of course it didnt work.
What I did to solve it now is use a previous built I had of the 1.6.2, since building it again was bringing me this issues. Probably because of some update on the bitcoin rpc module. 

I need to update to newer version for this to be solved. So I think you can close this issue for now.

**Comment by uaktags** [comment]
@sundanny26 
So to confirm, you're only using 1.6.2 and received the issue? Or did you have 1.6.2 working for a long while, and then attempted to upgrade to the most recent version and it failed? 

Please note there's a large number of changes between 1.6 and 1.7.x versions (such as pug vs jade) so any manual changes you have in those jade files also need porting over and whatnot. It tends to be better to just start with a fresh 1.7.x-stable build as a separate instance, connect it to the same mongodb instance, and port over the changes to pug.

**Comment by sundanny26** [comment]
I am using 1.6.2, Then I migrated the application to another server and when with the new build It didnt work. So I had to push an older image already built months ago, and that one worked nice.
yeah there are too many changes. I will probably just start fresh with 1.7 and update the things I have in 1.6. 
Thank you @uaktags

**Comment by uaktags** [comment]
Closing, hope you got setup and are doing well.
