### ISSUE TITLE
getting connection error

### ISSUE THREAD

**Issue by alexdice55** [iquidus/explorer#478]
Hi, when I try to run "mongo" command on Ubuntu 18.04 on VMWare I getting bellow error:

MongoDB shell version v5.0.2
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:372:17
@(connect):2:6
exception: connect failed
exiting with code 1

how I can fix that?

**Comment by joeuhren** [comment]
If you recently installed mongo, you may have it installed but not started. You can usually start it with a cmd like this:

```
sudo service mongod start
```

I also typically set up a service for mongo as well so that it will automatically start after a reboot with this:

```
sudo systemctl enable mongod.service
```

Once mongo is started, running the `mongo` cmd should work without errors. I hope that helps.

**Comment by enginlien** [comment]
@joeuhren
Hi
I have the same problem,
I try to run "mongo" command on Ubuntu 18.04,
I got error like this :
![Screenshot from 2021-12-29 17-17-33](https://user-images.githubusercontent.com/87757542/147646359-881827d4-7bdd-4784-8d5a-f27f40bcbd17.png)

Can you help me slove this problem?
Thanks

**Comment by joeuhren** [comment]
@enginlien I've only ever seen the error you are getting when mongo is installed but not actively running. Did you try either of the 2 cmds mentioned above to start the mongo server? Try running both cmds, reboot ubuntu, then try the `mongo` cmd again.

**Comment by ghost** [comment]
I had heaps of issues with Mongo. Had to remove ALL the repos and installations (had about 3 versions?) and use 4.4 on my Ubuntu machine. The error above, from memory, was the from the service not running - I could not start mine as it couldn't be found.

Anyway, following this resolved my issues https://askubuntu.com/questions/1403619/mongodb-install-fails-on-ubuntu-22-04-depends-on-libssl1-1-but-it-is-not-insta

**Comment by uaktags** [comment]
Closing, 

OP didn't reply back that they tested to make sure they started the service.
Secondary issue was due to not having mongo installed (its a pre-req, and stated "as it couldn't be found").
