### ISSUE TITLE
Constant Error

### ISSUE THREAD

**Issue by NLC1609** [iquidus/explorer#482]
Usage: node scripts/sync.js [database] [mode] database: (required) index [mode] Main index: coin info/stats, transactions & addresses market       Market data: summaries, orderbooks, trade history & chartdata mode: (required for index database only) update       Updates index from last sync to current block check        checks index for (and adds) any missing transactions/addresses reindex      Clears index then resyncs from genesis to current block notes: * 'current block' is the latest created block when script is executed. * The market database only supports (& defaults to) reindex mode. * If check mode finds missing data(ignoring new data since last sync), index_timeout in settings.json is set too low.Usage: node scripts/sync.js [database] [mode] database: (required) index [mode] Main index: coin info/stats, transactions & addresses market       Market data: summaries, orderbooks, trade history & chartdata mode: (required for index database only) update       Updates index from last sync to current block check        checks index for (and adds) any missing transactions/addresses reindex      Clears index then resyncs from genesis to current block notes: * 'current block' is the latest created block when script is executed. * The market database only supports (& defaults to) reindex mode. * If check mode finds missing data(ignoring new data since last sync), index_timeout in settings.json is set too low.

Guys I constantly get this error when I try to set up the explorer and sync it, please help. Thanks Lol

**Comment by uaktags** [comment]
What error do you get? You pasted readme documentation.

**Comment by uaktags** [comment]
No response.
