### ISSUE TITLE
Unable to connect to explorer API

### ISSUE THREAD

**Issue by bandexcoin-project** [iquidus/explorer#483]
hey, i am getting (Unable to connect to explorer API) error while syncing my coin.

Coin's conf file is
rpcuser=explorer
rpcpassword=explorer
rpcport=8766
port=8767
rpcallowip=127.0.0.1
daemon=1
server=1
txindex=1

settings.json wallet conf is
  "wallet": {
    "host": "127.0.0.1",
    "port": 8766,
    "username": "explorer",
    "password": "explorer"
  },

I'm not getting any connection issues. except (Unable to connect to explorer API) error while syncing the coin with the pool

**Comment by totaltrader** [comment]
Coin's conf file is
rpcuser=explorer
rpcpassword=explorer
rpcport=8766
port=8767 (erase it)
rpcallowip=127.0.0.1
daemon=1
server=1
txindex=1

**Comment by uaktags** [comment]
Closing as OP reacted to the emoji and never closed/commented.
