### ISSUE TITLE
Top 100 over estimated wildly on pos coin.

### ISSUE THREAD

**Issue by regtable** [iquidus/explorer#486]
I have just indexd from 0 all way to top with no breaks in sync and the top 100 seems to be over on most if not all pos coins. Is that normal…

**Comment by joeuhren** [comment]
Can you provide more detail about exactly what you mean by "the top 100 seems to be over estimated"? Screenshots? Which coin(s) are having this problem?

**Comment by uaktags** [comment]
Closing, very vague "issue". 
richlist gets updated during every update/reindex/etc with the following calls and it happens after updating the TXes, so the data should be as acurate as the last tx sync.
```
db.update_richlist('received', function(){
  db.update_richlist('balance', function(){
  ```
