### ISSUE TITLE
Any  Chance to Add Livecoin.net Market API

### ISSUE THREAD

**Issue by Reecoin** [iquidus/explorer#49]
Any  Chance to Add Livecoin.net Market API ??

**Comment by helleniccoin** [comment]
Any Chance to Add Livecoin.net Market API ??

**Comment by NxtGenCowboy** [comment]
Any Chance to Add Livecoin.net Market API ??

**Comment by TheHolyRoger** [comment]
Exchange markets are no longer hardcoded thanks to @uaktags - https://github.com/iquidus/explorer/commit/2be23e2f8f0e446943518303efef95ca964c59a9
