### ISSUE TITLE
Our explorer stopped working all of a sudden

### ISSUE THREAD

**Issue by Pivotalcoin** [iquidus/explorer#491]
Hi

Our explorer stopped working all of a sudden may you kindly help?

**Comment by joeuhren** [comment]
Can you provide more details? Screenshot? What error msg do you see?

I would assume if the explorer was working fine and then all of the sudden just stopped that something external caused the problem. For example, was an update run on the server recently? Did the server run out of disk space? Any other server changes you can think of? How about a recent change to the blockchain itself where the data was changed to a format that is unsupported by the explorer?

**Comment by Pivotalcoin** [comment]
Hi

Attached is a screenshoot it last updated long back and no change was 
made.

Regards

**Comment by joeuhren** [comment]
Sorry, I do not see any attached screenshot.

Please provide any error messages displayed in the terminal and on the website itself.

**Comment by Pivotalcoin** [comment]
Hi

I have reattached the screenshoot.

Regards
Ben

**Comment by joeuhren** [comment]
Whatever you are doing to attach the screenshot is not working, I can't see it. You can use the Preview tab to view what the msg will look like before sending. But maybe it is easier to just type out the error msg?

**Comment by Pivotalcoin** [comment]
Hi

We do not have any error message but the explorer is just not moving.

Regards
Ben

**Comment by joeuhren** [comment]
How was it moving before? Did something happen with your cron job?

What happens when you try to issue the index update cmd manually?
`cd /path/to/explorer && /usr/bin/nodejs scripts/sync.js index update`
(Make sure to change the paths to your absolute explorer path and path to node for the cmd to work)

**Comment by Pivotalcoin** [comment]
It was updating without stalling, now there is no update of the 
blockchain.

**Comment by joeuhren** [comment]
It seems that either there is an error when trying to run the index/update cmd or your cronjob has stopped running for some reason. Either fix whatever problem you have with your cron job or try running the cmd I posted above (make sure to change the paths to match your environment) and see if that starts syncing the blockchain again or shows an error msg.

**Comment by uaktags** [comment]
@Pivotalcoin, attaching screenshots to email replies won't work. FYI.

**Comment by uaktags** [comment]
Closing as no new update.
