### ISSUE TITLE
the explorer not start working

### ISSUE THREAD

**Issue by wuhonchi** [iquidus/explorer#495]
after npm start and mongodb setup
the layout out pop out but data seems can't even load 
error log as below ..... any comments or suggestion ?

Cluster restarting...
(node:40141) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:40141) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:40141) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:40141) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
(node:39850) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead
undefined:1
invalid content type, only application/json is supported
^

SyntaxError: Unexpected token i in JSON at position 0

**Comment by joeuhren** [comment]
I'm not sure I've seen that particular error before but it seems to be indicating there is some unexpected data in one of the JSON files.

Try temporarily renaming your settings.json file to something else and then start  the explorer with `npm start` and see if you get the same error.

What version of node.js are you using? You can type the cmd `node -v` to find out. I'm wondering if you are maybe using a really old version?

Have you made any custom changes to the explorer code?

Did you happen to copy any of the files to the server from another computer? You can sometimes get weird problems with file formats if you copy files from windows to a linux computer for example which may cause this type of problem.

Let us know how it goes

**Comment by wuhonchi** [comment]
i would like ask what's the coind for ?
and what's the wallet setting for config.json ?

**Comment by joeuhren** [comment]
coind is your coins daemon wallet. It is usually called something like bitcoind (whatever your coin name is, followed by the letter 'd'). You will need to specify the RPC information for your daemon wallet in the explorer config file so that the explorer can connect to the wallet and get information out of it.

**Comment by uaktags** [comment]
closing as the issue has gone stale. The basic readme file provides all of this information needed to setup. OP can reopen if there's more to add.
