### ISSUE TITLE
Index Issue

### ISSUE THREAD

**Issue by machado-rev** [iquidus/explorer#5]
This message are all the time on the front end, I create a crontab to make the index update every minute but do not work properly, when I run the update said something like that: "script already running". On the front end show this message: "Warning: Indexing is currently incomplete, functionality is limited until index is up-to-date"

How to solve this? Thank you

**Comment by iquidus** [comment]
Hi machado-rev,

The initial index can take a long time to produce (~2+ hours depending on blockchain). If it does not exit cleanly it will leave a .pid file behind in the tmp/ folder; index.pid. If you are certain the sync script is not currently running, but you receive the 'script already running' message. remove tmp/index.pid and the sync script will run as normal. It works like this to prevent the indexing script from being able to run twice at the same time, e.g if the initial index is running but still not done, and your crontab tries to launch the script again.

**Comment by machado-rev** [comment]
Ok, I will try agaun, really thanks, Iquidus Explorer are awesome

**Comment by iquidus** [comment]
If you run into any problems dont hesitate to reply here. We could set up a time to meet up over irc, I'm happy to help you get everything up and running.

**Comment by machado-rev** [comment]
All are running very good and stable, I have a question, Abe have a function in Datastore.py, we can adapt to Iquidus? It's used by Android Wallets, I will post here today the code to see.

**Comment by iquidus** [comment]
I'm going to close this issue as your indexing issue is resolved. As we discussed on irc, the additional functionality for android wallet compatibility is planned for version 1.5.0
