### ISSUE TITLE
Google Adsense

### ISSUE THREAD

**Issue by Zetalon0** [iquidus/explorer#500]
Possible to include ads?

**Comment by uaktags** [comment]
Sure, you can add it to the html portion of the views.

**Comment by Zetalon0** [comment]
Thx but where is that?

**Comment by uaktags** [comment]
https://github.com/iquidus/explorer/blob/master/views/layout.pug

this is the overall layout of the Explorer (head + body). You'll have to write your script in pug format, but that should be pretty straightforward looking at how scripts are added in the layout.

So you're probably looking at something like
```
script(async, src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-#####"
     crossorigin="anonymous")
ins.adsbygoogle(style="display:block", data-ad-client="ca-pub-####", data-ad-slot="####", data-ad-format="auto", data-full-width-responsive="true")
script.
     (adsbygoogle = window.adsbygoogle || []).push({});
```

Note that you can always use a resource like https://html2pug.vercel.app/ to convert html to being Pug/Jade compatible.

**Comment by Zetalon0** [comment]
thx
