### ISSUE TITLE
Installing explorer to other vps and daemon on another vps

### ISSUE THREAD

**Issue by violetdroidxz** [iquidus/explorer#501]
Hi there,I Successfully setup coin's explorer ,,,but the issue is I installed on another vps and coin's daemon on the other one vps ...My block explorer is opened but does not showing blocks ...Just blank table ...

**Comment by uaktags** [comment]
If the coin's daemon is on another server, you just need to provide the IP/Port and config to access it.

Go to your settings.json and make the wallet portion reflect the coin daemon's server creds, and make sure you have the coin daemon setup to accept the connections.

**Comment by violetdroidxz** [comment]
"PORT" means coin's rpc PORT right!!

**Comment by uaktags** [comment]
```
"wallet": {
    "host": "localhost",
    "port": 9332,
    "username": "darkcoinrpc",
    "password": "123gfjk3R3pCCVjHtbRde2s5kzdf233sa"
  },
  ```
  "port" above, under the WALLET section, refers to the RPC Port of your coin daemon.

**Comment by violetdroidxz** [comment]
Hi, uaktags ..I done same as u described ,,,but When I run ...it shows error  ... ECONNRESET .. :\

**Comment by uaktags** [comment]
closing as this is the 3rd issue of the same thing. Just open 1 and stick to it.
