### ISSUE TITLE
ECONNRESET,ECONNREFUSED AND SOCKET HANGUP .... ERROR SOLVED BY ME 

### ISSUE THREAD

**Issue by violetdroidxz** [iquidus/explorer#504]
Hi there, I solved the issue of ECONNRESET,ECONNREFUSED AND SOCKET HANGUP -----
So here is the heck ....It doesn't matter whether you are using on same machine or different machines (daemon/qt wallets and explorer on different VPS)

So the problem is wherever the daemon and explorer installed ... If you installed on same machine (wallets and explorer)
then also solution is same ...

Now if your wallet is running then CLOSE it...
The default RPC port of coin's daemon is already listening,So don't mention on conf file ...
We assign a new port inside conf file,along with other credentials ..like USERNAME,PASSWORD,SERVER=1,DAEMON=1,Txindex=1, addnodes=xxxxxxxxx,allowip=127.0.0.1...,
Now rpcallowip=127.0.0.1 is default..So mention it,And now we assign a new ip of your vps server *wherever vps you are using**If u are using 2nd VPS and your daemon is on 1st VPS then put your 2nd VPS IP in conins conf file 
along with new RPCPORT > rpcport= <new port>  ...then save it ...and put the same credentials on the explorer settings.json file /// then save it ...and run ...NOW your explorer is working with no error

**Comment by uaktags** [comment]
this is redudant to say the least to have 3 issues. Just update YOUR issue.
