### ISSUE TITLE
Shows double blocks

### ISSUE THREAD

**Issue by eddef** [iquidus/explorer#51]
I have a small issue, the explorer runs as it should but it displays 2 blocks. One is the newly generated coins, the second show the extra transactions in that block.
You can take a look at :
http://explorer.sicanet.net

**Comment by rudy4682** [comment]
It is working as designed

**Comment by iquidus** [comment]
The front page lists transactions not blocks. If the blocks that seem to be appearing multiple times is because they contain multiple transactions. this is intended behavior
