### ISSUE TITLE
Use of labels

### ISSUE THREAD

**Issue by dimecoinco** [iquidus/explorer#52]
Hi,
This is just a question regarding use of labels. I am frightened of messing it up by experimenting, especially if it is not possible anyway. 

Is it possible to use a label on the front page under "coin supply?" I use a "this is a burn address" label with an account which can be seen when you check the top-100 accounts, or search using the account address. It was simple to set up, because of the example given in settings.

The "coin supply" box obviously includes the burn address coins in the coins in the total it reports are in supply. I was wondering whether it is possible to add a label (or link) here which states "X amount of coin supply destroyed". 

Thanks and regards

**Comment by uaktags** [comment]
Closing. #257 has added a way to bring labels into a usable context with being able to claim them.
