### ISSUE TITLE
scrypt blockchain explorer

### ISSUE THREAD

**Issue by etype** [iquidus/explorer#53]
good day is there anyway to build a block-chain explorer for a scrypt coin

**Comment by gwbraa** [comment]
Yes just follow the instructions the explorer will function pretty much if any algo
I just setup one in quark

**Comment by etype** [comment]
Nice thanks man 

 

I manage to setup a easy blockchain thingie

 

How much would you charge me to set it up for me on my server

**Comment by iquidus** [comment]
It's a straight forward process to do yourself. Give it a go, and if you run into any problems, join the jumbucks slack http://slack.getjumbucks.com , ask explorer questions in #programming channel, myself and a few others also, will be able to help you out.

**Comment by iquidus** [comment]
The codebase works with all bitcoin based clones, no code changes required. everything can be set in settings.json. requires mongodb 3.2.x and nodejs 4.x or greater.

**Comment by grasshaussoftware** [comment]
im trying to figure out how to install the explorer for my coin and im not sure what value to set in the config file
