### ISSUE TITLE
node scripts/sync.js index reindex - Only index's block #1

### ISSUE THREAD

**Issue by CluelessOnePlus2** [iquidus/explorer#55]
Hello, 
Issue is when i run: `node scripts/sync.js index reindex`
It returns: reindex complete (block: 1)
then
I run `node scripts/sync.js index update`
I get the same results as "reindex"

On the website. It only displays block #1. 
Only when I enter a block height in the search bar of the site I get to see address, amounts, etc. 
When I return to home page, It now it displays only the blocks I entered in the search

thanks

**Comment by MartinSolie** [comment]
Have you started the explorer, before running this script ? 
My problem looked very similar to yours, and I was trying to run script while the explorer was shut down.

**Comment by SplitPeaches** [comment]
Hello, Im having a similar problem.  when I run:
node scripts/sync.js index update

I get this error:
Unable to connect to explorer API
update complete (block:1)

Any thoughts on what I'm doing or have set wrong? 
Thanks!

**Comment by MartinSolie** [comment]
Is you server running, while you are trying to run update ? 
In other words, have you run `npm start` before running `node scripts/sync.js index update` ?

**Comment by SplitPeaches** [comment]
Thanks so much MartinSolie!! Yes that was my problem.  I was trying to update without having the npm started. ugh   Thanks for your help!

**Comment by zhq1** [comment]
I have this problem, how to deal with

**Comment by cvaldezissc** [comment]
i have this problem too, does anyone know how to fix it?
i used this console command
` sudo node scripts/sync.js index update && npm start
`

**Comment by compcoinproof** [comment]
Having this same issue, unable to sync... saying TX NOT FOUND... not sure how its getting that TX ... I did comment out the "genesis" & "api" sections from ./settings.json ... is this the problem??

sudo node scripts/sync.js index update
script launched with pid: 13460
tx not found: cd9e35cb09d1b66e4b8ec77cf40597b239b055202fb8c2d160107f38c5dc1d9a
update complete (block: 1)

**Comment by CryptorClub** [comment]
This command helps me
`sudo node scripts/sync.js index update`

**Comment by SynchrotronCoinDev** [comment]
I solved it by removing all data from .coin folder and add the following lines in .conf file after recreating it 
 `listen=1
  txindex=1
  deamon=1
  rpcuser=..
  rpcpassword=..`
