### ISSUE TITLE
Unable to connect to explorer API

### ISSUE THREAD

**Issue by sirdanielfortesque** [iquidus/explorer#57]
Hi, I'm trying to create a block explorer for my coin, all seemed working until I got this error while syncing the db with the chain:

root@vps:/home/explorer# sudo node scripts/sync.js index update
script launched with pid: 1137
Unable to connect to explorer API
update complete (block: 1)

I get this error "Unable to connect to explorer API".

My config file is written as follows (set as read-only):

rpcuser=COINRPC
rpcpassword=PASSWORD
listen=1
server=1
port=21478 (rpc port of my coin)
txindex=1
rpcconnect=127.0.0.1
maxconnections=500

I tried these fixes:

- rebooting and relaunching
- "rpcport=21478" instead of "port" (gives error in explorer page "check your console")
- "rpcconnect=VPS IP ADDRESS" (nothing happens)
- tried tmp/index.pid (no such file or directory)

Wallet is working (getinfo, getmininginfo ok).
Is something related to settings.json file? 
I can display successfully the explorer on port 3001 but it's empty - no errors "check console" are given. I got no error during all the processes and the only issue I have is this "Unable to connect to explorer API". Lots of headaches but nothing comes up. Anyone had similar issues?

**Comment by Stone-Hedge** [comment]
Obvious question but have you configured your settings.json to match the settings in your conf file?

**Comment by iquidus** [comment]
This was a result of incorrect rpc configuration, we sorted it out in the jumbucks slack.

**Comment by SplitPeaches** [comment]
Hello, Can you please tell us what the problem was in the rpc configuration and the fix? I am getting the same error.  Thanks!

**Comment by dezzyboy** [comment]
same issue here did this get clarified on what the rpc conf error was

**Comment by bunbunbunbunbunny** [comment]
I have same error


And i am sure at 500% that the rpc port that ive put is the correct one ...

how to solve this ??

**Comment by uaktags** [comment]
Confirm that your RPC is working by doing curl tests. Also look at your daemon's debug log to ensure that it's listening and got set up. 

Create a new ticket as this was issue was created in error and found to be user conf issue, not a iquidus bug. Explorer needs to know the RPC port, RPC server, RPC user, and RPC password. Your conf needs to be setup with the allowedip of the server running Iquidus, needs to be bound to the port, and needs to be accessible (firewall). Until there's any error that shows that this is an iquidus issue, there's not much we can really do.

**Comment by bunbunbunbunbunny** [comment]
> 
> 
> Confirm that your RPC is working by doing curl tests. Also look at your daemon's debug log to ensure that it's listening and got set up.
> 
> Create a new ticket as this was issue was created in error and found to be user conf issue, not a iquidus bug. Explorer needs to know the RPC port, RPC server, RPC user, and RPC password. Your conf needs to be setup with the allowedip of the server running Iquidus, needs to be bound to the port, and needs to be accessible (firewall). Until there's any error that shows that this is an iquidus issue, there's not much we can really do.

I have solved it, thank you  !

**Comment by Laser9un** [comment]
I have the same issue when I put "#" in the RPC password.
