### ISSUE TITLE
No data available in table

### ISSUE THREAD

**Issue by cryptominers-online** [iquidus/explorer#64]
hi guys just trying the explorer here http://84.200.210.86:8088/

it shows the no of blocks in the bottom and connected peers 
ive created a default  user with read/write access: " Just =too see how it works when ive sorted it i will change it all over " 

> db.createUser( { user: "iquidus", pwd: "3xp!0reR", roles: [ "readWrite" ] } )

what am i doing wrong ? 

ive filled out the info in the config etc and added the cronjobs 

what command do i use to update the database so it shows the blocks etc 

ive tried this 

sudo node scripts/sync.js index update
Script already running..

and sudo node scripts/sync.js database update

but get Usage: node scripts/sync.js [database] [mode]

any help would be great thank you guys 

here is my coin conf 

listen=1
server=1
demon=1
rpcuser=coinname
rpcpassword=6546545654
rpcport=5943
enableaccounts=1
rpcallowip=127.0.0.1
txindex=1

**Comment by cryptominers-online** [comment]
sorted it now for anyone else who was in my boat , 

remove the pid from temp folder 

and run sudo node scripts/sync.js index reindex 

just hope my cronjobs are working now :)

**Comment by 008** [comment]
thank you
