### ISSUE TITLE
facebook link in settings 

### ISSUE THREAD

**Issue by cryptominers-online** [iquidus/explorer#65]
hi guys what do i put in the facebook part of it as when i put say 

https://cs-cz.facebook.com/people/Printerium-Dev/100015058543078 

it comes up with 

https://www.facebook.com/undefined

thanks guys

**Comment by legends420** [comment]
having the same issue i know the setting is in settings.json but it doesnt show up on the page

**Comment by sburina** [comment]
In app.js, find the line:
```
app.set('twitter', settings.twitter);
```

and add a new one below it:

```
app.set('facebook', settings.facebook);
```

Et voila. :)
