### ISSUE TITLE
Market box showing when false

### ISSUE THREAD

**Issue by cryptominers-online** [iquidus/explorer#66]
i run a few blockchains on my server and all works well appart fomr 1 thing 

The markets are set to  false as shown below

// menu settings
  "display": {
    "api": false,
    "markets": false,
    "richlist": true,
    "twitter": true,
    "facebook": false,
    "googleplus": false,
    "search": true,
    "movement": true,
    "network": true

But it still shows some random market 

How would i fiox this either by removing the block compleatly ? 

thankls

**Comment by bumbacoin** [comment]
i have found the same problem.
