### ISSUE TITLE
How to add cryptopia

### ISSUE THREAD

**Issue by Findblocks** [iquidus/explorer#68]
hi guys got my settings as 
  "markets": {
    "coin": "SFC",
    "exchange": "BTC",
    "enabled": ["cryptopia"],
    "cryptopia_id": "1658",
    "ccex_key" : "",
    "default": "cryptopia"
  },
 
it wont work no matter what i do ? have i made a mistake ? also whats a cryptopia id ? is this correct 

thanks guys

**Comment by jemekite** [comment]
Hi,

You put wrong cryptopia_id in your config, correct id for SFC is `4713`
You can find it here: 

```https://www.cryptopia.co.nz/api/GetTradePairs```

```
{"Id":4713,"Label":"SFC/BTC","Currency":"SolarflareCoin","Symbol":"SFC","BaseCurrency":"Bitcoin","BaseSymbol":"BTC","Status":"OK","StatusMessage":null,"TradeFee":0.20000000,"MinimumTrade":0.00000001,"MaximumTrade":100000000.0,"MinimumBaseTrade":0.00000500,"MaximumBaseTrade":100000000.0,"MinimumPrice":0.00000001,"MaximumPrice":100000000.0}
```
