### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by legends420** [iquidus/explorer#69]
www.ganjacoinpro.com  click block explorer to see
Rich list not populating
Coin Supply not showing right amount
All address dont load into block explorer only a few

has anyone else had these problems?

**Comment by legends420** [comment]
Nvm got it working

**Comment by bitfawkes** [comment]
could you type the command you use please?

**Comment by legends420** [comment]
it was rm tmp/index.pid to delete old file then run crons again should update everything
