### ISSUE TITLE
Missing Blocks in Latest Transactions List

### ISSUE THREAD

**Issue by phatkiller** [iquidus/explorer#76]
Whenever a block is found with reward 0.00000001 or 0,  The blocks don't appear on the on the main page with the Latest blocks/transactions.  You can search and find them if you type the block height in manually.

This is happening specifically with the coin 23-skidoo it has block rewards ranging from 0.00000001 to 0.00001

http://skidoo.duckdns.org:3001

**Comment by KrakenCoins** [comment]
same here

**Comment by BloodyNora** [comment]
`views/index.jade` around line 40 is where it does get the display data from the `getlasttxes` api call, with `0.00000001` as a `minimum amount` parameter. it results to a HTTP call to `/ext/getlasttxs/0.00000001` - switching to `-1` made the blocks reappear, but i cannot guarantee that it wont lead to other problems for you.

**Comment by TheHolyRoger** [comment]
Fixed in https://github.com/iquidus/explorer/commit/cae9a67da6ba55b84ce5c99904aec901e45dea4d
