### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by radmans** [iquidus/explorer#80]
Is there any "how to" Install GUI Iquidus explorer on public web server with Mysql.. ?

**Comment by kepoly** [comment]
You don't need mysql. The explorer uses Mongo.

Follow the insturctions here https://gist.github.com/zeronug/5c66207c426a1d4d5c73cc872255c572

Pay close attention to the settings file part as the config options are in there. Once you have the server running visit your url+port set in the settings file, default 3001.

**Comment by dbkeys** [comment]
Looks like zeronug zeroed out his presence....  Go way back ....
https://web.archive.org/web/20201029174520/https://gist.github.com/zeronug/5c66207c426a1d4d5c73cc872255c572
