### ISSUE TITLE
Where is my Explorer's url?

### ISSUE THREAD

**Issue by ElectroCreator** [iquidus/explorer#81]
Hi, can someone help me?
I set up the stuff, but when I go to my servers ip, nothing shows up.
Help is much appreciated

**Comment by xieta** [comment]
Hi ElectroCreator,

The default port from settings.json is 3001 as seen here.
    https://github.com/iquidus/explorer/blob/master/settings.json.template#L10

You will want to make sure you're trying the address and port you have specified there.

-Xi

**Comment by ElectroCreator** [comment]
Hi, yes I know that, also thanks for replying to my issue.
It cant connect to the MongoDB database.
Here are my settings for the dbsettings at settings.json
  
// database settings (MongoDB)
  "dbsettings": {
    "user": "electro",
    "password": "electro2234",
    "database": "electrodb",
    "address": "127.0.0.1",
    "port": 27017
  },

**Comment by ElectroCreator** [comment]
@xieta 
Can you help me with this?

**Comment by ElectroCreator** [comment]
I also enabled ipv6 on my server.

**Comment by xieta** [comment]
Hello @ElectroCreator,

Double check your work with regard to adding the user privileges to the Mongo collection.
[Node and Iquidus Explorer Setup for Dummies](https://gist.github.com/zeronug/5c66207c426a1d4d5c73cc872255c572)

-Xi

**Comment by awochna** [comment]
If your original question hasn't already been self-answered, you should be able to point your browser to http://your.ip.address.here:3001 to see the explorer, even if the database is empty. Not sure what it'll do if it can't connect to the database.
