### ISSUE TITLE
I am having an error connecting to the Database, please help!

### ISSUE THREAD

**Issue by ElectroCreator** [iquidus/explorer#82]
Hi, Im having a problem connecting to the database. 
Is this corrrect?

// database settings (MongoDB)
"dbsettings": {
"user": "electro",
"password": "electro2234",
"database": "electrodb",
"address": "127.0.0.1",
"port": 27017
},

**Comment by xieta** [comment]
Hello @ElectroCreator,

See [issue #81](https://github.com/iquidus/explorer/issues/81) for a reply to this inquiry which has been asked previously.

-Xi
