### ISSUE TITLE
Need help: tx and movements etc all limited to 100, how to get more?

### ISSUE THREAD

**Issue by jlong187** [iquidus/explorer#88]
I create an explorer for an altcoin, but the tx, movements, tx for an address etc all limited to 100, once I click to page 10, it has no more data. I updated the "tx count" in settings.json to 1000, but still only 100 displayed. How can I make these 100s to 1000s? Which code I should change? Thanks for helping.

**Comment by awochna** [comment]
Just checking to make sure, but did you restart the application after updating your `settings.json` file after updating it? That way the explorer picks up the new settings.

**Comment by TheHolyRoger** [comment]
Fixed in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc
