### ISSUE TITLE
reindex complete (block: 1)

### ISSUE THREAD

**Issue by foxer666** [iquidus/explorer#90]
Good day.

node scripts/sync.js index reindex
script launched with pid: 8077
Unable to connect to explorer API
index cleared (reindex)
reindex complete (block: 1)

**Comment by foxer666** [comment]
Sorry.
Find it
https://github.com/iquidus/explorer/issues/55#issuecomment-259658803

**Comment by cryptonana** [comment]
goto explorer/tmp and remove index.pid and reindex again
