### ISSUE TITLE
Start Node Exit Status 1

### ISSUE THREAD

**Issue by 200MPH** [iquidus/explorer#93]
Hello,

I cannot run the service.
I was trying to figure out why this is not working and I gave up due to lack of proper log output.
Here is entire log, any help would be very appreciated.
```

> explorer@1.6.1 start /root/explorer
> node --stack-size=10000 ./bin/cluster

npm ERR! explorer@1.6.1 start: `node --stack-size=10000 ./bin/cluster`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the explorer@1.6.1 start script.
npm ERR! This is most likely a problem with the explorer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --stack-size=10000 ./bin/cluster
npm ERR! You can get their info via:
npm ERR!     npm owner ls explorer
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /root/explorer
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

Regards,

**Comment by 200MPH** [comment]
Here is what I found in the syslogs:
 

> No AX.25 port data configured

I did research and it's reffering to AX25 package which is for modem set-up. Am I right?

**Comment by awochna** [comment]
Hi @200MPH 

I'm not super familiar with Debian specifically, so I want to make sure we try one thing hinted at the bottom of your output logs:

```
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

Have you already looked at that file and found it unhelpful?

**Comment by 200MPH** [comment]
Hi Awochna,

My node version v0.10.29
Required node version >= 0.10.28

It should work.
File READMY.Debian does not says anything interesting.

But system log says No AX.25 port data configured. Error is throw when I try to run node.
But AX.25 looks like a modem drivers.

**Comment by 200MPH** [comment]
Hi Awochna,

You were right.
I missed wery important thing when reading: /usr/share/doc/nodejs/README.Debian

In Debian the interpreter command has been changed to "**nodejs**".

> 
> This was done to prevent a namespace collision: other commands use
> the same name in their upstreams, such as ax25-node from the "node"
> package.

Sorry for being dumbass ...

**Comment by awochna** [comment]
@200MPH No worries, different OS's have weird little things like that.

I remember something like this happening on Ubuntu a few years ago, but the details completely escape me at the moment.

**Comment by 200MPH** [comment]
@nejeoui 

Thanks mate,
That's what I did in my prev post from 2 Sep :)
