### ISSUE TITLE
NPM Start Failures

### ISSUE THREAD

**Issue by ghost** [iquidus/explorer#98]
These failures come in right after I hit npm start, so it looks like theres no connection being made to my daemon when I know its running. 

`GET /ext/getlasttxs/0.00000001?_=1504903860945 200 25ms - 11b
{ [Error: connect ECONNREFUSED 127.0.0.1:80]
 code: 'ECONNREFUSED',
 errno: 'ECONNREFUSED',
 syscall: 'connect',
 address: '127.0.0.1',
 port: 80 }
GET /api/getdifficulty 200 27ms - 39b
{ [Error: connect ECONNREFUSED 127.0.0.1:80]
 code: 'ECONNREFUSED',
 errno: 'ECONNREFUSED',
 syscall: 'connect',
 address: '127.0.0.1',
 port: 80 }
GET /api/getconnectioncount 200 2ms - 39b
{ [Error: connect ECONNREFUSED 127.0.0.1:80]
 code: 'ECONNREFUSED',
 errno: 'ECONNREFUSED',
 syscall: 'connect',
 address: '127.0.0.1',
 port: 80 }
GET /api/getblockcount 200 2ms - 39b
GET /ext/summary 304 72ms

`

**Comment by zilveer** [comment]
Why do you run on port 80 ?
It is a special port which needs special configuration to be able to use it. Run on another port, for example 3001 as in the example.
